### ISSUE TITLE
Documentation: Add reasoning for technology choices

### ISSUE THREAD

**Issue by willvrny** [apprenda/kismatic#103]
It would be great to explain the reasoning behind why certain technologies e.g. Calico were chosen compared to other solutions.

**Comment by josephjacks** [comment]
Great idea. We can add this in the main README.md or in another doc explaining the justification behind the opinions in KET across networking, tracing and other areas as we include defaults across the stack.

**Comment by alexbrand** [comment]
This will be addressed in our networking documentation #692
