### ISSUE TITLE
Provisioner overrides labels when mutating clusters

### ISSUE THREAD

**Issue by emmetthitz** [apprenda/kismatic#1039]
If you spin up a cluster with the provisioner, it populates your plan file. If you add labels to nodes using the plan and apply the labels, then mutate the cluster (either by adding or removing nodes), your labels will be overwritten with nothing when provisioning completes.

**Comment by dkoshkin** [comment]
I suspect this is not just labels but all other options in the plan file.

**Comment by emmetthitz** [comment]
Most likely. I don't think this is a trivial fix, either.
