### ISSUE TITLE
CLI: New Healthcheck command

### ISSUE THREAD

**Issue by willvrny** [apprenda/kismatic#104]
### Scenario:

I've spun up a cluster previously using the Kismatic Enterprise Toolkit and now I'm seeing some issues in the cluster. It would be great to be able to run a command to verify that the basic cluster components are up and running correctly.

It could be possible to reuse some of the existing tests from the validate stage and the smoke test.

**Comment by josephjacks** [comment]
Thanks for the issue, @willvrny.

Can you kindly describe / expound on the cluster issues observed?

What specific cluster components would be useful to add to the existing validator rules?

**Comment by willvrny** [comment]
Sorry @josephjacks I was being theoretical.

I have seen issues with routing that initially appear as applications not being able to talk to each other but that have turned out to be routing issues. Not with Calico but another networking solution in a cluster not setup by Kismatic.

I was thinking it would be nice to be able to quickly diagnose whether its an application issue or a cluster issue?

**Comment by alexbrand** [comment]
@willvrny Do you think https://github.com/apprenda/kuberang covers this use case? Or would you like to see a separate command in `kismatic` that basically runs kuberang?

**Comment by willvrny** [comment]
@alexbrand I think you're right and Kuberang would work great.

Do you think adding a command for it in Kismatic would just add boat to the API?

**Comment by alexbrand** [comment]
Closing as this can be easily done now with `./kismatic ssh master -- sudo kuberang`. We can reopen if we think we need a dedicated command for this.
