### ISSUE TITLE
How to set Feature Flags

### ISSUE THREAD

**Issue by dragoonis** [apprenda/kismatic#1043]
Hey @dkoshkin,

As per this link: https://github.com/kubernetes-incubator/external-storage/tree/master/local-volume#enabling-the-alpha-feature-gates

I need to set these settings to allow me to have local storage on the worker.

I'm on k8s 1.9 and Kismatic v1.7.0

Thanks!

**Comment by dkoshkin** [comment]
You can set the `feature-gates` value in the [kube_apiserver](https://github.com/apprenda/kismatic/blob/master/docs/plan-file-reference.md#clusterkube_apiserveroption_overrides) overrides
