### ISSUE TITLE
Minikube style example fails due to duplicate hostname/IP validations

### ISSUE THREAD

**Issue by scottatron** [apprenda/kismatic#1070]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Bug report

**What happened**:

I tried testing out the single node example with a Vagrant machine as described here: https://github.com/apprenda/kismatic/blob/master/docs/intent.md#minikube

When I specify the same host/IP for etcd, master, and worker, I get validation errors: `Two different nodes cannot have the same IP` or `Two different nodes cannot have the same hostname`.

I tried working around this by giving the Vagrant host 3 IP addresses, and using 3 different hostnames in the kismatic-cluster.yaml, but the `verify hostname` task fails when checking the specified hostnames against the machine's real hostname:

```
- Task: verify hostname
  master: provided hostname does not match reported hostname of localhost.localdomain[ERROR]
  worker: provided hostname does not match reported hostname of localhost.localdomain[ERROR]
  etcd: provided hostname does not match reported hostname of localhost.localdomain[ERROR]
```

**What you expected to happen**:

I would be able to provision a single host local cluster for testing.

**How to reproduce it (as minimally and precisely as possible)**:

Build a single Vagrant host, and try configuring kismatic-cluster.yaml with the same hostname / IP for all roles.

**Anything else we need to know?**:

**Environment**:
- Kismatic version (use `kismatic version`): 1.7.0

**Comment by swade1987** [comment]
Can you provide the kismatic-cluster.yaml file please as well as the output of the runs directory.

**Comment by scottatron** [comment]
Sure, no problem:

- [kismatic-cluster.yaml](https://gist.github.com/scottatron/cba4734a3b42d3cc5fabe50289f4e8b0)
- [runs.zip](https://github.com/apprenda/kismatic/files/1650340/runs.zip)

**Comment by swade1987** [comment]
Looks to me like the hostname in the plan file needs to be `localhost.localdomain`

Kismatic is performing validation against the machines hostname and the ones listed in your plan file and they don't match up.

**Comment by dkoshkin** [comment]
@scottatron we run our integration tests using a few "minikube" clusters without any errors. I would make sure the sections that have the same node have the same `hostname` and both `ip`s

**Comment by dkoshkin** [comment]
@scottatron any update on this?

**Comment by scottatron** [comment]
I just tried to reproduce this again from scratch, and it only seems to occur if you give different host names for each node type, but use the same IP address.

This makes sense—and having since discovered `provision vagrant create-mini` which provides a working example—I think it's probably safe to say this isn't really a bug.

Thanks for your help.
