### ISSUE TITLE
Include Istio as an addon

### ISSUE THREAD

**Issue by swade1987** [apprenda/kismatic#1079]
**Proposed plan file changes**

Add as a service mesh addon but default to `disable:true`

```
service_mesh:
    disable: true
    provider: istio
```

**Proposed architecture**

- Run the Pilot/Auth on master nodes
- Run the Initializer on the master nodes
- Run Mixer with pod anti-affinity
- Replace NGINX Ingress with istio-ingress (envoy) and run as a daemonset on ingress nodes.
- Also deployment Zipkin for tracing by default

@zackbutcher any feedback/advise here is welcomed.

**Comment by ZackButcher** [comment]
That all looks good to me.

One potential place that users could get tripped up is the replacement of NGINX ingress controller with Istio's: they don't have feature parity, and in particular Istio will never support the universe of NGINX specific ingress annotations. A more robust/safer setup would be to keep NGINX ingress as the cluster's primary ingress, and have it forward to Istio's ingress for paths hosted by services in the mesh. Long term if all of your services are in the mesh you'll want to remove the NGINX ingress, but that will require modifying your existing ingress config.

**Comment by swade1987** [comment]
@ZackButcher I am thinking to reduce complexity having a comment in the YAML file to make people aware that if they switch on the Istio service mesh that their ingress definitions will require changing.

**Comment by ZackButcher** [comment]
SGTM

**Comment by magowant** [comment]
@swade1987 I agree with @ZackButcher in that istio feature parity with nginx ingress has not yet been reached. For example, we need https://github.com/istio/issues/issues/50 to be completed before we could consider istio ingress. Having both nginx and istio ingress controllers available, with nginx ingress forwarding to istio where required, would provide a good migration path.
