### ISSUE TITLE
Single node example broken using Ubuntu? DNS will not pass

### ISSUE THREAD

**Issue by javaboyuk** [apprenda/kismatic#108]
After adding aufs_tools to my fresh build then running the plan and using this edited config on ubuntu 16.04.1 fully patched to 21/11/2016. the DNS would not pass the test on the final step of the install

**Comment by alexbrand** [comment]
There's a couple of things we could do to try to figure out what is going on. If you log into the master, you should be able to use kubectl to query the API server for some info.

1. Is your node in the ready state? What is the output of `kubectl get nodes`?
2. What is the status of the kube-dns pod (`kubectl get pods -n kube-system`) ?
3. Is the kube-dns pod logging anything? You can use `kubectl get logs -n kube-system NAME_OF_KUBEDNS_POD` to get the logs by using the correct name as shown in the output of command 2?

Thanks @javaboyuk

**Comment by javaboyuk** [comment]
After much investigation (I am a newbie so takes longer) I have tried also moved to a full implementation as I know JJ got it working.... so etcd x3, master x2 and worker x3, rebuilt and patched a few times with different options, I was using 192.168.x.x for hosts so moved and rebuilt to 10.10.x.x so not to conflict with defaults etc etc... in the end managed to find this!


{"log":"E1125 10:20:24.723381       1 reflector.go:214] pkg/dns/dns.go:155: Failed to list *api.Service: Get https://master-1:6443/api/v1/services?resourceVersion=0: dial tcp: lookup master-1 on 8.8.8.8:53: no such host\n","stream":"stderr","time":"2016-11-25T10:20:24.723688084Z"}
{"log":"I1125 10:20:24.723501       1 dns.go:172] Ignoring error while waiting for service default/kubernetes: Get https://master-1:6443/api/v1/namespaces/default/services/kubernetes: dial tcp: lookup master-1 on 8.8.8.8:53: no such host. Sleeping 1s before retrying.\n","stream":"stderr","time":"2016-11-25T10:20:24.723762158Z"}
{"log":"E1125 10:20:24.723582

So it looks like the conatiner can't look up my master-1 IP address.... which should be in the host file, as I am on a VirtualBox build on my laptop I said I was NOT using DNS and it seemed to suggest the master-1 entry should have been added to the /etc/hosts file (my build has all the machines in their hosts file anyway... so looks like an issue with how ansible installs skyDNS ?

**Comment by javaboyuk** [comment]
yes confirmed

The install of kube-dns does not make the /etc/hosts file visible, hence you need to NOT use a name in the kubeconfig file (as suggested in the install file yaml created by kismatic!) I have posted am issue on the config.
Now I have set the fqdn to the IP address it install:
load_balanced_fqdn: "10.10.0.21"

at last
16/17..  Configure Kubernetes DNS                                               [OK]
17/17..  Configure Kubernetes Dashboard                                         [OK]

Running Smoke Test==================================================================
1/3....  Configure Cluster Prerequisites                                        [OK]
2/3....  Update Hosts File                                                      [OK]
3/3....  Smoke test Master Nodes                                                [OK]
4/3....  Smoke test Master Nodes                                                [OK]

The cluster was installed successfully

**Comment by dasmb** [comment]
Since you got this installed, and your DNS pain is documented elsewhere, I'm gonna close this as a duplicate for now.

https://github.com/apprenda/kismatic/issues/123
