### ISSUE TITLE
upgrade Helm v.2.8.0

### ISSUE THREAD

**Issue by mrgleeco** [apprenda/kismatic#1087]
as of 2018-01-22 - https://github.com/kubernetes/helm/releases/tag/v2.8.0

**Comment by mrgleeco** [comment]
reading through this https://github.com/kubernetes/helm/issues/3371
does older helm 2.7.2 work with 1.9.2?

**Comment by dkoshkin** [comment]
This [one](https://github.com/kubernetes/helm/issues/3382) has me really worried. 
We deploy helm with a `serviceaccount` that has the correct permissions so the issue you linked does not impact us. I've also tested the current helm version and it worked with k8s `v1.9.2`.

**Comment by swade1987** [comment]
I personally feel that Helm v2.8.0 is a little too new to include in KET right now, @dkoshkin thoughts?

**Comment by bacongobbler** [comment]
Don't upgrade to helm 2.8.0. We have a few bugs found both upstream and in our own code which we are working to fix. :)

**Comment by bacongobbler** [comment]
@mrgleeco that erro you point out is just a basic user support issue; it doesn't affect the release.

**Comment by mrgleeco** [comment]
+1 thank you

**Comment by swade1987** [comment]
Closing issue until a more stable version of Helm is released.
