### ISSUE TITLE
Docker storage driver "devicemapper" is not suitable for production use 

### ISSUE THREAD

**Issue by alexbrand** [apprenda/kismatic#109]
The storage driver that we are deploying is not suitable for production according to https://docs.docker.com/engine/userguide/storagedriver/selectadriver/

**Comment by josephjacks** [comment]
@dkoshkin looks like we just need to change to default `devicemapper` storage driver mode from `loop-lvm` to `direct-lvm`.

**Comment by mbentley** [comment]
@josephjacks is correct.  Out of the box, `devicemapper` comes with `loop-lvm` which isn't production ready.  Until `overlay2` gains full support on operating systems like RHEL and CentOS, `devicemapper` with `direct-lvm` is the preferred production configuration for RHEL and CentOS.  For Ubuntu, it is still `aufs` as the preferred graph storage driver.

For proper `devicemapper` configuration, see https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#configure-direct-lvm-mode-for-production.  If you prefer a more automated approach, see https://github.com/mbentley/docker-devicemapper-setup which is based off of mostly the docs linked and with some bits from https://github.com/projectatomic/container-storage-setup.
