### ISSUE TITLE
is docker doc current?

### ISSUE THREAD

**Issue by mrgleeco** [apprenda/kismatic#1103]
**Is this a BUG REPORT or FEATURE REQUEST?**:  Bug 

**What happened**:  

read about new changes in docker config at https://github.com/apprenda/kismatic/releases/tag/v1.8.0 'New Equivalent Config'

saw outdated info at https://github.com/apprenda/kismatic/blob/master/docs/docker.md

**Comment by dkoshkin** [comment]
Thanks for reporting this, yes looks like some of the docs are outdated.
