### ISSUE TITLE
Upgrade checks should properly handle cluster services the installer deployed

### ISSUE THREAD

**Issue by swade1987** [apprenda/kismatic#1104]
I have a default install of KET 1.8.1 with no other workloads deployed.

I upgraded the kismatic-cluster.yaml to leverage Kubernetes 1.9.3

After performing `kismatic upgrade online --verbose` I received the following [errors](https://gist.github.com/swade1987/3f2a471a38d0623c0f62f183b1d3bc84 ) ...

**Comment by dkoshkin** [comment]
This is an issue with all upgrades not just that specific version. The upgrade needs to be reworked to correctly handle errors for services that are deployed by KET.  

For current versions you can hit "Y" when prompted to continue or use the `--ignore-safety-checks` option.
