### ISSUE TITLE
Support metrics-server

### ISSUE THREAD

**Issue by benmathews** [apprenda/kismatic#1116]
FEATURE REQUEST

New versions (1.7+) of kubernetes provide metrics through a metrics server.
https://github.com/kubernetes-incubator/metrics-server
https://kubernetes.io/docs/tasks/debug-application-cluster/core-metrics-pipeline/

Please support automatic installation

**Comment by dkoshkin** [comment]
[This is unfortunate](https://github.com/kubernetes/heapster/issues/1840). Those v1.8 release notes were not clear at all.

Thanks for bringing this up. We will work on adding this as it looks like HPA does not work without the metrics-server.

**Comment by dkoshkin** [comment]
Ok looks like the HPA does in fact NOT function properly without having the metrics-server (although `kubectl top` does work with just `heapster`)
```
I0215 17:44:02.278877       1 event.go:218] Event(v1.ObjectReference{Kind:"HorizontalPodAutoscaler", Namespace:"default", Name:"nginx-deployment", UID:"87b68664-1277-11e8-b868-080027c30a85", APIVersion:"autoscaling/v2beta1", ResourceVersion:"5281", FieldPath:""}): type: 'Warning' reason: 'FailedComputeMetricsReplicas' failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from API: the server could not find the requested resource (get pods.metrics.k8s.io)
```

Trying to deploy the metrics-server results in an error:
```
F0215 17:46:20.335656       1 heapster.go:97] Could not create the API server: cluster doesn't provide requestheader-client-ca-file
```

Relevant issue https://github.com/Azure/acs-engine/issues/1390
