### ISSUE TITLE
Kubelet: failed to create kubelet: misconfiguration: kubelet cgroup driver: "cgroupfs" is different from docker cgroup driver: "systemd"

### ISSUE THREAD

**Issue by engineerakki** [apprenda/kismatic#1117]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG-Report

**What happened**: My ./kismatic install validate was successful,
But while running ./kismatic install apply, my kubelet service doesn't start with the error

error: failed to run Kubelet: failed to create kubelet: misconfiguration: kubelet cgroup driver: "cgroupfs" is different from docker cgroup driver: "systemd"

 

**What you expected to happen**:  Install process should be successfel, this can be checked in validate step.

**How to reproduce it (as minimally and precisely as possible)**:
Install kubernetes cluster Install on RHEL 7.4 via kismatic

**Anything else we need to know?**:

**Environment**:
- Kismatic version (use `kismatic version`): 1.8.1
- Plan file Gist (remove sensitive information if any): 
- Cloud provider or hardware configuration: Baremetal
- OS (e.g. from /etc/os-release): RHEL 7.4
- Kernel (e.g. `uname -a`): Linux app-linux2.lab.com 3.10.0-514.16.1.el7.x86_64 #1 SMP Fri Mar 10 13:12:32 EST 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dkoshkin** [comment]
@engineerakki Was `docker` already installed on the machine or did you allow KET to install it? From all of our testing kubelet automatically detects the correct option to use.

You can also override the `kubelet` option in the plan file with:
```
...
  kubelet:
    option_overrides: 
      cgroup-driver: "systemd"
...
```

**Comment by engineerakki** [comment]
@dkoshkin 
Thanks.

Overriding the cgroup driver works.

I have let KET install docker for me. It installed Docker version 17.03.2-ce, build f5ec1e2
