### ISSUE TITLE
Error on stage smoke test on Azure VMs

### ISSUE THREAD

**Issue by DmitriyProkhorov** [apprenda/kismatic#1119]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**What happened**:
When deploying cluster K8S I get error:

Running Smoke Test==================================================================
Smoke Test Master Node                                                          [ERROR]
- Task: run smoke test checks using Kuberang
  k8s-master1-lab2:                                                             [ERROR]
---- STDOUT ----
Kubectl configured on this node                                                 [OK]
Delete existing deployments if they exist                                       [OK]
Nginx service does not already exist                                            [OK]
BusyBox service does not already exist                                          [OK]
Nginx service does not already exist                                            [OK]
Issued BusyBox start request                                                    [OK]
Issued Nginx start request                                                      [OK]
Issued expose Nginx service request                                             [OK]
Both deployments completed successfully within timeout                          [OK]
Grab nginx pod ip addresses                                                     [OK]
Grab nginx service ip address                                                   [OK]
Grab BusyBox pod name                                                           [OK]
Accessed Nginx service at 172.20.74.99 from BusyBox                             [OK]
Accessed Nginx service via DNS kuberang-nginx-1519132554597704825 from BusyBox  [OK]
Accessed Nginx pod at 172.16.128.133 from BusyBox                               [ERROR]
-------- OUTPUT --------
wget: download timed out
command terminated with exit code 1
------------------------

Accessed Nginx pod at 172.16.151.70 from BusyBox                                [OK]
Accessed Google.com from BusyBox                                                [OK]
Accessed Nginx pod at 172.16.128.133 from this node                             [ERROR IGNORED]
Accessed Nginx pod at 172.16.151.70 from this node                              [ERROR IGNORED]
Accessed Google.com from this node                                              [OK]
Powered down Nginx service                                                      [OK]
Powered down Busybox deployment                                                 [OK]
Powered down Nginx deployment                                                   [OK]
---- STDERR ----
Error running command: One or more required steps failed
---------------
error running smoke test: error running playbook: error running ansible: exit status 2

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy infrastructure from Azure powershell script (in the attachment p.s. edit own settings: $env, $SSHKeyPath, $SSHKeyPath_AuthPath, $securePassword,
[k8s-azure.zip](https://github.com/apprenda/kismatic/files/1740290/k8s-azure.zip)
)
2. Login to k8s-devops VM
3. Download KET
4. Use kismatic-cluster.yaml (in the attachment p.s. edit hostname)
5. run ./kismatic install apply and get error

**Anything else we need to know?**:
The simple configuration 1 master+1 worker+1 etcd on the one VM works 
**Environment**:
- Kismatic version (use `kismatic version`): 1.8.1
- Plan file Gist (remove sensitive information if any): 
- Cloud provider or hardware configuration: IaaS on Azure
- OS (e.g. from /etc/os-release): CentOS 7.3
- Kernel (e.g. `uname -a`): 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dkoshkin** [comment]
@DmitriyProkhorov `calico` is not supported on Azure, you will need to use `weave` as your CNI provider.

**Comment by DmitriyProkhorov** [comment]
Thanks!
And what are the best options to set for the weave in the file kismatic-cluster.yaml?

**Comment by dkoshkin** [comment]
https://github.com/apprenda/kismatic/blob/master/docs/plan-file-reference.md#add_onscnioptions

```
add_ons:
  cni:
    disable: false

    # Selecting 'custom' will result in a CNI ready cluster, however it is up to
    # you to configure a plugin after the install.
    # Options: 'calico','weave','contiv','custom'.
    provider: weave
```

**Comment by DmitriyProkhorov** [comment]
Thanks
It works

**Comment by DmitriyProkhorov** [comment]
Please tell me how to specify options, for example, overlay

**Comment by dkoshkin** [comment]
We don't expose any `weave` options, we deploy the default from their repo https://github.com/apprenda/kismatic/blob/master/ansible/roles/weave/templates/weave.yaml

**Comment by dkoshkin** [comment]
Yes, I believe there is no other mode for `weave`

**Comment by DmitriyProkhorov** [comment]
Many thanks!
