### ISSUE TITLE
How to re-install a deployment or daemonset that has been deleted with kubectl

### ISSUE THREAD

**Issue by bobclarke** [apprenda/kismatic#1143]
**Is this a BUG REPORT or FEATURE REQUEST?**: Not sure

**What happened**:
The kube-dns and coredns Deployments were deleted with kubectl

**What you expected to happen**:
I expected these to be re-installed when I ran "kismatic install apply". I.e i would have expected ansible to detect the change and ensure the cluster was returned to the desired state as specified by the plan file.

**How to reproduce it (as minimally and precisely as possible)**:
Delete kube-dns and coredns deployments and then run kismatic install apply in an attempt to de-install them

**Anything else we need to know?**:
Essentially I need to understand how to re-initilaise any component of the cluster (or even the whole existing  cluster as if from scratch) with kismatic. 

**Environment**:
- Kismatic version (use `kismatic version`): 1.8.1
- Plan file Gist (remove sensitive information if any): 
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release):
        NAME="Red Hat Enterprise Linux Server"
        VERSION="7.4 (Maipo)" 
        ID="rhel"

- Kernel (e.g. `uname -a`): 3.10.0-693.17.1.el7.x86_64

**Comment by dkoshkin** [comment]
If you rerun `kismatic install apply` the deployments will be installed again. Under the hood KET runs `kubectl apply` for deploying services, this command is idempotent and will always be rerun.

You can also run `kismatic install step _cluster-dns.yaml` (or any other `_*.yaml` file from the Ansible directory), this will run just that one play.

**Comment by bobclarke** [comment]
Many thanks
