### ISSUE TITLE
Label ingress nodes in kubelet.service

### ISSUE THREAD

**Issue by willvrny** [apprenda/kismatic#1147]
**BUG REPORT**:

**What happened**:

Losing an ingress node from the API also loses the 'kismatic/ingress=true' label. If the node is then brought back the label needs to be re-applied for the ingress workloads to be rescheduled onto it.

If the label was set in the 'kubelet.service' then it would have re-registered with the label.

**Comment by dkoshkin** [comment]
This is how the nodes were labeled a few releases ago however this was shown to be problematic during upgrades. The labels only get applied the first time a node gets registered, so making changes to the labels in the future does not work as expected.
