### ISSUE TITLE
`install validate` fails in Kerberized Automount environment

### ISSUE THREAD

**Issue by briantopping** [apprenda/kismatic#1151]
PS: slack.kismatic.com does not resolve and kismatic.slack.com says it's not possible to apply unless one is (apparently) a partner.

**Is this a BUG REPORT or FEATURE REQUEST?**: Both?

**What happened**: 

Installing in a Kerberized autofs environment seems impossible. My k8s nodes are set up as FreeIPA IDM clients with autofs and Kerberos. In a nutshell, this means I can get a TGT on the start node, `ssh` to a target node, and my TGT will forward to the target node. On initial access, automount will mount the home directory, but it's NFSv4, so if the TGT is not forwarded (because it does not exist on the source client or otherwise), the directory will not be accessible. With the Kismatic installer, regardless of whether a TGT exists for `kismaticuser` in the administrator keyring, the ticket is not forwarded. The login proceeds, but without a ticket, the home directory is inaccessible, and in turn, Ansible cannot create a work directory in `~/.ansible/tmp` on the target node. 

The node is reported as UNREACHABLE when in fact the node is quite reachable, but Ansible cannot bootstrap.

**What you expected to happen**: 

I recognize this is a rather advanced operational environment. https://www.virtualtothecore.com/en/manage-automatic-kerberos-login-in-ansible-for-active-directory-accounts/ has a basic breakdown of Kerberos use in Ansible, but I get the feeling that the author is referring to specific kerberized tasks within Ansible rather than Ansible taking advantage of a valid kerberos context if it exists. 

I've tried a few things but none have seemed to work:
* As above, simply getting a ticket for the `kismaticuser`.
* Making sure that `python-gssapi` is installed for `parameko`.
* Trying to add `ansible_connection: ssh` to the `kismatic-cluster.yaml` file.

**How to reproduce it (as minimally and precisely as possible)**:
* You could probably see the error by just deleting the home directory on a target node. This is equivalent to `automount` not being able to publish the directory.
* If you wanted an environment that could demonstrate the system working, you'd need to have automount working with NFSv4 and Kerberos infrastructure in place. I run with FreeIPA for all that.

**Anything else we need to know?**: It seems like Ansible is not being configured correctly. I'd be happy to run some tests, ideally starting with getting `ansible_connection: ssh`. But I'm good to go and am happy to screenshare if anyone is interested.

**Environment**:
- Kismatic version (use `kismatic version`): Kismatic:
  Version: 1.8.1
  Built: Wed Feb  7 16:54:50 UTC 2018
  Go Version: go1.9.2
- Plan file Gist (remove sensitive information if any): https://gist.github.com/briantopping/94121f1dfdb0fbbb441ca9a047efba06
- Cloud provider or hardware configuration: XenServer 7.3
- OS (e.g. from /etc/os-release): CentOS Linux release 7.4.1708 (Core)
- Kernel (e.g. `uname -a`): Linux salt.kbjc.coglative.com 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dkoshkin** [comment]
@briantopping Im not sure if I'm understanding the question fully. You do have a method to override all `ansible.cfg` settings in `ansible/playbooks/ansible.cfg`, but I dont know if Ansible supports this setup.

**Comment by briantopping** [comment]
Ok, thanks @dkoshkin. I'll close for now with that info. 

If Ansible doesn't support what I'm trying to do, it's probably out-of-scope in general. I think it does, and I didn't know there was a supported path for tweaking Ansible. 

When I wrote this up, I also wanted to provide some breadcrumbs if anyone else came up against the same issues. Happy to help if someone does.

**Comment by dkoshkin** [comment]
Thanks for the update.
