### ISSUE TITLE
Adding a Role to Existing Nodes

### ISSUE THREAD

**Issue by DmitriyProkhorov** [apprenda/kismatic#1165]
**Is this a BUG REPORT or FEATURE REQUEST?**: How to

**What happened**:
I installed the cluster in the configuration: etcd-3, master-2, worker-2, ingress-0
Then I wanted to add a ingress role to worker nodes
Which way is correct?

The command:
**Kismatic install add-node k8s-worker1 IP1 IP2 --roles ingress**
ends with an error:
**according to the plan file, the host name of the new node is already being used by another worker node**

**Environment**:
- Kismatic version (use `kismatic version`): 1.9.1
- Plan file Gist (remove sensitive information if any):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):

**Comment by dkoshkin** [comment]
You can modify the plan file copying the node details to the new desired section and rerunning `kismatic install apply`

**Comment by DmitriyProkhorov** [comment]
Do I need to use additional keys when I rerun the kismatic install apply? For example:
--skip-preflight
--restart-services

**Comment by dkoshkin** [comment]
No with the newest version it will work without any extra flags.
