### ISSUE TITLE
Restart services single node

### ISSUE THREAD

**Issue by mjschmidt** [apprenda/kismatic#1191]
Am I able to restart services on only a single node?

**Comment by mjschmidt** [comment]
Using v1.9.1 of kismatic

**Comment by emmetthitz** [comment]
Unfortunately not, sorry @mjschmidt.

**Comment by mjschmidt** [comment]
If host 1 is a single node then yes that is what I am looking for (: Thanks @dkoshkin!(?)

**Comment by mjschmidt** [comment]
If not, its not terrible to ssh over to a node and restart the services
