### ISSUE TITLE
Change kubernetes cluster version in KET plan file

### ISSUE THREAD

**Issue by DmitriyProkhorov** [apprenda/kismatic#1206]
**Is this a BUG REPORT or FEATURE REQUEST?**: How TO

**What happened**:
Is the correct way to change the version of kubernetes in the kismatic plan file before this version comes out in KET?
For example, I want to update the version of kebernetes from 1.10.0 to 1.10.1 with KET 1.10.0
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kismatic version (use `kismatic version`): 1.10.0
- Plan file Gist (remove sensitive information if any): 
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3
- Kernel (e.g. `uname -a`):

**Comment by dkoshkin** [comment]
Yeah that's exactly why that option was added in the plan file, to support a version without the tool being rereleased, just set the `version` in the plan file.
