### ISSUE TITLE
Allow passing --limit to install 

### ISSUE THREAD

**Issue by leehanel** [apprenda/kismatic#1211]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature Request - specifically the ability to target a single node.

**What happened**:

when running kismatic install step(or kismatic install apply), All nodes are targeted

**What you expected to happen**:

When adding a --limit option, kismatic should pass that to ansible so it only runs on passed nodes

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
Currently using v1.9.0

**Comment by dkoshkin** [comment]
@leehanel a `--limit` option was added in v1.9.0, for `apply`, `validate` and `step` commands in this [PR](https://github.com/apprenda/kismatic/pull/1158), is the issue saying that using that option didn't work for you?

**Comment by leehanel** [comment]
ok, i didn't see it in the command help .
    `./kismatic install apply --help
apply your plan file to create a Kubernetes cluster

Usage:
  kismatic install apply [flags]

Flags:
      --generated-assets-dir string   path to the directory where assets generated during the installation process will be stored (default "generated")
  -h, --help                          help for apply
  -o, --output string                 installation output format (options "simple"|"raw") (default "simple")
      --restart-services              force restart cluster services (Use with care)
      --skip-preflight                skip pre-flight checks, useful when rerunning kismatic
      --verbose                       enable verbose logging from the installation

Global Flags:
  -f, --plan-file string   path to the installation plan file (default "kismatic-cluster.yaml")`

and we are on version 1.9.0:
`./kismatic  version
Kismatic:
  Version: 1.9.0
  Built: Wed Feb 28 15:18:53 UTC 2018
  Go Version: go1.9.3`

so, maybe it just needs to be added to the help?

**Comment by dkoshkin** [comment]
My mistake, that feature was actually added in `v1.9.2`, please try with that version and see if it fits your usecase.

**Comment by leehanel** [comment]
@dkoshkin yep, added in 1.9.2, and in the --help.
Thanks, I missed that.
