### ISSUE TITLE
Persistence Storage

### ISSUE THREAD

**Issue by coolpalani** [apprenda/kismatic#1215]
I have deployed the K8s cluster on Google clour platform using Kismatic
How do I provision persistence storage (gce-pd) or LoadBalancer.

I had created the storage class and tried to provision using kubectl, but it's showing pending and not creating.

kubectl apply -f ssd-storageclass.yaml
kubectl apply -f ssd-claim.yaml
[](url)https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes
or should we want to build storage like rook and manage as our self.

**Comment by coolpalani** [comment]
Kindly take this some one and respond to this query

**Comment by dkoshkin** [comment]
@coolpalani when you deployed did you specify the options below:
```
  # Kubernetes cloud provider integration.
  cloud_provider:

    # Options: 'aws','azure','cloudstack','fake','gce','mesos','openstack',
    # 'ovirt','photon','rackspace','vsphere'.
    # Leave empty for bare metal setups or other unsupported providers.
    provider: ""

    # Path to the config file, leave empty if provider does not require it.
    config: ""
```

**Comment by coolpalani** [comment]
I didn't specify.
Could you let me know the procedure to specify.

**Comment by coolpalani** [comment]
@dkoshkin 

I had even found sample cloud config file for Azure.
[https://raw.githubusercontent.com/alexbrand/ket-on-azure/master/azure-cloud-provider.conf.sample](https://raw.githubusercontent.com/alexbrand/ket-on-azure/master/azure-cloud-provider.conf.sample)
I don't find yet for google.

could you share some sample config file

**Comment by dkoshkin** [comment]
Looks like you found a @techjw project already, he has successfully used https://github.com/techjw/k8s-gcp to setup cluster with cloud provider enabled.
