### ISSUE TITLE
Clarify the system requirements for KET

### ISSUE THREAD

**Issue by eriklg** [apprenda/kismatic#122]
I wanted to find the system requirements for installing KET but didnt find the location very easy to find. The requirements should be in the main readme for the repository or at least linked from there to the detailed documentation under the PLAN section.

**Comment by alexbrand** [comment]
Added a section in the docs that lists the operating systems that we currently support. I think this was the main concern brought up by @eriklg. Feel free to reopen if you think we are missing something else.
