### ISSUE TITLE
install apply failure during helm/tiller provisioning

### ISSUE THREAD

**Issue by kmkramer** [apprenda/kismatic#1231]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
**What happened**:

fatal: [hostname.domain.com -> localhost]: FAILED! => {
"cmd": "../../helm init --service-account=tiller -i=gcr.io/kubernetes-helm/tiller:v2.8.2 --tiller-namespace=kube-system --upgrade

**What you expected to happen**:
plan complete install

**How to reproduce it (as minimally and precisely as possible)**:
plan file with 4 VMware hosts. 3 are etcd/master and 1 worker, no ingress/storage

**Anything else we need to know?**: cluster appears up otherwise without helm/tiller bits

**Environment**:
- Kismatic version (use `kismatic version`):
Kismatic:
  Version: 1.10.0
  Built: Fri Apr 13 19:28:04 UTC 2018
  Go Version: go1.9.4

- Plan file Gist (remove sensitive information if any): https://gist.github.com/kmkramer/1c85d87af35af4ca122adf0a42af850b
- Cloud provider or hardware configuration: VMware
- OS (e.g. from /etc/os-release):  16.04.4 LTS
- Kernel (e.g. `uname -a`):  4.4.0-122-generic

**Comment by dkoshkin** [comment]
Seems like a flake, can you try rerunning the install.

**Comment by kmkramer** [comment]
I actually did a kismatic reset on it ,deleted the generated dir and retried the whole thing. same problem.
it would be nice to not have to deploy a worker up front.... I'll switch workerA with hostnameC and see what happens just to see if the problem follows a node. but these vm host were created identically with Ubuntu PXE preseed

**Comment by kmkramer** [comment]
same problem. it seems to bork on the first node in the list or either etcd node or master node

**Comment by dkoshkin** [comment]
In `generated/runs` can you get the logs for this step and copy them here.

**Comment by kmkramer** [comment]
[apply.zip](https://github.com/apprenda/kismatic/files/1988122/apply.zip)
[preflight.zip](https://github.com/apprenda/kismatic/files/1988124/preflight.zip)

**Comment by dkoshkin** [comment]
Is the `helm` binary in the directory, what is the output for `ls -la`? Are you running the install from the `kismatic` directory or somewhere else?

**Comment by kmkramer** [comment]
well my helm/kismatic/kubectl binaries are in ~/bin/. didn't have this issue on another cluster with just 3 machines acting as 1 etcd, 1 master and 1 worker. I'll run again with the binaries in the cwd. is there also a way to specifiy a "run" output dir? would be nice if kismatic could just read in the clustername var from the plan file and automatically use it to organized the generated/runs outputs.

**Comment by kmkramer** [comment]
that worked much better. thanks and sorry for the noise.
