### ISSUE TITLE
Сan not add a worker node to the cluster

### ISSUE THREAD

**Issue by DmitriyProkhorov** [apprenda/kismatic#1238]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug
**What happened**:
I want to add a node to the cluster
I use the command:
./kismatic install add-node k8s-worker3-prod 10.2.0.108 10.2.0.108 --roles worker
As a result I get an error:
Running Pre-Flight Checks On New Node===============================================
Copy Kismatic Inspector                                                         [OK]
Configure Cluster Prerequisites                                                 [OK]
Gather Node Facts                                                               [OK]
Update Hosts File                                                               [SKIPPED]
Run Cluster Pre-Flight Checks                                                   [OK]

Generating Certificate For New Node=================================================
Generated certificate for k8s-worker3-prod kubelet                              [OK]
Found valid certificate for etcd client                                         [OK]

Adding New Node to Cluster==========================================================
Configure Cluster Prerequisites                                                 [OK]
Gather Node Facts                                                               [OK]
Copy Addition Files and Directories                                             [SKIPPED]
Deploy Cluster Certificates                                                     [OK]
Generate Kubectl Config File                                                    [OK]
Configure Package Repositories                                                  [OK]
error running playbook: error running playbook: error running ansible: exit status 2

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kismatic version (use `kismatic version`): v1.10.0
- Plan file Gist (remove sensitive information if any): 
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): Ubuntu LTS 16.04
- Kernel (e.g. `uname -a`):

**Comment by dkoshkin** [comment]
In the run's directory can you find ansible.log and share the contents of the end of the file it should tell you what is actually failing.

**Comment by DmitriyProkhorov** [comment]
Thanks
Logs helped
