### ISSUE TITLE
Cloud Provider Support

### ISSUE THREAD

**Issue by srjturner** [apprenda/kismatic#124]
I created some AWS hosts and successfully used Kismatic to install Kubernetes. However, when I tried to use an EBS volume this failed. Checking /etc/systemd/system/kubelet.service on workers and masters I realised that --cloud-provider is empty. Manually setting --cloud-provider to "aws" and restarting the kubelet service then fails with:
```
Zone not specified in configuration file; querying AWS metadata service
Nov 25 06:25:04 ip-172-15-1-114.eu-west-1.compute.internal kubelet[9542]: error: failed to run Kubelet: could not init cloud provider "aws": error finding instance i-0054f74dfec8d7fc9: error listing AWS instances: NoCredentialProviders: no valid providers in chain
```

Looking again at kube-up for comparison, it seems that this is probably because Kismatic doesn't do the IAM role setup that kube-up does (see [here](https://medium.com/@canthefason/kube-up-i-know-what-you-did-on-aws-93e728d3f56a#.n80meac1x)) so it can't talk to AWS. That would mean it can't do any of the cloud integrations that Kubernetes is capable of.

Is my reasoning correct? And is AWS integration anywhere on the roadmap?

**Comment by dasmb** [comment]
To date we've been bare metal focused and thus don't have any provider specific features, including the automatic provisioning of S3, AWS or ELBs. 

That said, at Apprenda we do much testing on AWS and would get value out of some deeper integration. It's likely we'll take a different approach than Kube-up -- our goal is to put cluster operators in control of essential decisions, and this would include keys and networking.

**Comment by swade1987** [comment]
Would be great to see if we can integrate KET with Terraform

**Comment by dasmb** [comment]
What would you want out of a Terraform integration?

**Comment by dasmb** [comment]
Three K8s tools that need to be informed of cloud details:

http://kubernetes.io/docs/admin/kube-controller-manager/
http://kubernetes.io/docs/admin/kube-apiserver/
http://kubernetes.io/docs/admin/kubelet/

**Comment by pires** [comment]
I believe we should keep track of [this proposal for refactoring cloud provider API](https://github.com/kubernetes/community/pull/128), particularly [section 5,  Strategy for refactoring Volumes](https://github.com/kubernetes/community/pull/128/files#diff-7bdcb15bb8800f186f4693e9d0a7f9d1R104).

**Comment by eicnix** [comment]
I am using KET and would like to integrate Kubernetes to the Cloud platform I am using. Would it be OK to add two parameters "cloud_provider" and "cloud_config_path" to the KET configuration and set these values in every component that needs a cloud provider?

**Comment by swade1987** [comment]
Hi @eicnix which cloud platform are you using out of interest.

**Comment by eicnix** [comment]
I am using vSphere.
