### ISSUE TITLE
kube-dns in container creation state

### ISSUE THREAD

**Issue by snyamars** [apprenda/kismatic#1241]
** BUG REPORT **:

**What happened**:
kube-dns in container creation state after re-deploying with manually generated certificates

**What you expected to happen**:
kube-dns service to start normally

**How to reproduce it (as minimally and precisely as possible)**:
Generate certificates using cfssl utility and replace the existing certificates with new ones.
Restart the services.

**Anything else we need to know?**:

**Environment**:
- Kismatic version (use `kismatic version`): 1.9
- Plan file Gist (remove sensitive information if any): 
- Cloud provider or hardware configuration: AWS IAAS
- OS (e.g. from /etc/os-release): Ubuntu 16.04.4 LTS (Xenial Xerus)
- Kernel (e.g. `uname -a`): x86_64 x86_64 x86_64 GNU/Linux

**Comment by snyamars** [comment]
kube-dns events show - Failed create pod sandbox

**Comment by dkoshkin** [comment]
Which certificates are you generating manually or is it all of them? Are you sure that the CN and SANs are identical to what is automatically generated?

**Comment by dkoshkin** [comment]
Hey I just actually finished going through this, here are the [details for all the certs](https://docs.google.com/spreadsheets/d/1bTQCleCDlMh1-o9Vl2meyGiYp-159rVKOgc0PMOoc8s/edit?usp=sharing).

**Comment by snyamars** [comment]
Hey @dkoshkin - Thank you. It helps. Let me try again.
