### ISSUE TITLE
24 node cluster has trouble validating prechecks?

### ISSUE THREAD

**Issue by mjschmidt** [apprenda/kismatic#1262]
**BUG REPORT**:

**What happened**:
So I am able to add nodes one by one, but when I get to larger cluster creation I have issues validating and installing the cluster. I have an existent 24 node (3 master 21 worker) cluster I want to upgrade, but I can't get past validation.

My validation fails at - Run Cluster Pre-Flight Checks
   - Task: verify worker to worker node connectivity using IP
error running playbook: error running ansible: exit status 1

**What you expected to happen**:
Cluster to go through and be able to validate/upgrade. Or if I did something wrong in the yaml for install it would at least tell me what IP to fix

**How to reproduce it (as minimally and precisely as possible)**:
This might be a "how do I get more verbose response" but to reproduce create a quick cluster with 3 nodes dedicated for masters, and 21 dedicated for workers and then just set up your yaml and try to see if you can get validation to work. Also the playbook might be failing because its timing out? Is there a place I can set that timeout higher?

**Anything else we need to know?**:

**Environment**:
- Kismatic version: So I was using like 1.9.3 but I switched to the 1.11 to do the upgrade
- Plan file Gist (remove sensitive information if any): 
- Cloud provider or hardware configuration: Hardware Centos 7.5, by the way this does work on CentOS 7.5!
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`): 3.10.0-963.21.1 (I think? Though this doesn't seem like a kernel problem)

**Comment by dkoshkin** [comment]
Please share the relevant Ansible logs in `runs/preflight/2018-06-28-08-18-43/ansible.log`.

**Comment by mjschmidt** [comment]
Sorry also I did just find the verbose command, so here is an update on the error
For those wondering, its just an easy --verbose flag.

I can't share logs because I am in offline environment. What should I be looking for?

**Comment by dkoshkin** [comment]
At the end of the file for the task that is failing there might be something that points to why its failing.

**Comment by mjschmidt** [comment]
Okay let me take a look. I am waiting for the preflight validate to finish with verbose on to see if I can see anything

**Comment by mjschmidt** [comment]
I got exit status 250 at Running task verify worker to worker node connectivity using ip.

**Comment by mjschmidt** [comment]
I may need a script that just runs over all the nodes and has every node ssh to each other ahead of time. I think that is where the fail is coming... I went to a random worker node and then tried to ssh over to a different random worker node and I got a "are you sure you want to connect" and I had to type yes before it worked. So the playbook is probably trying to ssh worker to worker and being unhappy because it can't ssh automatically?

**Comment by dkoshkin** [comment]
The option `host_key_checking` should already be set. Are these IPs reused from before and already in `/Users/dkoshkin/.ssh/known_hosts` with a different identity?

**Comment by mjschmidt** [comment]
AH I see it now, OSError Cannot allocate memory I will sudo code transcribe the error I see:

ERROR! Unexpected exception Cannot allocate Memory

The traceback doesn't seem especially helpful but if you want I can transcribe that. Just let me know

**Comment by dkoshkin** [comment]
How much ram does the install node have, by default we set `forks = 50` (runs tasks on up to 50 nodes). That does require some RAM, you can try either using a larger install node or modify the `forks` option to something less in `ansible/playbooks/ansible.cfg`.

**Comment by mjschmidt** [comment]
Its not especially large. Its maybe... 4GB total but I know some other stuff is there running too...

So Yeah let me try lowering the forks.

**Comment by mjschmidt** [comment]
I got Error a worker was found in a dead state. But a kubectl get nodes show all nodes as ready?

**Comment by mjschmidt** [comment]
META: noop
META: noop
META: noop
ERROR! A worker was found in a dead state

So I guess I might have put something wrong in my yaml. I am off to investigate

**Comment by mjschmidt** [comment]
Walked through my yaml file... every node was alive. Why could I be getting a worker was dead error?

**Comment by dkoshkin** [comment]
I think that error is from Ansible not being bale to connect, should be able to rerun.

**Comment by mjschmidt** [comment]
I did have two ingress nodes that for some reason when I did node-add --role= ingress didn't add them as ingress nodes to the yaml file. I added those as ingress to see if that helps this part of the validate script.

**Comment by mjschmidt** [comment]
META: noop
META: noop
META: noop
ERROR! A worker was found in a dead state

No workers are dead... I just sshed to all of them? Possibly lower the forks more? I went to 25.

**Comment by mjschmidt** [comment]
It looks like I was able to have that work when I decreased the forks running to 10 and it got further... now I took it down to 5. Slow crawl but hopefully this is my issue...

**Comment by mjschmidt** [comment]
Dang it still out of memory...

**Comment by mjschmidt** [comment]
A a more helpful error from the new kismatic version. it looks like 5 of my nodes were unreachable... even though I can definitely reach them. So I don't know what is up with that. I will have to check the logs.

**Comment by mjschmidt** [comment]
So a second validate test. a different set of nodes were unreachable via the kismatic inspector from the master. That seems like a bug since its not a standard set of nodes it can't reach?

**Comment by mjschmidt** [comment]
A 3rd run yielded a successful test no nodes reported down. So yah bug?

**Comment by dkoshkin** [comment]
I've seen that `UNREACHABLE` error before and its coming from Ansible. Unfortunately it could be related to networking quirks and other flakiness.

I will close this for now, feel free to reopen if you see the issue again.
