### ISSUE TITLE
metrics-server start failed. status is CrashLoopBackOff

### ISSUE THREAD

**Issue by chicago7** [apprenda/kismatic#1283]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 BUG REPORT

**What happened**:

I0411 03:09:30.784560       1 heapster.go:71] /metrics-server --source=kubernetes.summary_api:''
I0411 03:09:30.784637       1 heapster.go:72] Metrics Server version v0.2.1
I0411 03:09:30.784846       1 configs.go:61] Using Kubernetes client with master "https://10.0.0.1:443" and version 
I0411 03:09:30.784862       1 configs.go:62] Using kubelet port 10255
I0411 03:09:30.785670       1 heapster.go:128] Starting with Metric Sink
I0411 03:09:31.372204       1 serving.go:308] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
F0411 03:09:31.904501       1 heapster.go:97] Could not create the API server: cluster doesn't provide requestheader-client-ca-file

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

1. aks engine v0.31.1
2. k8s01.json

{
"apiVersion": "vlabs",
  "location": "chinaeast2",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.12.5",
      "kubernetesConfig": {
        "clusterSubnet": "10.244.0.0/16",
        "networkPlugin": "kubenet",
        "networkPolicy": "calico",
        "enableRbac": false,
        "addons": [
          {
            "name": "tiller",
            "enabled": false
          },
          {
            "name": "kubernetes-dashboard",
            "enabled": false
          },
          {
            "name": "blobfuse-flexvolume",
            "enabled": false
          },
          {
            "name": "keyvault-flexvolume",
            "enabled": false
          }
        ],
        "apiServerConfig": {
          "--enable-admission-plugins": "DenyEscalatingExec,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,ExtendedResourceToleration"
        }
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "test03",
      "vmSize": "Standard_A2m_v2",
      "firstConsecutiveStaticIP": "172.16.0.200",
      "vnetSubnetId": "*************************",
      "storageProfile": "ManagedDisks"
    },
    "agentPoolProfiles": [
      {
        "availabilityProfile": "AvailabilitySet",
        "name": "test02",
        "count": 1,
        "vmSize": "Standard_A2m_v2",
        "vnetSubnetId": "*******************************",
        "storageProfile": "ManagedDisks",
        "osType": "Linux"
      }
    ],
    "linuxProfile": {
      "adminUsername": "test02",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "*********",
      "secret": "**********"
    }
  }
}
**Anything else we need to know?**:

**Environment**:
- Kismatic version (use `kismatic version`):
- Plan file Gist (remove sensitive information if any): 
- Cloud provider or hardware configuration: azure 
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):

**Comment by JasonvanBrackel** [comment]
@chicago7 This hasn't had a commit since June of 2018 and is likely dead.  I would suggest looking into [RKE](https://rancher.com/docs/rke/latest/en/) or [kubeadm](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm/)

**Comment by chicago7** [comment]
@JasonvanBrackel Thanks for your reply. Do you encounter the same issue before? i find same issue in github(https://github.com/Azure/acs-engine/issues/2421) i try to fix the issue, but didn't work
