### ISSUE TITLE
Write docs on how default KET docker registry works with existing user registry

### ISSUE THREAD

**Issue by josephjacks** [apprenda/kismatic#129]

**Comment by dkoshkin** [comment]
There is this [document](https://github.com/apprenda/kismatic/blob/master/docs/DOCKER_REGISTRY.md).

Did you have anything else in mind?

**Comment by alexbrand** [comment]
Closing as this is currently documented. Please re-open if docs need clarification/improvement.

**Comment by josephjacks** [comment]
We don't link to it anywhere in the main docs sections. I'll fix that.
