### ISSUE TITLE
Separate SSH keypairs for core K8s components

### ISSUE THREAD

**Issue by swade1987** [apprenda/kismatic#152]
For security reasons it would be useful to have the option of supplying different SSH keypairs for the Master, Worker and Etcd nodes.

**Comment by dasmb** [comment]
What is the security goal envisioned by this technique?

Would providing the ability to supply a key per node solve your issue, or does it need to be by role?

**Comment by swade1987** [comment]
I would propose a key per role. It reduces the attack surface area if somebody gets the key currently they have the keys to the kingdom.

**Comment by swade1987** [comment]
Closing this issue as I feel others take priority.
