### ISSUE TITLE
Perform node connectivity checks during preflight

### ISSUE THREAD

**Issue by alexbrand** [apprenda/kismatic#159]
I have run into an issue on Packet where the machines are unable to talk to each other after being provisioned. However, this is not being caught during preflight. The end result is that the installation fails further down the line.

I am not sure how we can perform this check efficiently, as this will most likely not scale.

**Comment by dasmb** [comment]
Every etcd node should be reachable from every master node.
Every master node should be reachable from every worker.

Workers should be able to access all other workers but we really should consider a reduction in the test space. Testing every node FROM every node is obviously quadratic, and that's no good.

I suggest a random sampling of probes, ensuring that every node is probed from, say, 3 different locations and targets 3 other nodes.

We should make sure we test both internal IP and hostname, so long as we have a hostname requirement...
