### ISSUE TITLE
1.5 upgrade process

### ISSUE THREAD

**Issue by DavidHuie** [apprenda/kismatic#164]
Hi, I've been using Kismatic to maintain a few Kubernetes 1.4 clusters. Now that you guys have updated the packages to use Kubernetes 1.5, how do I proceed in upgrading my cluster? Can I upgrade the packages? Or is this something that's handled by the Kismatic tool?

Also, I tried to join the Slack group for Kismatic, but it seems to be restricted to certain organizations. It would be great if I could get an invite. I'm david.huie@dollarshaveclub.com.

Thanks,
David

**Comment by josephjacks** [comment]
@DavidHuie I've added you to the Slack team.

Re: upgrades, we do not yet have a way for KET users to upgrade KET clusters. Please, stay tuned! For now, you would have to deploy a new cluster to "upgrade" to 1.5.

A proposal for upgrades should be landing relatively soon.

**Comment by dkoshkin** [comment]
To add what @josephjacks said...
I just ran a quick test using a cluster created with ket [1.0.3](https://github.com/apprenda/kismatic/releases/tag/v1.0.3), so this is in no way recommended for production environments, but here are the steps:
```
# do on each worker node
yum -y update kismatic-kubernetes-node 
systemctl restart kubelet 
systemctl restart kube-proxy 
```
```
# do on each master node
yum -y update kismatic-kubernetes-master 
systemctl restart kubelet 
systemctl restart kube-proxy 
systemctl restart kube-controller-manager
systemctl restart kube-scheduler
systemctl restart kube-apiserver
```
There were no changes in etcd so you should NOT need to update.

To verify the versions you can run `kubectl describe nodes` after all the upgrades.  
You can also run [kuberang](https://github.com/apprenda/kuberang) on the masters to verify the cluster didn't break
```
wget https://kismatic-installer.s3-accelerate.amazonaws.com/latest/kuberang && chmod +x kuberang && ./kuberang
```

## Important 
- Depending on your cluster size and configuration you might experience some downtime for the cluster and/or the apps deployed on it.

**Comment by DavidHuie** [comment]
@dkoshkin that worked! 

One thing to note: I accidentally upgraded the etcd packages, and that broke the etcd cluster when I restarted the nodes. Re-running the kismatic utility off of the master branch fixed the issue.
