### ISSUE TITLE
Validation error is misleading when python is not installed

### ISSUE THREAD

**Issue by eriklg** [apprenda/kismatic#173]
I am attempting to install KET on a 1 node environment (install and target node are the same). Started with the core Ubuntu server image which does not have all the standard libraries. 

I tried to run kismatic install validate and received the following error:
```
 ./kismatic install validate

Validating==========================================================================
Reading installation plan file "kismatic-cluster.yaml"                          [OK]
Validating installation plan file                                               [OK]
error running preflight: error running ansible playbook: error running playbook: fork/exec ansible/bin/ansible-playbook: no such file or directory
```
There are two asks here:
* The validation step should make sure that you have the underlying libraries installed
* The documentation should list any foundational requirements to run kismatic

**Comment by alexbrand** [comment]
@eriklg can you provide more details about the Ubuntu image you used? Vagrant?

**Comment by eriklg** [comment]
@alexbrand Yep, it was https://www.ubuntu.com/download/server Ubuntu Server 16.04.1 LTS . I installed the core server (gives you an option at the end) with no additional libraries/packages.

**Comment by alexbrand** [comment]
Thanks @eriklg . I assume this was on a bare VM and not through something like Vagrant?

**Comment by eriklg** [comment]
Correct. I created a new VM and installed using that ISO.

**Comment by ranajit-jana** [comment]
i got the code from github and built the go source using 'go install main.go'  it compiled all dependent go source in pkg folder. and later when i run 'main install apply' ,I am getting the same error. Do i have to do a build of python classes to get the bin folder in playbook folder ?

**Comment by ranajit-jana** [comment]
in case i want to change to code make file will not help me change it. I want to change my cni to pick up flannel my  approach  needs to be little different than doing a `make`

**Comment by ranajit-jana** [comment]
I pointed my `ansibleDir`  to the `out` folder generated from the  `make` command and things are working as program is able to find the needed folder

**Comment by ranajit-jana** [comment]
Thanks Dimitri for reply.

I will keep you updated on the changes.
