### ISSUE TITLE
docker-env command (docker-machine / docker repo integration)

### ISSUE THREAD

**Issue by McCodeman** [apprenda/kismatic#193]
This issue has been broken out from https://github.com/apprenda/kismatic/issues/191

# Problem Statement

The Kismatic CLI should implement a single command for configuring a local docker CLI to use a "minikube like" Kismatic installation as it's docker machine and docker repo.

with minikube, one can type

```
$ minikube docker-env
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.101:2376"
export DOCKER_CERT_PATH="/Users/marshallmccain/.minikube/certs"
export DOCKER_API_VERSION="1.23"
# Run this command to configure your shell:
# eval $(minikube docker-env)
```

which provides an easy way for the user to configure their docker client to use the minikube docker daemon and repo for building and deploying containers.  Having this would remove any need to have a docker repo available when deploying workloads into the repository.  Kismatic currently provides an easy configuration parameter in the plan file to install a local repo, however, additional configurations have to be performed to use it and docker images must be explicitly pushed to it.  

Having the above command would simplify the user's experience when connecting their local docker cli to the daemon and repo (see https://docs.docker.com/registry/insecure/ for the additional configuration that is currently required)

**Comment by dasmb** [comment]
I think this is a feature that should wait until we introduce storage. This will likely affect the way we stand up registries for users.

**Comment by codymccain** [comment]
Out of all the `minikube` like features, this is highest on my priority list as it removes the need for an external docker repo when demonstrating deployment of a user's container into a KET provisioned cluster.  Lowering the barrier to entry by making it easy for anyone to give KET a spin with their own workloads (and minimal external dependencies) is critical to proliferation and adoption.  Sure you can run containers on public repos, but it's much cooler to run ones you rolled yourself.

**Comment by jaycoon** [comment]
This is interesting, but would help a very small set of KET users at this time. Been around for a almost a year now, can we close this?

**Comment by alexbrand** [comment]
Agreed @jaycoon. We also removed the docker registry feature, so this doesn't make that much sense anymore.
