### ISSUE TITLE
Implement ssh command

### ISSUE THREAD

**Issue by codymccain** [apprenda/kismatic#194]
This issue has been broken out from https://github.com/apprenda/kismatic/issues/191

When a user sets up a Kismatic installation, they are required to provide a public/private ssh key pair  for accessing the target hosts.  If a "minikube like" cluster is automatically provisioned and launched, it would be useful to allow the user to SSH into the VM host by issuing:

```
$ kismatic ssh <?nodename>
```

Obviously I am only addressing a single host machine installation with this syntax.  Maybe we default to the first node listed in the plan file if a node name is not provided.

**Comment by dasmb** [comment]
I would use this every day.
