### ISSUE TITLE
Implement an ip command

### ISSUE THREAD

**Issue by codymccain** [apprenda/kismatic#196]
This issue has been broken out from https://github.com/apprenda/kismatic/issues/191

Minikube provides the  `minikube ip` command to access the IP address of a minikube instance.  Since small vm demo environments can be setup without DNS, this is useful in preparing lab instructions as the student can use this instead of substituting an IP address into a command string.  For example, if an http service has an ingress at `/foobar`, a student can type:

```
curl $(kismatic ip)/foobar
```

if using `BASH` and `curl` to access a REST endpoint for example.

**Comment by dasmb** [comment]
KET is not intended to be a minikube replacement; it's a toolkit for building enterprise deployments of Kubernetes. It's also not necessarily targeted at a single cluster -- with all command you must specify which cluster you want to target from the command line, currently by specifying a `kismatic-cluster.yaml` Plan file.

Were we to add an IP function as you describe, we'd need to require specification of a Plan and also which node was being targeted. You may be better off simply using grep.

**Comment by codymccain** [comment]
First off, this is certainly a lower priority request and a nice-to-have; however, I do think it enhances the user experience (more so for command line novices).

I agree it's not a minikube replacement, but providing a subset or parity of minikube functionality brings parity between training and production use.

In regards to specifying a plan file, I agree but would expect that the current behavior of using the `kismatic-cluster.yaml` in the current directory as the default is sufficient.  Also, I think it is sufficient to always default the node to the first master unless a node short-name is supplied as an argument.

**Comment by alexbrand** [comment]
Closed via #215
