### ISSUE TITLE
Introduce NFS shares to Plan file

### ISSUE THREAD

**Issue by dasmb** [apprenda/kismatic#201]
Plan file should have a new section for defining an NFS share.

This will be used during creation to set up a PersistentVolume in the created Kubernetes cluster, so that persistent workloads that are installed as part of creation can use something other than host storage.

This share should be validated -- we need to be sure it's mountable by worker nodes, that it has available storage and that it is writable -- and then added to the cluster as a PV using kubectl.

It's vitally important that the NFS share not be duplicated on the cluster. Offering the same store twice might make it available for a storage claim twice.

**Comment by alexbrand** [comment]
Closed via #229
