### ISSUE TITLE
Add storage cluster support to Plan

### ISSUE THREAD

**Issue by dasmb** [apprenda/kismatic#202]
For installations where clustered storage is desired but neither a cloud storage provider or NFS capable SAN is available, we will provide the options to install Gluster on some worker nodes. This will provide a mechanism for creating replicated NFS capable volumes using the disks attached to nodes as "bricks" of the store.

Gluster nodes should be specified in a `kismatic-cluster.yaml` Plan file. Like other nodes managed by kismatic, Gluster nodes must be manageable using passwordless SSH via the common kismatic user & private key. A new section will be introduced to the Plan file to allow for the specification of nodes in a storage cluster:

```
storage:
  expected_count: 2
  nodes:
  - host: ""
    ip: ""
    internalip: ""
  - host: ""
    ip: ""
    internalip: ""
```

Similar to ingress nodes, gluster nodes may be either schedulable or unschedulable. There is value to reserving storage resources for the storage use case. To make a node schedulable, include in both the storage and worker sections.

If package installation is permitted, we should install and start the service; if not, we should ensure that gluster and NFS server are installed & started.

RHEL: should already have the needed packages installed
CentOS: 
```sudo yum -y install centos-release-gluster
sudo yum update -y
sudo yum install http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
sudo yum install glusterfs-server -y
```
Ubuntu:
```
sudo apt-get install glusterfs-server
sudo apt install nfs-common
```

The service will need to be started on all storage nodes
```sudo systemctl enable glusterd.service
sudo systemctl start glusterd.service
```

After installation, the cluster will need to be formed. This is done by sshing into one node (we'll use the first one on the list) and calling
```
sudo gluster peer probe <hostname of second node>
sudo gluster peer probe <hostname of third node>
etc
```

If the cluster has at least two nodes, the first node should also be probed from at least one other node (we'll use the second one on the list) to ensure that all IP addresses and hostnames for the first node are known by the cluster.

Lastly: all the nodes in the gluster cluster should be added to a Kubernetes Endpoint, thus providing HA within the cluster.

**Comment by alexbrand** [comment]
Status:
- [x] Storage role supported in plan file
- [ ] Gluster cluster is created when nodes are defined in the storage role
  - [x] Ubuntu
  - [x] CentOS
  - [ ] RHEL
- [x] Integration test for GlusterFS on CentOS and Ubuntu
- [x] Inspector checks for required packages
- [ ] Inspector checks for required ports
- [ ] Creation of Kubernetes endpoint

**Comment by alexbrand** [comment]
Completed in #222
