### ISSUE TITLE
Kismatic function to create new Storage volumes

### ISSUE THREAD

**Issue by dasmb** [apprenda/kismatic#203]
The new command
`kismatic storage new-volume <flags> <size in gigabytes> [volume name]` 

can be used to add storage volumes to the Kubernetes cluster. A Gluster store is required for this function and should be referenced by flags to the command, e.g.

`-f kismatic-cluster.yaml`

Other flags that should be introduced:

```
-r | --replica-count (default 2) The number of times each file will be written.

-d | --distribution-count (default 1) This is the degree to which data will be distributed
 across the cluster. By default, it won't be -- each replica will receive 100% of the data. 
Distribution makes listing or backing up the cluster more complicated by spreading data 
around the cluster but makes reads and writes more performant.

-a | --allow-addresses This is a list, comma delimited, of address wildcards permitted
access to the volume in addition to Kubernetes nodes.
```

Example:
`kismatic storage new-volume -r 2 -d 2 -a 10.10.*.* 10 kismatic` 

will create a distributed, replicated volume named kismatic with a 10 GB quota. We will grant access to any IP address starting with `10.10`. In pursuit of this, 4 bricks will be created -- 2 distributed bricks and 2 replicas of each.

The command will
1. List free space & known volumes on all gluster nodes
2. If there is insufficient space on enough nodes to create the described volume, the command will raise an error.
3. If the new volume name would make a bad directory name (e.g. has spaces, colons, slashes in it), the command will raise an error.
    1. If no volume name is introduced, use `kismatic-<some brief randomness>`
4. Otherwise, will make a list of the (num_replicas) most empty storage nodes.
5. For each node:
    1. Create a new "brick" directory off `/data` using the new volume name.
    2. Set its permissions to 777
6. Create a new volume, referencing each of the bricks created at 5 and named approriately
7. Start the volume
8. Enable NFS, quotas & quota-deem-status [allows df to accurately report quotas]
9. Apply a white list allowing the pod network and the install machine's IP address to access the drive (but nothing else)
10. Set the quota to the desire size
11. Add a new PV for the created volume to kubernetes

**Comment by dkoshkin** [comment]
Do we need another flag to allow for specifying the base directory (default to `/data`)?

This is useful if there are multiple drives mounted on the storage node under different directories.

**Comment by dkoshkin** [comment]
Im not very clear on where the responsibility lies for steps above with Ansible and Go code, let's try to break this down.

What complicates this is the interface to Gluster is via the CLI (has native support for XML? but no JSON)

1. Executed from Golang via ssh
  a. Linux `df` util, is there some gluster command?
  b. `gluster volume status all` 
2. Golang
3. Golang
4. Golang use the info from 1?
5. Ansible, does Go pass in only the storage nodes required here?
6. Ansible, does Go pass in only the storage nodes required here?
7. Ansible
8. Ansible
9. Ansible, Go passes in the install machine and storage node IPs as formatted string
10. Ansible, Go passes in the size
11. Ansible, requires the `master[0]` node to run`kubectl`

Steps 5-11 can all be performed with a single call to Ansible

**Comment by alexbrand** [comment]
I am somewhat worried about doing half the work in one place, and doing the other half in another. What's the main driver for moving some of these steps into the CLI?

**Comment by alexbrand** [comment]
Complete via #231
