### ISSUE TITLE
Test addition of a stateful feature to Kismatic

### ISSUE THREAD

**Issue by dasmb** [apprenda/kismatic#205]
As part of this release, we likely won't be introducing a feature that will make use of the new Gluster store. But we will want to test that addition of a stateful feature to the platform would work as expected -- that a specified NFS volume would be tested and used, that specified Gluster cluster would have a new volume created of the correct storage class, and that any feature that was introduced would result in a volume being claimed and named "kismatic."

Kismatic doesn't really have a model of a "feature" at the moment, so picking up this issue should include a design for detecting the "features" of a platform. A list of "existing features" has been produced on the Apprenda wiki (comment here if you would like and I will make copy here).

The test should include a Reader service and a Writer service with at least 2 pods of each.

**Comment by alexbrand** [comment]
- [x] [Whiteboard/brainstorm](https://realtimeboard.com/app/board/o9J_k0xrJU8=/) what the installation of a stateful feature looks like

**Comment by alexbrand** [comment]
Complete via #234
