### ISSUE TITLE
Does Kismatic support adding an Ingress node once the cluster is built?

### ISSUE THREAD

**Issue by raghu67** [apprenda/kismatic#207]
If so, How do I do it? Can I just run kismatic install apply again after modifying the plan file? Perhaps skipping validation checks?

**Comment by dkoshkin** [comment]
Yes you can do that, however this will also update all the packages and the other components in the cluster. 
You will end up with 2 kube-dns services and a duplicate dashboard deployment so you will have to clean that up manually.
