### ISSUE TITLE
Error when running smoke test with the step command

### ISSUE THREAD

**Issue by alexrjs** [apprenda/kismatic#219]
## Initial install run
During the initial install of the cluster, the smoketest failed, with;
```
Configured kubectl exists                                                       [OK]
Nginx service does not already exist                                            [OK]
BusyBox service does not already exist                                          [OK]
Nginx service does not already exist                                            [OK]
Issued BusyBox start request                                                    [OK]
Issued Nginx start request                                                      [OK]
Both deployments completed successfully within timeout                          [OK]
Issued expose Nginx service request                                             [OK]
Grab nginx pod ip addresses                                                     [OK]
Grab nginx service ip address                                                   [OK]
Grab BusyBox pod name                                                           [OK]
Accessed Nginx service at 172.17.39.196 from BusyBox                            [OK]
Accessed Nginx service via DNS kuberang-nginx-1483461638247018172 from BusyBox  [ERROR]
Accessed Nginx pod at 172.16.144.192 from BusyBox                               [OK]
Accessed Nginx pod at 172.16.86.129 from BusyBox                                [OK]
Accessed Nginx pod at 172.16.105.65 from BusyBox                                [ERROR]
Accessed Google.com from BusyBox                                                [ERROR IGNORED]
Accessed Nginx service via DNS kuberang-nginx-1483461638247018172 from this node[ERROR IGNORED]
Accessed Nginx pod at 172.16.144.192 from this node                             [OK]
Accessed Nginx pod at 172.16.86.129 from this node                              [OK]
Accessed Nginx pod at 172.16.105.65 from this node                              [OK]
Accessed Google.com from this node                                              [OK]
Powered down Nginx service                                                      [OK]
Powered down Busybox deployment                                                 [OK]
Powered down Nginx deployment                                                   [OK]
---- STDERR ----
Error running command: One or more required steps failed
---------------
error during smoke test: error running smoketest: error running playbook: error running ansible: exit status 2
```
## Standalone smoketest run
Then I tried to run the smoketest standalone, with:
`./kismatic install step smoketest.yaml`

which ended with this error:
```
Validating==========================================================================
Reading installation plan file "kismatic-cluster.yaml"                          [OK]
Validating installation plan file                                               [OK]

Running Task========================================================================
1/2....  Configure Cluster Prerequisites                                        [OK]
2/2....  Smoke test Master Nodes
- Running task: copy Kuberang to node
  us1604s01 the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'kuberang_path' is undefined

The error appears to have been in '/home/homeboy/kismatic/ansible/playbooks/roles/smoketest/tasks/main.yaml': line 2, column 5, but may be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
  - name: copy Kuberang to node
    ^ here
                                                                                [ERROR]
error running task: error running playbook: error running ansible: exit status 2
```

**Comment by alexbrand** [comment]
Thanks for reporting this bug, @alexrjs 

If you wish, you can run `kuberang` manually by ssh'ing into a Master node, and running `kuberang`.

**Comment by alexrjs** [comment]
Hi,

thanks for the reply. Kismatic, is a great idea and tool. I was struggling getting kubernetes on coreos to work… man, so many manual steps with coreos… Then I saw the Kismatic video from kubcon 2016, and switched to kismatic… Thanks for open sourcing it… :-) d  

Ok, dit it manually… Calling kuberang manually on the master, without ansible seems to work… Still a DNS problem, though… :-(

Guess running the cluster on my own ESXi host with 5 vm servers (2 small (master, etcd), 3 medium (worker)) isn’t gonna work without digging deeper into the dns problem… :-(

Anyhow, here the output of kuberang, not that it is related to my reported ansible problem, but you might read something out of it: 

——8<—— 
ubuntu@us1604s01:~$ sudo kuberang
Configured kubectl exists                                                       [OK]
Nginx service does not already exist                                            [OK]
BusyBox service does not already exist                                          [OK]
Nginx service does not already exist                                            [OK]
Issued BusyBox start request                                                    [OK]
Issued Nginx start request                                                      [OK]
Both deployments completed successfully within timeout                          [OK]
Issued expose Nginx service request                                             [OK]
Grab nginx pod ip addresses                                                     [OK]
Grab nginx service ip address                                                   [OK]
Grab BusyBox pod name                                                           [OK]
Accessed Nginx service at 172.17.211.220 from BusyBox                           [OK]
Accessed Nginx service via DNS kuberang-nginx-1483472698946430311 from BusyBox  [ERROR]
Accessed Nginx pod at 172.16.105.66 from BusyBox                                [ERROR]
Accessed Nginx pod at 172.16.144.194 from BusyBox                               [OK]
Accessed Nginx pod at 172.16.86.130 from BusyBox                                [OK]
Accessed Google.com from BusyBox                                                [ERROR IGNORED]
Accessed Nginx service via DNS kuberang-nginx-1483472698946430311 from this node[ERROR IGNORED]
Accessed Nginx pod at 172.16.105.66 from this node                              [OK]
Accessed Nginx pod at 172.16.144.194 from this node                             [OK]
Accessed Nginx pod at 172.16.86.130 from this node                              [OK]
Accessed Google.com from this node                                              [OK]
Powered down Nginx service                                                      [OK]
Powered down Busybox deployment                                                 [OK]
Powered down Nginx deployment                                                   [OK]
Error running command: One or more required steps failed
——8<—— 

Cheers and a late Happy new year from Germany...
   Alex

**Comment by alexbrand** [comment]
Hey @alexrjs 

It seems like one of the nodes might be having issues with the networking layer. This document might be helpful when it comes to diagnosing the issue: https://github.com/apprenda/kismatic/blob/master/docs/TROUBLESHOOTING-NETWORK.md
