### ISSUE TITLE
Support DNS names instead of IP addresses in kismatic-cluster.yaml

### ISSUE THREAD

**Issue by notuscloud** [apprenda/kismatic#225]
Hi guys, 

Is it possible to only use DNS names for my hosts in the `kismatic-cluster.yaml` file?
My servers are automatically provisioned by terraform over a DHCP network. I only rely on DNS names to reach those machines.

When I try to valide my kismatic plan, I fall upon those errors:
```
Validating==========================================================================
Reading installation plan file "kismatic-cluster.yaml"                          [OK]
Validating installation plan file                                               [ERROR]
- SSH Key field must be an absolute path
- Etcd nodes: Node #1: Invalid IP provided
- Master nodes: Node #1: Invalid IP provided
- Master nodes: Load balanced FQDN is required
- Master nodes: Load balanced shortname is required
- Worker nodes: Node #1: Invalid IP provided
- Worker nodes: Node #2: Invalid IP provided
error validating plan: validation error prevents installation from proceeding
```

Which is quite normal cause I didn't provided any IP addresses...

Regards,
Thomas

**Comment by dasmb** [comment]
I have a few quick questions for you.
1) Are your IP addresses stable after provisioning?
2) Is there more than one address attached to each host?
3) Does the IP address map to the same hostname everywhere? (e.g. can you `ping machine01` from machine01 and get the same IP you get when you ping it from your installation machine)

The reason Kismatic separates hostname, IP and internalIP into three different sections is that different tools need to access machines in different ways -- e.g. some of the Calico tools have _(or rather had, I think this has been relaxed)_ a requirement that the communicate over hostname, and some other tools in the K8s stack had requirements that they use IP addresses, with the internal IP address being a pretty substantial optimization for routing internal cluster traffic.

If your IP addresses aren't stable, when you obtain a new address for a node that node will lose identity on the cluster. And if your hostnames aren't the same both inside and out, some components just flat out won't work correctly.

If your hostnames always map to the same address, inside and out, and only that address matters for purposes of routing, and it's stable, we could introduce functionality to automatically fill in the IP address from the hostname that would meet your needs. It may also encourage people with more complicated network and naming rules to set their clusters up in a way that is likely to be unstable.

**Comment by notuscloud** [comment]
Hi, 

1 - My IPs are stable, we have 24h DHCP lease and VMs keep their IP upon renewal. the only case an IP is changed would a more than 24h downtime for a VM.

2 - Each host comes with only a single nic, with a single IP

3 - The IP map the host name everywhere.
 
I can see your need in delivering a robust and resilient piece of software. In my case, I think it fastidious to edit this `kismatic-cluster.yaml` as I plan to setup multiples 10 nodes K8S cluster.
But describing you my network setting, I realize that my IP distribution is stable and I could rely on it a tad more. 
As I consider my VMs as disposable element, I could easy drop a VM who got an IP change then build it again.

Thx

**Comment by dkoshkin** [comment]
This issue has been opened for a while, unfortunately IPs are still required by numerous k8s components (although that might be hidden by doing IP detection), when IPs change there are many issues that will pop up, ie. certificates, etcd out of sync etc.
