### ISSUE TITLE
Not installing on coreos 1235.6.0

### ISSUE THREAD

**Issue by ranzbak** [apprenda/kismatic#230]
When I try to install a cluster on 4 Coreos nodes I get :

- Running task: Install python 2.7
  coreos-01                                                                     [ERROR]
---- STDOUT ----
which: no python in (/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/opt/bin)
/home/core/.ansible/tmp/ansible-tmp-1484128659.62-36746745770822/python27.sh: line 2: apt-get: command not found
ln: failed to create symbolic link '/usr/bin/python': Read-only file system

---- STDERR ----
OpenSSH_6.7p1 Debian-5+deb8u3, OpenSSL 1.0.1t  3 May 2016
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: /etc/ssh/ssh_config line 57: Applying options for *
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 27278
debug3: mux_client_request_session: session request sent
debug1: mux_client_request_session: master session id: 2
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 1
Shared connection to 188.166.75.126 closed.

---------------
error running preflight: error running playbook: error running ansible: exit status 2

Why does it try to use apt-get on Coreos?

Kind regards, Paul

**Comment by alexbrand** [comment]
We don't support CoreOS at the moment. Take a look at https://github.com/apprenda/kismatic/blob/master/docs/PLAN.md#hardware--operating-system for a list of operating systems we currently support.
