### ISSUE TITLE
only one pod can be access???

### ISSUE THREAD

**Issue by pennpeng** [apprenda/kismatic#247]
I create an nginx deployment with three replicas.and  i create a svc.
like this:
```
[root@master ~]# kubectl get  pod -o wide
NAME                       READY     STATUS    RESTARTS   AGE       IP               NODE
my-nginx-379829228-0d203   1/1       Running   2          16d       172.16.171.196   slave01
my-nginx-379829228-v47h8   1/1       Running   2          16d       172.16.14.6      slave02
my-nginx-379829228-xs2l5   1/1       Running   2          16d       172.16.171.195   slave01
```
when i access the nginx serivce,only one pod can be reach .
```
[root@master ~]# kubectl logs -f my-nginx-379829228-0d203


^C
[root@master ~]# kubectl logs -f my-nginx-379829228-xs2l5






^C
[root@master ~]# kubectl logs -f my-nginx-379829228-v47h8
172.16.1.64 - - [20/Jan/2017:05:58:34 +0000] "GET / HTTP/1.1" 200 612 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36" "-"
2017/01/20 05:58:35 [error] 5#5: *1 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.16.1.64, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.83.190:30062", referrer: "http://192.168.83.190:30062/"
172.16.1.64 - - [20/Jan/2017:05:58:35 +0000] "GET /favicon.ico HTTP/1.1" 404 571 "http://192.168.83.190:30062/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36" "-"
```

**Comment by alexbrand** [comment]
@pennpeng Can you provide the spec of your service? Did you enable session affinity? Are you seeing dropped requests, or are all requests succeeding?

**Comment by dasmb** [comment]
I've seen this many times with services in KET, hand-crafted and GKE clusters. I believe this to be a result of Kubernetes service load balancing just not working the way I -- and you -- expect, especially with a small volume of requests.

First, it's not strictly round robin -- e.g. if you request 3 things, you aren't guaranteed to retrieve 1 thing from each server.

There's also the issue of connection stickiness. Modern HTTP systems keep connections around for quite some time and it's the connection that's load balanced through a service. If you hit refresh a bunch of times in your browser, you may never leave the same connection, which with a K8s service (and indeed any layer 4 balancer) would mean all your traffic goes to the same pod.

Try throwing some time-seperated volume at at and see if you get different results. Here's a cheap way to do that:

`watch -n 5 curl "http://yourservice/"

This will call your service once every n seconds. Let it run for a minute. I expect you will see roughly equivalent load the longer you let it run.
