### ISSUE TITLE
kubelet worker node failed to start  (kismatic 1.2)

### ISSUE THREAD

**Issue by yiqz** [apprenda/kismatic#251]
/var/log/messages:
error: failed to run Kubelet: invalid kubeconfig: read /etc/kubernetes/ca.pem: is a directory

$ sudo systemctl status kubelet -l
  kubelet.service: main process exited, code=exited, status=1/FAILURE

OS  CentOS 7

**Comment by alexbrand** [comment]
@yiqz This is odd. Can you provide a listing of /etc/kubernetes? `ls -al /etc/kubernetes` should do it. Thanks!

**Comment by yiqz** [comment]
[kismaticuser@worker-1 ~]$ ls -al /etc/kubernetes
总用量 28
drwxr-xr-x   5 root root 4096 12月 25 23:04 .
drwxr-xr-x. 82 root root 4096 1月  30 22:34 ..
drwxr-xr-x   2 root root 4096 12月 25 23:04 ca.pem
drwxr-xr-x   2 root root 4096 12月 25 23:04 kubenode-key.pem
drwxr-xr-x   2 root root 4096 12月 25 23:04 kubenode.pem
-rw-rw----   1 root root 1679 12月 25 23:04 service-account-key.pem
-rw-rw----   1 root root 1403 12月 25 23:04 service-account.pem

**Comment by dkoshkin** [comment]
HI @yiqz, any update on this? We have also recently released a new [version](https://github.com/apprenda/kismatic/releases/tag/v1.3.0).

**Comment by dkoshkin** [comment]
Closing, feel free to reopen if you are still facing problems.
