### ISSUE TITLE
Unfiltered Offline upgrade

### ISSUE THREAD

**Issue by dasmb** [apprenda/kismatic#255]
As a first step to all other forms of upgrade, we will add a command to kismatic that will allow for a cluster to be upgraded, one node at a time, with no draining or analysis of safety.

`kismatic upgrade offline [-f plan=kismatic-cluster.yaml]`

This process should start by detecting the current Kismatic version (ssh, grab /etc/kismatic-version). For each node, if that node is below the current version of the installer, then the node qualifies for upgrade. Nodes that do not qualify should be logged as skipped with their current version displayed. If no nodes needing upgrading are detected, the process should exit.

For the nodes that qualify to be upgraded, we will run a special form of validation against them to be sure they are ready. Readiness is a function primarily of disk space on the root volume and an ability to access the upgrade packages via existing repositories. If any qualifying nodes are unready, the process should exit, listing the nodes which are not ready.

Upgrades should occur, one node at a time, in the following order: 

1. All worker nodes (regardless of specialization)
2. All master nodes
3. All etcd nodes
4. “On-cluster” Docker Registry
5. Other on-cluster systems (DNS, dashboard, etc)

No draining or cordoning will be done. This may result in data loss or a reduction in availability. That's what makes this the "offline" upgrade.

**Comment by alexbrand** [comment]
In terms of the upgrade order, I believe we want to upgrade the K8s control plane components before the worker components. K8s guarantees new API server -> old Kubelet compatibility, but not the other way around. 

I am also unsure about whether we should run ansible once against the entire inventory, or run ansible multiple times, one node at a time? If running against the whole inventory, we specify `serial: 1`, but I am not sure if that's enough.

**Comment by alexbrand** [comment]
Initial implementation of this was completed in #275
