### ISSUE TITLE
Online upgrade

### ISSUE THREAD

**Issue by dasmb** [apprenda/kismatic#256]
An online upgrade is just an offline upgrade with two twists:

1. We will exit if any of the nodes is detected as being unsafe to upgrade online. This should be accompanied by a list of reasons and potential mediations for each node.
2. We will attempt to drain each worker node prior to upgrade, and uncordon each worker after it is upgraded.

`kismatic upgrade offline [-f plan=kismatic-cluster.yaml]`

**Node Safety**

For each node, we will check each of its roles to see if it has any of the offline preventing issues below. If so, we will generate a report of all such violations, output it and exit.

_Etcd_

- If there are less than 3 etcd nodes, upgrading one will make the cluster unavailable.

_Master_

- If there is a single master, upgrading it will make cluster features unavailable.
- If a master is also acting as the load balanced endpoint, upgrading it will make cluster features unavailable.

_Ingress_

- As we do not control the load balancing of ingress, if a node is an Ingress Node, upgrading it will make workloads unavailable.

_Gluster_

- As many different permutations of volume capabilities can be included on a Gluster node, if a node is a Gluster Node, upgrading it will potentially make workloads unavailable.

_Worker_

- If there is a single worker, upgrading it will make cluster features unavailable.
- If a node is host to a pod using a HostPath or emptyDir volume, upgrading it would potentially cause data loss.
- If a node is the only host to a DaemonSet, upgrading it could potentially decrease availability
- If a node is running a pod that has no peers, upgrading it could cause a loss of data or availability
- If a node is running a pod that is not managed by an RC, RS, Job or DS, upgrading it could cause a loss of data or availability.

For now, we're ignoring alpha features like [`taints, affinities and tolerations`](https://groups.google.com/forum/%23!msg/kubernetes-dev/-fwfHQtm9GE/H1TU4yqiBAAJ&sa=D&ust=1484942815608000&usg=AFQjCNHynESpssTvErCFdqV94oT2tdYiOA) in this detection algorithm, but these certainly should be taken into account once they become mainstream.

**Comment by alexbrand** [comment]
Closed via #305
