### ISSUE TITLE
Introduce partial flag

### ISSUE THREAD

**Issue by dasmb** [apprenda/kismatic#257]
The partial flag would allow for either upgrade -- online or offline -- to apply the upgrade to the nodes that did not report a problem (unreadiness for offline upgrades, unreadiness/unsafety for online upgrades).

After applying upgrades, a report of which nodes that couldn't be upgraded will be delivered prior to exiting.

**Comment by dkoshkin** [comment]
@alexbrand What does `unreadiness` for an `offline` upgrade mean?

**Comment by dkoshkin** [comment]
Closed with #337
