### ISSUE TITLE
Preflight checks should check for duplicate hostnames and ip addresses

### ISSUE THREAD

**Issue by swade1987** [apprenda/kismatic#264]
The execution of KET has corrupted a few times when I have had duplicate hostnames and/or ip addresses. The tool should check for these before running any of the ansible playbooks.

**Comment by dasmb** [comment]
Duplicate hostnames /ips where?

Duplication across node roles is perfectly legal and how you might create useful hybrid deployments (such a "mini" style with the same node used for all roles, or a "mesos" style that combines etcd and master).

Duplication within a node role may be something we can detect and warn about.
