### ISSUE TITLE
Upgrades: Upgrade Etcd

### ISSUE THREAD

**Issue by dkoshkin** [apprenda/kismatic#326]
To keep the cluster at a consistent well defined state, etcd will also be upgraded when running `kismatic upgrade` for both `online` and `offline` commands.

- [x] Publish new "transitional" etcd package, this is required to upgrade old networking etcd from `v2.3.x` to `v3.0.x` then to the final `v3.1.x` versions
  - This means the whole cluster must be upgraded to `3.0` first then again to `3.1`
- [x] Fix bug with etcd service not restarting correctly
- [x] Will need to place an indicator on node that it has been upgraded to the transition etcd, without it rerunning the upgrade on a failure will fail due to the package conflict
  - No need to do this as we can rely on the `kismatic-version` file
- [x]  Add new upgrade code for etcd as described in [upgrade to 3.0](https://coreos.com/etcd/docs/latest/upgrades/upgrade_3_0.html) and [upgrade to 3.1](https://coreos.com/etcd/docs/latest/upgrades/upgrade_3_1.html)
- [x] Verify an etcd node has been upgraded and is ready
  - `cluster-health` seems to do this fine
- [x] Move cert copying to the certs play so it doesnt rerun on upgrades
- [x] Test the overall state of the etcd clusters, maybe another step after node-upgrade?
- [x] Figure out what happens for an `online` upgrade when an etcd node has multiple roles and those are `ingress`, `storage` - maybe these can be upgraded?

**Comment by alexbrand** [comment]
> Will need to place an indicator on node that it has been upgraded to the transition etcd, without it rerunning the upgrade on a failure will fail due to the package conflict
Can we detect etcd version using etcdctl instead?

**Comment by alexbrand** [comment]
Closed via #331
