### ISSUE TITLE
Explore using secrets instead of hostpath for certs

### ISSUE THREAD

**Issue by dkoshkin** [apprenda/kismatic#367]
Currently we rely on `hostPath` to mount our cluster certificates for the controle-plane, DNS and calico.

Moving to secrets and configmap would also help with the `upgrade online` story in the future.

**Comment by dkoshkin** [comment]
This doesn't really make sense.

Our certs are different on all nodes. We also made the decision to NOT use service accounts when connecting to the API server with `kube-DNS` and the same reasoning applies to calico

**Comment by alexbrand** [comment]
Closing due to @dkoshkin's comments and the fact that most of the solutions out there are using volumes for mounting certs when doing self-hosted/static pods.
