### ISSUE TITLE
Liveness probe for containers in Kube-DNS pod fails intermittently

### ISSUE THREAD

**Issue by alexbrand** [apprenda/kismatic#408]
I noticed an unexpected number of restarts in the DNS pod in a cluster that was at rest:

```
kube-dns-24248056-3qclh                 1/3       CrashLoopBackOff   26         44m
```

Once I looked into it, I noticed that the dnsmasq liveness probe fails intermittently:

```
  22m	4m	24	{kubelet node001}	spec.containers{dnsmasq}	Warning	Unhealthy	Liveness probe failed: HTTP probe failed with statuscode: 503
```

This is what is causing the issue we are seeing with kuberang, which is intermittent failures during the DNS check.

**What changed?**
We recently changed the way we deploy kube-dns, and with that we changed the liveness probe. This explains why we started seeing this now. These are the logs from the healthz container which is deployed inside the kube-dns pod:

```
2017/03/09 21:53:28 Worker running nslookup kubernetes.default.svc.$DNS_DOMAIN 127.0.0.1:10053 >/dev/null to serve /healthz-kubedns
2017/03/09 21:53:30 Worker running nslookup kubernetes.default.svc.$DNS_DOMAIN 127.0.0.1:10053 >/dev/null to serve /healthz-kubedns
2017/03/09 21:53:30 Worker running nslookup kubernetes.default.svc.$DNS_DOMAIN 127.0.0.1 >/dev/null to serve /healthz-dnsmasq
2017/03/09 21:53:30 Client ip 10.0.3.223:60658 requesting /healthz-dnsmasq probe servicing cmd nslookup kubernetes.default.svc.$DNS_DOMAIN 127.0.0.1 >/dev/null
2017/03/09 21:53:30 Client ip 10.0.3.223:60660 requesting /healthz-kubedns probe servicing cmd nslookup kubernetes.default.svc.$DNS_DOMAIN 127.0.0.1:10053 >/dev/null
2017/03/09 21:53:30 Healthz probe on /healthz-dnsmasq error: Result of last exec: nslookup: can't resolve 'kubernetes.default.svc.'
, at 2017-03-09 21:53:30.62416731 +0000 UTC, error exit status 1
2017/03/09 21:53:30 Healthz probe on /healthz-kubedns error: Result of last exec: nslookup: can't resolve 'kubernetes.default.svc.'
, at 2017-03-09 21:53:30.625418789 +0000 UTC, error exit status 1
2017/03/09 21:53:32 Worker running nslookup kubernetes.default.svc.$DNS_DOMAIN 127.0.0.1 >/dev/null to serve /healthz-dnsmasq
2017/03/09 21:53:32 Worker running nslookup kubernetes.default.svc.$DNS_DOMAIN 127.0.0.1:10053 >/dev/null to serve /healthz-kubedns
2017/03/09 21:53:34 Worker running nslookup kubernetes.default.svc.$DNS_DOMAIN 127.0.0.1 >/dev/null to serve /healthz-dnsmasq
```

It looks like both the healthz probes fail to look up `kubernetes.default.svc.`.

Two thoughts, although neither explain why the failure is intermittent:
1. It seems like the DNS_DOMAIN environment variable is not being set. We might be mis-configuring something, somewhere.
2. We could go back to the old liveness probe, which was `nslookup kubernetes.default.svc.cluster.local`. 

Looks like we glossed over this in #393, as this is something that is happening after install.

**Comment by alexbrand** [comment]
I looked into this a bit more and I understand why we were seeing the intermittent kuberang failure. I'll try to explain below.

We discovered that we were misconfiguring the liveness check for KubeDNS. Given that the readiness and liveness checks are using different methods to determine health (I don't know if this is expected, seems odd to me), the KubeDNS pod is placed into service and it works just fine.

Then, the liveness checks come around and - given that they are misconfigured - start failing. This results in the KubeDNS pod being restarted. Due to the way the liveness probe is configured, KubeDNS would be restarted approximately 1m50s after the pod started. This is because the probe has an initial delay of 60s, a probe period of 10s (this is the default when period is not specified) and  a threshold of 5 failures.

Depending on how quickly we ran kuberang after installing the cluster, there was a chance that KubeDNS was down, which result in the intermittent failure.

**Comment by dkoshkin** [comment]
It was discovered that the health check relies on doing an `nslookup` on the kubernetes service. If the hosts DNS is configured to always respond to a DNS request even if it's a bogus URL(looking at you FIOS) then the health probes will never fail and kube-dns will remain broken.
