### ISSUE TITLE
Kube does not support updating labels on DaemonSets without also changing the spec

### ISSUE THREAD

**Issue by dkoshkin** [apprenda/kismatic#420]
Related to https://github.com/kubernetes/kubernetes/issues/26202

When rerunning `kubectl apply` with the same DS spec but different labels I get:

```
The DaemonSet "default-http-backend" is invalid: spec.template.metadata.labels: Invalid value: {"app":"default-http-backend","kismaticVersion":"1.3.0-alpha.0-51-ged12a81-dirty"}: `selector` does not match template `labels`
```

The labels will change when new versions of KET are released. 

I believe this is a DS issue and not on other resources.

**Comment by dkoshkin** [comment]
Need to revisit `label` vs `annotation`

**Comment by alexbrand** [comment]
What is this in relation to? Is this an issue for upgrades as a whole, or a specific part (e.g. ingress)?

**Comment by dkoshkin** [comment]
This will happen anytime we upgrade a DS labels without upgrading anything in the spec. Ingress, Calico and Storage affected by this. 

The good thing is the version labels were added in the `1.3.alpha` and not in any of the prior releases so we do not need to fix any bugs in the upgrade relating to this.
