### ISSUE TITLE
kismatic-inspector.service with Fedora

### ISSUE THREAD

**Issue by VinayKumarbrsoft** [apprenda/kismatic#444]
Hi Guys

Trying to run my first cluster with Kismatic and using fedora as my Host OS for all nodes.  Successfully generated the cluster plan .  Validating the plan giving me following error: 
```

`---- STDERR ----
Error: error running inspector against remote node: error posting request to server: Post http://10.22.1.3:8888/execute: dial tcp 10.22.1.3:8888: getsockopt: connection refused
---------------
  master-1:                                                                     [ERROR]`

`---- STDERR ----
Error: error running inspector against remote node: error posting request to server: Post http://10.22.1.2:8888/execute: dial tcp 10.22.1.2:8888: getsockopt: connection refused
---------------
  etcd-1:                                                                       [ERROR]`
`---- STDERR ----
Error: error running inspector against remote node: error posting request to server: Post http://10.22.1.4:8888/execute: dial tcp 10.22.1.4:8888: getsockopt: connection refused`
```

Debugging the error message telling me to start the service called kismatic-inspector.service but the distribution does not seem to support Fedora.  

Can I ask if Fedora OS is not supported at all or are there any ways I can get around the problem?

**Comment by alexbrand** [comment]
Hi @VinayKumarbrsoft - we currently do not support Fedora. Supported OSs are listed here:
https://github.com/apprenda/kismatic/blob/master/docs/PLAN.md#hardware--operating-system

**Comment by VinayKumarbrsoft** [comment]
Thanks Alex!!
