### ISSUE TITLE
Change load_balanced_fqdn

### ISSUE THREAD

**Issue by WillPlatnick** [apprenda/kismatic#457]
After a cluster is setup, is there a way to change the load_balanced_fqdn value? Initially I pointed it directly to a master, but now I'd like to setup a load balancer in front of the masters.

**Comment by alexbrand** [comment]
We currently don't have a supported way of doing this. You may be able to call `apply` against the existing cluster using the `--skip-preflight` and `--restart-services` flags. Changing the load balanced FQDN will need regeneration of certificates, which is why forcing a restart of services is required.

**Comment by WillPlatnick** [comment]
I have a feeling this is causing some networking issues on my side. I wanted to check and see if this has come up since I put the ticket in, and how dangerous it could be to do this on an existing production cluster? cc @alexbrand @dkoshkin

**Comment by WillPlatnick** [comment]
@alexbrand Can you show me where the regeneration of certificates would need to be for this changing this variable? Looking for what certificates would need to be regenerated.

**Comment by alexbrand** [comment]
Can you elaborate on what you are seeing @WillPlatnick (symptoms, logs, etc)? Maybe we can help troubleshoot.

I don't think we have seen cases where users change the load balancer's FQDN after the cluster is deployed.

**Comment by WillPlatnick** [comment]
@alexbrand When we first set the cluster up, we didn't have a load balancer ready in front of the masters, so I just set it to be the fqdn of our first master server. 

As far as the API is concerned, I have tried to work around this by setting up nginx in tcp mode and route requests to either master01 and master02. I then changed the dns for the load balanced fqdn (same as master01) to point to nginx. However, something about this doesn't seem to work well: when I turned off master01 by shutting down the ethernet interface, the kubelet on a worker also ended up going down. Later on, with master01 back up, I turned off master02's ethernet, and all the kubelets on all worker nodes also went NotReady. Lots of issues talking to the api server in the logs, even though the load balancer was doing its thing when asked. I have a feeling it's something related to my load balanced fqdn and master01 being the same, and wanted to setup a new fqdn so we can get out of the funkiness of this situation and hopefully fix API HA. 

However, the bigger issue is that sometimes, when a master is down, network traffic is stopping to some degree within the pods and I can't figure out where and why it's happening. It seems like DNS traffic is definitely affected, but it may be all traffic going out of pods, I'm not sure.  Right now the only thing I can find in the logs of calico-node, kube-proxy, kubelet, etc... is that during these periods of time, there's tons of failed API requests.

**Comment by WillPlatnick** [comment]
@alexbrand @dkoshkin If I move to kismatic 1.6.1 and don't move over the generated dir and change the load_balanced_fqdn, will all the certs be regenerated as part of the upgrade?

**Comment by WillPlatnick** [comment]
Alternatively, can I create additional master nodes and then somehow delete the master node that was named master01?

**Comment by dkoshkin** [comment]
There is no simple way to do this, if for some reason a new `fqdn` is required I would recommend reinstalling the cluster.
