### ISSUE TITLE
Upgrade fails at kismatic-inspector

### ISSUE THREAD

**Issue by TimWoolford** [apprenda/kismatic#466]
Attempting to upgrade a cluster created with v.1.2.2 using v1.3.0:

`kismatic upgrade offline --dry-run`

Every master, etcd, worker node fails with :

`Error: error running inspector against remote node: server responded with non-successful status: "400 Bad Request"`

running:

`<path to>/kismatic-inspector client <etcd-node-ip>:8888 --upgrade --node-roles etcd`

produces the same error.

From the logs on the node:

`kismatic-inspector: 2017/04/03 17:36:19 error unmarshaling rules from JSON: rule with kind "freespace" is not supported`

Looks to be an incompatibility between versions of inspector, I expect this could be worked around with a custom rules file, but I cannot find an example of this.

Any hints?

**Comment by alexbrand** [comment]
Hey @TimWoolford 

You should not have to modify the inspector's rule set. This does seem to point to the possibility that an old inspector server is running on the node when we run the upgrade preflight checks.

Can you remove the inspector binary and service from one of the machines to see if the this resolves it?

**Comment by TimWoolford** [comment]
Thanks @alexbrand, yes the new binary had been installed into /bin, but there was a running process left over from the 1.2.2 installation.

**Comment by TimWoolford** [comment]
--dry-run passes now, but @swade1987 told me not to upgrade just yet ;-)

**Comment by alexbrand** [comment]
This is unexpected. Action to take here is to manually reproduce this issue, and change our inspector setup tasks to stop existing inspectors before starting the new one. From a quick glance at the ansible play, we should already be doing this, but seems like we are not.

**Comment by TimWoolford** [comment]
I've retraced my steps and I can reproduce the issue by running `kismatic install validate` after the cluster had been built.

This fails due to port availability - obviously, but leaves the inspector running on the nodes.

Probably not many people will do silly things like this.

**Comment by alexbrand** [comment]
This was fixed by #525
