### ISSUE TITLE
private ip for etcd cause error when add new node

### ISSUE THREAD

**Issue by alirezaDavid** [apprenda/kismatic#469]
Hi
I created a new cluster (all node has internal ip).
After that i want add some new node but pre flight section show some error
```
   - Port Accessible: 2379: Port 2379 on host "*.*.*.*" is unreachable. Error was: dial tcp *.*.*.*":2379: getsockopt: connection refused

```
etcd listens on private ip and it seems kismatic trying to reach etcd in public ip.

Thanks

**Comment by dkoshkin** [comment]
We currently run the checks from the install node using the public IP, to get around this for now you can run the installer with `--skip-preflght` option.

**Comment by alexbrand** [comment]
Hey @alirezaDavid - it seems like you are attempting to run `kismatic install apply` against an existing cluster. 

We currently don't support running preflights against an existing cluster. However, you may use @dkoshkin's suggestion to skip preflight checks when calling `apply`.
