### ISSUE TITLE
Support nodes with existing docker installation

### ISSUE THREAD

**Issue by dkoshkin** [apprenda/kismatic#474]
Kismatic should be able to detect if docker is already installed and skip the package installation.

Supporting machines with running docker will allow users to configure docker in custom ways and possibly use different versions of docker.

The only requirement for the machine will be to have the `docker` command line and docker be managed by `systemd` with a service `docker`. (this is the default configuration when installing docker packages)

**Comment by alexbrand** [comment]
What are the upgrade implications here? This _needs_ to be thought through and considered.

**Comment by dkoshkin** [comment]
Closed in #1051
