### ISSUE TITLE
Verify Hostname task fails if inventory hostname includes domain.

### ISSUE THREAD

**Issue by TimWoolford** [apprenda/kismatic#483]
This worked fine in v1.2.2 but new verification fails in latest release.

```
[user@vm002734 kismatic-v1.3.1-beta0]$ ./kismatic install validate -f staging-slu.yaml

Validating==========================================================================
Reading installation plan file "staging-slu.yaml"                               [OK]
Validating installation plan file                                               [OK]
Validating SSH connectivity to nodes                                            [OK]
Configure Cluster Prerequisites                                                 [OK]
Run Cluster Pre-Flight Checks                                                   [ERROR]
- Task: verify hostname
  vm002756.bskyb.com: provided hostname does not match reported hostname of vm002756[ERROR]
  vm002757.bskyb.com: provided hostname does not match reported hostname of vm002757[ERROR]
  vm002758.bskyb.com: provided hostname does not match reported hostname of vm002758[ERROR]
  vm002754.bskyb.com: provided hostname does not match reported hostname of vm002754[ERROR]
  vm002755.bskyb.com: provided hostname does not match reported hostname of vm002755[ERROR]
  vm002752.bskyb.com: provided hostname does not match reported hostname of vm002752[ERROR]
  vm002753.bskyb.com: provided hostname does not match reported hostname of vm002753[ERROR]
  vm002759.bskyb.com: provided hostname does not match reported hostname of vm002759[ERROR]
  vm002760.bskyb.com: provided hostname does not match reported hostname of vm002760[ERROR]
  vm002761.bskyb.com: provided hostname does not match reported hostname of vm002761[ERROR]
error running playbook: error running ansible: exit status 2
[sonique@vm002734 kismatic-v1.3.1-beta0]$
```

**Comment by alexbrand** [comment]
Calico performs auto-detection of hostnames, and it uses the result of `hostname` to do so. We have seen issues in the past with calico where machines that had the FQDN configured as the machine's `hostname`. This is what led us to add this validation. 

Is it possible that the machine is misconfigured? `hostname` should return the hostname, and `hostname -f` should return the FQDN.

**Comment by TimWoolford** [comment]
```

**Comment by alexbrand** [comment]
Excellent. Thanks @TimWoolford!

**Comment by alexbrand** [comment]
I think I misread the original issue. It seems like you are using FQDNs in the plan file? Is that the case? If so, is there a reason why you need to use FQDNs?

**Comment by TimWoolford** [comment]
Yes, I am using FQDNs.

From the bastion we don't need to, but the plan file is generated by another process, on another network, which may need it.


Right now, I can't get the apiserver to stay up with >= v1.3.0, but thats a different issue.

**Comment by alexbrand** [comment]
Got it. Thanks @TimWoolford.

The calico team actually recommends setting the hostname in the calico configuration, instead of relying on the auto detection of hostnames. 

I am thinking we should probably do this, and then relax the hostname check as you did in #484
