### ISSUE TITLE
Cannot specify custom IP address range for Services or Pods

### ISSUE THREAD

**Issue by Anarethos** [apprenda/kismatic#487]
Hi,

I currently have an issue with Kismatic (1.2.2 and 1.3.1). If I change the IP address range for the Services or Pods in the "kismatic-cluster.yaml", the deployment fails.

Everything is running under Vagrant on a Windows host.

The "smoke" test fails. I end up with no kubeconfig file at the end and cannot do anything. I have to revert my Vms and use the default IP settings.

All my Vms are in the 192.168.56.0/24 network.

Local hosts file are correctly set between all Vms.

Master1 + Node1 + Node2 ==> Oracle Linux 7.2 (with modified os-release file to act as a CentOS Linux).
Management node / Ansible ==> Ubuntu Trusty
Host : Windows 10 (with Virtual Box + Vagrant)

We also have the same problem with out lab environemnt, using Oracle Linux under OVM.

**Comment by Anarethos** [comment]
Here is the error message when I change the default settings.

[ERROR]
- Task: fail if any DNS pods are not ready
  master1: Timed out waiting for DNS pods to be in the ready state.
[ERROR]
error installing: error running playbook: error running ansible: exit status 2

**Comment by dkoshkin** [comment]
@Anarethos  What are you using for `master.load_balanced_fqdn` and `master.load_balanced_short_name`, we intentionally do not mount the `/etc/hosts` files in the kube-dns pod.

Those addresses need to be resolvable without relying on the `hosts` file.

**Comment by dkoshkin** [comment]
You can also run `kismatic diagnose` to collect cluster data. This will include numerous things including _systemd_ services and component logs.

**Comment by Anarethos** [comment]
I use the IP of the single Master.
```
load_balanced_fqdn: "192.168.56.10"
load_balanced_short_name: "192.168.56.10"  
```

I will retry the deployment and, then, use the diagnose command and post the result here.

Like I said, if I use the default IP range 
```
pod_cidr_block: 172.16.0.0/16
service_cidr_block: 172.17.0.0/16 
```
it works.

But if I chnage it to
```
pod_cidr_block: 172.20.0.0/16
service_cidr_block: 172.21.0.0/16 
```

it doen't works and fails.

**Comment by Anarethos** [comment]
I'm using the following Vms in my scenario. The "ansible" Vm if also my deplyment client.

```
master1 : 192.168.56.10
node1 : 192.168.56.30
node2 : 192.168.56.31
ansible : 192.168.56.40
```

The local hosts file of each server is correctly configured to find the others servers.

**Comment by dkoshkin** [comment]
Thanks @Anarethos I will try to reproduce this locally.

**Comment by dkoshkin** [comment]
@Anarethos in your first comment you mentioned the _smoketest_ fails, what is the issue you are seeing?
Did it look something like:
```
Ping kubernetes service from BusyBox                                            [ERROR]
-------- OUTPUT --------
PING kubernetes (172.21.0.1): 56 data bytes

--- kubernetes ping statistics ---
5 packets transmitted, 0 packets received, 100%!p(MISSING)acket loss
------------------------
```

Also when did you see a DNS failure, was it on a different install?

**Comment by Anarethos** [comment]
Here is the error.

Running Smoke Test==================================================================
SUDO password:
Smoke Test Master Node
Smoke Test Master Node
Smoke Test Master Node                                                          [ERROR]
- Task: run smoke test checks using Kuberang
  master1:                                                                      [ERROR]
---- STDOUT ----
Kubectl configured on this node                                                 [OK]
Delete existing deployments if they exist                                       [OK]
Nginx service does not already exist                                            [OK]
BusyBox service does not already exist                                          [OK]
Nginx service does not already exist                                            [OK]
Issued BusyBox start request                                                    [OK]
Issued Nginx start request                                                      [OK]
Issued expose Nginx service request                                             [OK]
Both deployments completed successfully within timeout                          [OK]
Grab nginx pod ip addresses                                                     [OK]
Grab nginx service ip address                                                   [OK]
Grab BusyBox pod name                                                           [OK]
Accessed Nginx service at 172.21.114.53 from BusyBox                            [OK]
Accessed Nginx service via DNS kuberang-nginx-1492018238882347878 from BusyBox  [OK]
Accessed Nginx pod at 172.20.166.132 from BusyBox                               [OK]
Accessed Nginx pod at 172.20.104.5 from BusyBox                                 [OK]
Accessed Google.com from BusyBox                                                [OK]
Accessed Nginx pod at 172.20.166.132 from this node                             [OK]
Accessed Nginx pod at 172.20.104.5 from this node                               [OK]
Accessed Google.com from this node                                              [OK]
Ping kubernetes service from BusyBox                                            [ERROR]
-------- OUTPUT --------
PING kubernetes (172.21.0.1): 56 data bytes

--- kubernetes ping statistics ---
5 packets transmitted, 0 packets received, 100%!!(MISSING)p(MISSING)acket loss
------------------------

Powered down Nginx service                                                      [OK]
Powered down Busybox deployment                                                 [OK]
Powered down Nginx deployment                                                   [OK]
---- STDERR ----
Error running command: One or more required steps failed
---------------
error during smoke test: error running playbook: error running ansible: exit status 2

**Comment by Anarethos** [comment]
I am not able to reproducte th eDNS error stuff. But this error (the smoke test error) is always the same.

**Comment by dkoshkin** [comment]
Got it, we figured out the [issue](https://github.com/apprenda/kuberang/pull/33) and will release shortly.

**Comment by Anarethos** [comment]
Thanks!

Now, if I want Docker to use also another range other than 172.17.0.0, can this be set in Kismatic or I will have to do that manually in the cluster after?

Bacause if we wanted to change the service/pods segment is because we are using the 172.16.0.0 as out IP range here for our Wifi network and this cause problems when using Kubernetes.

**Comment by dkoshkin** [comment]
Currently we do not provide a method to configure docker, but it can always be done manually after the install.
If you do end up needing to modify the docker CIDR we would love to hear your feedback, why it was needed and any issues you were seeing 😄

**Comment by Anarethos** [comment]
Thanks. I will see what I can do then. 👍
