### ISSUE TITLE
Remove the need to update /etc/hosts files on nodes

### ISSUE THREAD

**Issue by dkoshkin** [apprenda/kismatic#49]
With new versions of Calico components, using hostnames for TLS is no longer required.
This should reduce the total install time on large clusters.

**Comment by dasmb** [comment]
Host file updating is slow but it's also a convenience intended for small clusters without DNS.

My suggestion to anyone installing on large clusters would be to use DNS, and turn off the host file update.

**Comment by dkoshkin** [comment]
I think if its not a requirement it would make sense to just remove it. Updating the hosts file was sort of a hack to get Calico working.

**Comment by dkoshkin** [comment]
Closing until we have a better idea if this is possible/wanted.
