### ISSUE TITLE
generated certs have an empty DNS SAN

### ISSUE THREAD

**Issue by kwtalley** [apprenda/kismatic#498]
When certs are generated at deployment, there is an empty DNS SAN:

X509v3 Subject Alternative Name:
                DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, DNS:router, **DNS:**, IP Address:127.0.0.1, IP Address:10.200.0.1, IP Address:10.2.0.11, IP Address:10.2.0.11, IP Address:10.2.0.11

This can break some applications (deis) which attempt to contact the apiserver via https due to cert/hostname mismatch.

**Comment by alexbrand** [comment]
@kwtalley Was this the certificate for a specific node?

**Comment by alexbrand** [comment]
I am unable to repro after the changes in #499, which included refactoring of cert generation code. I am going to attempt to repro without those changes now.

**Comment by alexbrand** [comment]
Thanks @kwtalley
