### ISSUE TITLE
Update smoke tests

### ISSUE THREAD

**Issue by dkoshkin** [apprenda/kismatic#51]
Track additional test cases for the smoke test:

- Verify all services are in the `running` state
- `kubectl cluster-info` should not timeout - tests kubeconfig file: run this from outside the cluster?
- `kubectl get nodes` should  == node count from the plan file

**Comment by alexbrand** [comment]
The first check seems like it should live in kuberang?

I am not quite sure I understand what the second test is asserting, as we use kubectl to deploy stuff before the smoke test.

**Comment by dkoshkin** [comment]
Will track in a proposal if we want to do this
