### ISSUE TITLE
port check fails after retrying failed install

### ISSUE THREAD

**Issue by bryanlarsen** [apprenda/kismatic#510]
My installation failed fairly late in the process (waiting for KubeDNS).   I fixed my configuration, and then I retried doing `./kismatic install apply`.

Now it fails because it claims that ports aren't available/accessible.   Of course they aren't available, etcd and other parts of Kubernetes are running on them.

I tried cleaning up after kismatic:   `apt-get purge kismatic-etcd kismatic-kubernetes-networking kismatic-kubernetes-node kismatic-kubernetes-master`

And then I get:
- Running task: verify etcd_k8s cluster health
  server                                                               [ERROR]
---- STDOUT ----
cluster may be unhealthy: failed to list members
---- STDERR ----
Error:  client: etcd cluster is unavailable or misconfigured
error #0: dial tcp 127.0.0.1:2379: getsockopt: connection refused
---------------

I'm not sure why, I can `systemctl start etcd_k8s` on all three machines and then `sudo /usr/bin/etcdctl --cert-file=/etc/etcd_k8s/etcd.pem --key-file=/etc/etcd_k8s/etcd-key.pem --ca-file=/etc/etcd_k8s/ca.pem --endpoint=https://127.0.0.1:2379/ cluster-health` and get success.

**Comment by bryanlarsen** [comment]
This appears to be a duplicate of #130, if you reopen that one I can close this one and move discussion over there.

**Comment by dkoshkin** [comment]
@bryanlarsen there is a flag to skip preflight checks `--skip-preflght`.
You can also try rerunning the install with `--restart-services` flags to force restart etcd prior to checking the status.

**Comment by bryanlarsen** [comment]
That's what I needed, thanks!

**Comment by jonmosco** [comment]
I dont see any documentation for those flags and keep getting  unknown flag.

**Comment by dkoshkin** [comment]
@jonmosco take a look at https://github.com/apprenda/kismatic/blob/master/docs/kismatic-cli/kismatic_install_apply.md, you can also run `kismatic --help` to see a list of commands and flags.
