### ISSUE TITLE
Replace KubeDNS with CoreDNS

### ISSUE THREAD

**Issue by swade1987** [apprenda/kismatic#511]
As [CoreDNS](https://coredns.io/) is now in the CNCF we should look at replacing KubeDNS

We would need to add the cluster IP to [https://goo.gl/cVn3WU](https://goo.gl/cVn3WU)

Execute the script and then delete the `kube-dns` deployment.

**Comment by alexbrand** [comment]
Has CoreDNS been chosen as the successor to KubeDNS by the Kube community? I know they are working towards it, but last I checked it wasn't quite ready yet. If you have any docs/links around that, that would be awesome to read up on.

**Comment by tjheslin1** [comment]
+1

**Comment by josephjacks** [comment]
https://github.com/kubernetes/features/issues/427

**Comment by alexbrand** [comment]
Thanks @josephjacks!

**Comment by luxas** [comment]
This is shipping in kubeadm v1.9. Check out https://github.com/kubernetes/kubeadm/issues/446

**Comment by jaycoon** [comment]
Need to understand the migration impact (if any) for existing Kismatic users on KubeDNS.

**Comment by luxas** [comment]
Then look at the kubeadm code :)

**Comment by swade1987** [comment]
adding @miekg to help if/when required.

**Comment by swade1987** [comment]
Closed, will be part of the KET 1.8.0 release.
