### ISSUE TITLE
Have kubectl inside the Kismatic binary ready to use

### ISSUE THREAD

**Issue by swade1987** [apprenda/kismatic#516]
The user should be able to interact with the cluster straight away after it's been provisioned.

They shouldn't need to download and install Kubectl as a separate step.

We can also pin the Kubectl version to the version of Kubernetes being used for the release.

**Comment by alexbrand** [comment]
Meaning `./kismatic kubectl get pods`?

**Comment by swade1987** [comment]
As part of the provisioning step, it should go ahead and install the version of Kubectl associated with the specific Kubernetes release. 

For offline installs, the kubectl binary would need to be packaged inside the Kismatic binary.

**Comment by alexbrand** [comment]
I think it makes sense to include `kubectl` in the tarball.
