### ISSUE TITLE
calicoctl not found

### ISSUE THREAD

**Issue by akasetty** [apprenda/kismatic#519]
Just installed K8S cluster using kinematic on CentOS7.3 VMs.  Everything is working fine so far.

I am unable to find calicoctl utility,  I thought it was installed on all the master nodes as per this link [https://github.com/apprenda/kismatic/blob/master/docs/NETWORKING.md](NETWORKING.md)

How do I go about installing calicoctl (either as a docker image or install it on the master nodes directly)

**Comment by alexbrand** [comment]
@akasetty Those docs are out of date, and they are being updated here: https://github.com/apprenda/kismatic/pull/517

**Comment by alexbrand** [comment]
@akasetty  Just merged the new docs with the updated information.

**Comment by akasetty** [comment]
Thanks @alexbrand.
