### ISSUE TITLE
Error running ansible playbook [OSX] 

### ISSUE THREAD

**Issue by johscheuer** [apprenda/kismatic#53]
When I try to provision a Cluster with kismatic I get the following error:

```bash
$ kismatic install validate
Validating==========================================================================
Reading installation plan file "kismatic-cluster.yaml"                          [OK]
Validating installation plan file                                               [OK]
error running preflight: error running ansible playbook: error writing inventory file to "ansible/inventory.ini": open ansible/inventory.ini: no such file or directory
```

What I did:

- Install kismatic
- `kismatic install plan` with defaults
- Adjust `kismatic-cluster.yaml`
- run `kismatic install apply`

and in the dir the following files are:

```bash
$ tree
├── kismatic-cluster.yaml
└── runs
    └── preflight
        └── 2016-11-08-16-56-11
            ├── ansible.log # is empty
            └── kismatic-cluster.yaml
```

**Comment by dkoshkin** [comment]
What does the directory where you are running this from looks like, the `kismatic` binary needs the `anisble` folder to be in the same directory. 
Also you should run it from inside that directory, ie. `./kismatic install validate`

**Comment by johscheuer** [comment]
Ah Okay, I see this was my error. When I tried it again with everything in one folder it works.

Thanks!
