### ISSUE TITLE
Kube-api dies when the manifest is modifed

### ISSUE THREAD

**Issue by dkoshkin** [apprenda/kismatic#532]
After modyfing the `--runtime-config` field in a running cluster the api docker container never gets started. 
To fix the cluster, had to remove the file `/etc/kubernetes/manifests/kube-apiserver.yaml` and then place it back in the directory.

Expected the changes to be picked up by the kubelet and for the pod to restart successfully.

This _might_ cause issues during upgrades when the spec definition is modified and not just the container versions.

**Comment by alexbrand** [comment]
Is this that issue we had seen before where the kubelet had to be restarted if any of the manifests changed? Trying to find the issue and found this one: https://github.com/kubernetes/kubernetes/issues/44450 which is pretty fresh.

**Comment by dkoshkin** [comment]
I don't remember exactly but I believe that was issue was about labels changing.
Just tested this myself with `vim` it failed with the same behavior.

Closing this as this is really na upstream fix and our upgrade process does not rely on modifying in an editor.
