### ISSUE TITLE
Use x509 client auth for kubelet, kube-proxy and control plane components

### ISSUE THREAD

**Issue by alexbrand** [apprenda/kismatic#535]
Currently, the kubelet, kube-proxy and the control plane components use token-based authentication with the admin's token. This means that this admin token is spread across all the nodes of the cluster.

Now that we are moving towards RBAC, we should instead use x509 certificate authentication with least-privileged accounts that are specific to each component.

The following are users/groups that should be used for each of the components:

Component | User | Group
------------|-------|-------
Scheduler| system:kube-scheduler| |
Controller Manager |system:kube-controller-manager| |
Kubelets | system:node:$hostname | system:nodes
Kube-proxy | system:kube-proxy | |

These certificates will be generated during our cert generation phase. Once generated, they will be copied over to the respective nodes. These certificates will be used in `kubeconfig` files that are specific to each component.

**Impact on upgrade**
It seems like as long as the existing CA is available, we can generate these new certificates, and replace them during the upgrade process. It's unclear to me at this time if we can ensure that the certs are re-generated, as it will be up to the user to not include them in the `generated` dir.

**Comment by ikester** [comment]
Seems like the right thing to do. I don't understand the concern in your last sentence. If it's part of the upgrade can't we just re-generate them and distribute them?

**Comment by alexbrand** [comment]
Historically, we have supported "bring your own" certs by not clobbering existing certificates.

**Comment by alexbrand** [comment]
Currently, if a node is both an `etcd` and a `master` node, the `kube-apiserver` and the `etcd` server use the same certificate. I am thinking we should probably have component-specific certificates here as well. That is, have a certificate that is specific to `etcd`, and another that is specific to the API server. What do you think?

cc @ikester @dkoshkin

**Comment by ikester** [comment]
Yes. Let's give each component type a cert of their own.

**Comment by alexbrand** [comment]
Kubedns should be able to use the service account to connect to the API server. However, there is a bug in kubedns that prevents us from specifying the location of the API server without specifying credentials: https://github.com/kubernetes/dns/issues/72. For this reason, `kubedns` will continue using the `admin` user and password until the issue is fixed.

**Comment by alexbrand** [comment]
Keeping this open to revisit a couple of things:
- [ ] Documentation of admin cert change
- [ ] Revisit kubedns comment https://github.com/apprenda/kismatic/issues/535#issuecomment-300243621 as the issue has been fixed.

**Comment by alexbrand** [comment]
We should be able to update to kubeDNS version 1.14.2 and stop using the `admin` user/password, as https://github.com/kubernetes/dns/issues/72 has been fixed.
