### ISSUE TITLE
Helm: tiller does not start up when doing a disconnected install

### ISSUE THREAD

**Issue by alexbrand** [apprenda/kismatic#539]
Test run: https://app.snap-ci.com/apprenda/kismatic/pull/538/logs/defaultPipeline/3/slow-test?back_to=build_history

Search for: "disconnected install feature"

**Comment by dkoshkin** [comment]
This is expected as the packages are not yet built with tiller :)

**Comment by dkoshkin** [comment]
Fixed with #545
