### ISSUE TITLE
NGINX version - ssl-passthrough issue

### ISSUE THREAD

**Issue by akdj** [apprenda/kismatic#543]
Hello, 
I just want to make a remark. 

With another issue of mine, I discovered that there is a something wrong with the version 0.8.3 of `gcr.io/google_containers/nginx-ingress-controller` in Kismatic v1.3.2. 

In fact, the `ingress.kubernetes.io/ssl-passthrough: "true"` annotation in ingresses, doesn't work,   I can't acccess to my service with https header. 

I solved this issue by changing the image `gcr.io/google_containers/nginx-ingress-controller:0.8.3` to another image `quay.io/aledbf/nginx-ingress-controller:0.107 `   see #https://github.com/kubernetes/ingress/issues/699
There may be a good version of this image in gcr.io/google_containers, need to verify

**Comment by dkoshkin** [comment]
Hi @akdj was there an update on this that you can share? Thanks

**Comment by akdj** [comment]
@dkoshkin 
Hi
It is seen that with this docker image (quay.io/aledbf/nginx-ingress-controller:0.107), my ingress annotation  `ingress.kubernetes.io/ssl-passthrough: "true"` is working, I can now access to my service with `https:// `header and my dns address

However, I am not sure, but it is seen that I lost my ingress loadbalancer capabiltity, so maybe this image has some problems too...
