### ISSUE TITLE
Kismatic install on Azure having issues with Calico overlay network

### ISSUE THREAD

**Issue by engelr1974** [apprenda/kismatic#547]
When I install a kubernetes cluster using the Kismatic playbook on Azure Linux (CentOS 7.2) servers, everything appears to be installing okay, but when I deploy a single Pod to one of my worker nodes, I cannot address that Pod from a different node in the cluster.  I can route to all of the Pod, Service, and NodePort on the actual worker node the Pod is running on, but not on any other nodes.  Any known incompatibilities with Calico on Azure, or something special to configure?

**Comment by alexbrand** [comment]
Hey @engelr1974 

Calico networking is not supported on Azure, unfortunately.

**Comment by engelr1974** [comment]
Ah, that explains a lot of my frustration here.  Is there a documented alternative I can use for my overlay network in the Kismatic install?

**Comment by alexbrand** [comment]
We currently only support Calico as our networking plug in, which means we are unable to deploy a cluster on azure using kismatic at the moment.

**Comment by frankgreco** [comment]
@alexbrand can you please go into a lot more detail. Why doesn't Calico work on Azure. It is a networking limitation? Is it calico specific or the way that kismatic implements calico in kismatic? If possible, can you go into as low level detail as you can.

**Comment by frankgreco** [comment]
so interestingly enough, Azure does not support ipip

**Comment by alexbrand** [comment]
Hi @frankgreco, certainly:

Calico uses IP-IP encapsulation as the technique to create the overlay network for the pods in Kubernetes. The problem on Azure is that their network does not support IP-IP encap. 

When calico runs as a pure L3 routed fabric (no overlay), it uses BGP peering to broadcast the IP addresses of the pods. Unfortunately, BGP peering is also not supported on Azure at the moment.

The Calico team's recommendation for running Calico on Azure is to use Calico Policy + Native Azure networking (if you are using ACS-Engine), or Calico Policy + Flannel networking.

**Comment by frankgreco** [comment]
@alexbrand thanks! that's makes a lot more sense. Didn't know azure was so behind

**Comment by alexbrand** [comment]
No problem!

**Comment by ranajit-jana** [comment]
As working with azure we are facing same issue. I see flannel is not supported right now in the latest code at https://github.com/apprenda/kismatic/blob/master/pkg/install/plan_types.go
first thing is in case we introduce flannel what will be version of flannel which  will go with the  version as stated in https://github.com/apprenda/kismatic/blob/master/ansible/group_vars/container_images.yaml . If any references which  can be provided  calico policy can work with flannel will be very helpful

**Comment by alexbrand** [comment]
@ranajit-jana KET can install clusters on Azure when using Weave as the CNI plugin. Would this work for you?

**Comment by ranajit-jana** [comment]
yes. Will try . Thank you

**Comment by ranajit-jana** [comment]
It did not work. 

DNS containers did not start as expected
Task: fail if DNS pod validation command could not determine if the DNS pods are ready
  dsci-kube-master: Waited for all DNS pods to be ready, but they took longer than 5 minutes to be in the ready state.
===========================

kubectl get pods -n kube-system
NAME                                       READY     STATUS              RESTARTS   AGE
kube-apiserver-dsci-kube-master            1/1       Running             0          11m
kube-controller-manager-dsci-kube-master   1/1       Running             0          12m
kube-dns-66676c8c6-clhhr                   0/3       ContainerCreating   0          10m
kube-dns-66676c8c6-jnr98                   0/3       ContainerCreating   0          10m
kube-proxy-dsci-kube-master                1/1       Running             0          11m
kube-proxy-dsci-kube-node1                 1/1       Running             0          11m
kube-proxy-dsci-kube-node2                 1/1       Running             0          11m
kube-scheduler-dsci-kube-master            1/1       Running             0          12m
weave-net-pfzbk                            2/2       Running             0          10m
weave-net-r7sqc                            2/2       Running             0          10m
weave-net-vq6tp                            2/2       Running             0          10m

=============
Containers did not come up correctly.
Weave was able to install as you can see in the list of the pods

**Comment by ikester** [comment]
Several teams have been using KET with Weave for Azure deployments successfully over the past few months. If you find a new issue with Weave on Azure please feel free to open a new issue.
