### ISSUE TITLE
dashboard fails when pass has slashes

### ISSUE THREAD

**Issue by mrgleeco** [apprenda/kismatic#560]
eg. when pass is `zHWGW7SpuuafmUQuVdvjDVBa/xxhejAh`

```
$ ./kismatic dashboard -f ./kismatic-cluster.yaml
Error verifying connectivity to cluster dashboard: Get https://admin:zHWGW7SpuuafmUQuVdvjDVBa/xxhejAh@10.20.30.40:6443/ui: invalid URL port "zHWGW7SpuuafmUQuVdvjDVBa"
```
Possibly disturbing to some folks that it is printed to terminal.

This is on v1.3.3

**Comment by dkoshkin** [comment]
Thanks @mrgleeco, was this password generated by the installer or did you specify this password yourself in the plan file?

**Comment by mrgleeco** [comment]
hello - i created it with cmd like `cat /dev/urandom | base64 | head -c 32`

**Comment by emmetthitz** [comment]
This appears to also fail when the password contains double-quotes.
