### ISSUE TITLE
Unreachable node does not show up in kismatic info command output

### ISSUE THREAD

**Issue by bgregorius** [apprenda/kismatic#563]
If you have a node that "goes away" the kismatic info command does not show the affected node in the output.

Discovered on an AWS cluster where a node started failing AWS status checks, couldn't ssh to the node, etc.

kismatic info stopped reporting that node as part of the cluster
kubectl get nodes however still showed the node with a NotReady status

The expectation here is that kismatic info should show all nodes that are part of the cluster until they have explicitly been removed.

**Comment by alexbrand** [comment]
I tried to reproduce this issue but failed to do so. Before even displaying node information, we verify that we can SSH to all machines in the cluster.

My suspicion here is that the bad node was replaced with a new node with the same identity that was up and running. Given that we currently default the case of "no kismatic version file" to `v1.0.0`, the `kismatic info` command happily reported that.

We should improve this but I am dropping the priority for now.
