### ISSUE TITLE
With epel enabled on etcd nodes yum update breaks etcd

### ISSUE THREAD

**Issue by tsikorski** [apprenda/kismatic#568]
Hi,
Just a heads up for the community. If you enabled epel on the systems where etcd is built a yum update will overwrite the kismatic version of etcd with a new version which then then break kismatic etcd.
Kismatic etcd creates two files /usr/bin/etcd_k8s  /usr/bin/etcd_networking which will be overwritten if you do yum updates via cron and you have epel enabled. 
The solution is to either put an exclusion in /etc/yum.conf or disable epel. Just an fyi.

--
Ted

**Comment by alexbrand** [comment]
Fixed in #756. We don't install etcd using yum anymore.
