### ISSUE TITLE
Add ability to enable/disable seeding of images to private container image registry

### ISSUE THREAD

**Issue by alexbrand** [apprenda/kismatic#589]
Currently, the `disconnected_installation` flag controls both the source of the container images (private registry or docker hub) and whether KET should seed the private container registry. This means that it is currently not possible to perform a disconnected install using a registry that requires authentication, or a registry that is not writable by Kismatic nodes.

**Comment by alexbrand** [comment]
I _think_ what we need is a new flag that controls the seeding of the private registry.

The decision tree would look something like this:

```
if disconnected_install is true:
    if private_registry not provided and kismatic_registry not requested:
        return error
    if seed_registry is false and private_registry not provided:
        return error
    if seed_registry is true:
        install_ket_offline_package()
        seed_registry()
    
    install_ket_using_private_registry()
    
else:
    use default registries available over internet (gcr.io, dockerhub, etc)
```

**Comment by dkoshkin** [comment]
To maintain backwards compatibility, I _think_ we need to flip the variable to `diasble_seeding_registry` or use a pointer and check for nil.

IMO `diasble_seeding_registry` makes more sense since this is something a user would opt out from.
