### ISSUE TITLE
Configurable reclaimPolicy for adding a persistent-volume

### ISSUE THREAD

**Issue by tjheslin1** [apprenda/kismatic#609]
The `pv.yaml` template has persistentVolumeReclaimPolicy hardcoded to 'Retain'. (see below)

https://github.com/apprenda/kismatic/blob/master/ansible/roles/persistent-volume/templates/pv.yaml#L12

I would recommend adding a flag to `kismatic storage add` to override this default.

Scenario: 
As every Persistent Volume (PV) I create is set to _Retain_ this means I have to manually wipe the contents of the PV every time I want to redeploy.

**Comment by alexbrand** [comment]
We should definitely expose a way to set the reclaim policy on the volumes created by KET.

**Comment by tjheslin1** [comment]
@alexbrand Thanks for this! What milestone is this going in?

**Comment by alexbrand** [comment]
@tjheslin1 I'll try to squeeze it into 1.4 as I know it's a blocker for you.

**Comment by tjheslin1** [comment]
@alexbrand cheers dude. Thanks for the quick turnaround. In the future is be happy to raise a PR for changes I'd like made. Nothing needed right now.

Your PR gives me something to go by in the future.
