### ISSUE TITLE
Uppercase hostnames cause an issue

### ISSUE THREAD

**Issue by dkoshkin** [apprenda/kismatic#634]
A user reported an issue when installing with a plan file that contained an uppercased hostnames.

When doing k8s pod validation, the installer is looking for `kube-apiserver-K8SMASTER`, but the name is actually `kube-apiserver-k8smaster`.

**Comment by jesse-welch** [comment]
I am experiencing a similar issue as well.  I have a hostname with mixed case:

`$ hostname
TINY14k01`

Kismatic attempts to check on the apiserver pod using the actual hostname:

`fatal: [TINY14k01]: FAILED! => {"changed": true, "cmd": ["kubectl", "get", "pods", "kube-apiserver-TINY14k01", "--namespace", "kube-system", "-o", "jsonpath={.metadata.annotations.kismatic/version}", "--kubeconfig", "/root/.kube/config"], "delta": "0:00:00.121128", "end": "2017-07-07 20:26:24.175489", "failed": true, "invocation": {"module_args": {"_raw_params": "kubectl get pods kube-apiserver-TINY14k01 --namespace kube-system -o jsonpath='{.metadata.annotations.kismatic/version}' --kubeconfig /root/.kube/config", "_uses_shell": false, "chdir": null, "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "rc": 1, "start": "2017-07-07 20:26:24.054361", "stderr": "Error from server (NotFound): pods \"kube-apiserver-TINY14k01\" not found", "stdout": "", "stdout_lines": [], "warnings": []}`

Manually running this check using a completely lowercase name does provide a valid result:

`$ sudo kubectl get pods kube-apiserver-tiny14k01 --namespace kube-system -o jsonpath={.metadata.annotations.kismatic/version} --kubeconfig /root/.kube/config
1.3.0`

**Comment by alexbrand** [comment]
Damn. I think this basically means that we have to treat hostnames as case-sensitive, even though they are not under normal circumstances.
