### ISSUE TITLE
API Server does not start after upgrade to 1.7 with a certificate issue

### ISSUE THREAD

**Issue by holgerstolzenberg** [apprenda/kismatic#642]
I was running a a `K8N-1.6` cluster provisioned by `Kismatic-1.3.3` on a local Vagrant `1/1/1` setup. The Vagrant machines are on `centos/7`.

I tried to upgrade the cluster to 1.7 using `kismatic-v1.4.0-darwin-amd64`. I downloaded the binaries and extracted them. Then I copied over the manifest file `kismatic-cluster.yaml` and the `generated` folder, modified deprecated config values and started a offline upgrade.

The upgrade runs fine for the `etcd` node but fails for the `master` node:

![kismatic-upgrade-error](https://user-images.githubusercontent.com/282736/28109108-31969cc6-66ee-11e7-8d3e-3129005ff91b.png)

SSHing into the master and digging around, it turns out the kube-apiserver does not come up.

```
[root@ci-lab-master-01 ~]# docker ps
CONTAINER ID        IMAGE                                                                                                                            COMMAND                  CREATED             STATUS              PORTS               NAMES
9835b6352ba5        gcr.io/google-containers/kube-controller-manager-amd64@sha256:1bd41ae3ca8572e31ba40ad052c6751348c8d072d63c5f42688bc94826898431   "kube-controller-mana"   11 minutes ago      Up 11 minutes                           k8s_kube-controller-manager_kube-controller-manager-ci-lab-master-01_kube-system_5ca04c1c9d2b7b8841b2ea8992658dd3_0
7a02f3315532        gcr.io/google-containers/kube-scheduler-amd64@sha256:692f837a12bee4da127b8a8fab2338b9beb108e1f33b1838286f3fd26a25705d            "kube-scheduler --kub"   11 minutes ago      Up 11 minutes                           k8s_kube-scheduler_kube-scheduler-ci-lab-master-01_kube-system_6ec122cf33c2d3317809ff6823f1d8ce_0
6ddc4df24dad        gcr.io/google-containers/kube-proxy-amd64@sha256:2c6f2b7b3d1a93c1e238a5ee4d0a2d9f7bcdad607254b99d4489ec920d26ca01                "kube-proxy --cluster"   11 minutes ago      Up 11 minutes                           k8s_kube-proxy_kube-proxy-ci-lab-master-01_kube-system_b6168df4c15a14e30647bac1db701206_0
d577ed5dc513        gcr.io/google_containers/pause-amd64:3.0                                                                                         "/pause"                 11 minutes ago      Up 11 minutes                           k8s_POD_kube-controller-manager-ci-lab-master-01_kube-system_5ca04c1c9d2b7b8841b2ea8992658dd3_0
9f1a25ad8fcd        gcr.io/google_containers/pause-amd64:3.0                                                                                         "/pause"                 11 minutes ago      Up 11 minutes                           k8s_POD_kube-scheduler-ci-lab-master-01_kube-system_6ec122cf33c2d3317809ff6823f1d8ce_0
a4ad4528dec5        gcr.io/google_containers/pause-amd64:3.0                                                                                         "/pause"                 11 minutes ago      Up 11 minutes                           k8s_POD_kube-proxy-ci-lab-master-01_kube-system_b6168df4c15a14e30647bac1db701206_0
d239f0d74278        gcr.io/google_containers/pause-amd64:3.0                                                                                         "/pause"                 11 minutes ago      Up 11 minutes                           k8s_POD_kube-apiserver-ci-lab-master-01_kube-system_13051828efcff9068bad3bcb40a38c0f_0
```

In order to be able to get better logs, created a docker command from the `kube-apiserver` manifest in order to test if the api-server comes up:

```bash
#!/bin/bash

docker run -it --rm --name apiserver \
        -p 8080:8080 -p 6443:6443 \
        -v /etc/kubernetes:/etc/kubernetes \
        -v /usr/share/ca-certificates:/etc/ssl/certs \
        gcr.io/google-containers/kube-apiserver-amd64:v1.7.0 \
        kube-apiserver \
      --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota \
      --advertise-address=192.168.205.11 \
      --allow-privileged=true \
      --anonymous-auth=false \
      --apiserver-count=1 \
      --authorization-mode=RBAC,ABAC \
      --authorization-policy-file=/etc/kubernetes/auth/authorization-policy.json \
      --basic-auth-file=/etc/kubernetes/auth/basicauth.csv \
      --bind-address=0.0.0.0 \
      --client-ca-file=/etc/kubernetes/pki/ca.pem \
      --enable-swagger-ui=true \
      --etcd-cafile=/etc/kubernetes/pki/ca.pem \
      --etcd-certfile=/etc/kubernetes/pki/etcd-client.pem \
      --etcd-keyfile=/etc/kubernetes/pki/etcd-client-key.pem \
      --etcd-servers=https://192.168.205.10:2379 \
      --insecure-bind-address=127.0.0.1 \
      --insecure-port=8080 \
      --runtime-config=extensions/v1beta1=true,extensions/v1beta1/networkpolicies=true \
      --secure-port=6443 \
      --service-account-key-file=/etc/kubernetes/pki/service-account-key.pem \
      --service-cluster-ip-range=172.20.0.0/16 \
      --tls-cert-file=/etc/kubernetes/pki/api-server.pem \
      --tls-private-key-file=/etc/kubernetes/pki/api-server-key.pem \
      --v=2 \
      --logtostderr=true \
```

During the start up of the container, the apiserver endpoint ports become available via telnet/curl but no real communication can be established. It looks like this is somehow related to SSL certificate issues, on which I haven´t changed anything.

I´ll attach the complete logs in the next comment.

Any idea on that?

**Comment by holgerstolzenberg** [comment]
[out.txt](https://github.com/apprenda/kismatic/files/1141392/out.txt)

**Comment by alexbrand** [comment]
@holgerstolzenberg I have run into something like this before, but don't quite remember the exact details. I think I was able to figure it out by trying to write something to etcd using etcdctl, as that is where the kubernetes API server is getting stuck.

```
docker run -e "ETCDCTL_API=3" \
  -v /etc/kubernetes/pki:/pki \
  --net host \
  quay.io/coreos/etcd \
  etcdctl --endpoints https://192.168.205.10:2379 \
    --cert /pki/etcd-client.pem \
    --key=/pki/etcd-client-key.pem \
    --cacert /pki/ca.pem put test test
```

**Comment by holgerstolzenberg** [comment]
@alexbrand 
* I stopped kubelet and all containers
* Executed your command
* Restartet kubelet

It helps. The `apiserver` comes up. I was able to fully run the upgrade to K8N `1.7`. So thanks for that.

Still I´d like to get to know how you diagnosed the problem as I did not have the `etcd` under suspect. 
* What is the interesting line(s) in the logfile?
* What does your command actually change? As I understand it it just puts `test=test` to the KV store of `etcd`?
* Is this a problem of K8N itself or may their be a bug in Kismatic 1.4?

**Comment by alexbrand** [comment]
Whenever I have run into that issue it was always related to connectivity issues between the API server and the etcd server. Thus, I was expecting the command I posted to fail and provide useful diagnostic information about the error.

However, it seems like in this case the underlying cause was different. Another possibility is that the node running the API server was overloaded, and the API server simply did not have time to connect. It's hard to tell at this point, unfortunately.

I am going to close this. Feel free to reopen if you disagree.
