### ISSUE TITLE
Static pods changes are not always picked up during a cluster upgrade

### ISSUE THREAD

**Issue by dkoshkin** [apprenda/kismatic#643]

**Comment by alexbrand** [comment]
@dkoshkin I believe we diagnosed and fixed this issue in https://github.com/apprenda/kismatic/issues/702. The problem was that new kubelets were unable to talk to the API server due to RBAC being disabled in the pre-upgrade API servers. 

Can you confirm this issue is in relation to that?

**Comment by dkoshkin** [comment]
I opened this issue when it was originally opened on our slack, this in fact the same as #702 and closed with #703.
