### ISSUE TITLE
error: unable to Configure Heapster Cluster Monitoring

### ISSUE THREAD

**Issue by mvasilenko** [apprenda/kismatic#644]
Hello

Got an error while trying to install fresh kismatic cloned from sources

```
error: unable to decode "/etc/kubernetes/specs/heapster-rbac.yaml": no kind "ClusterRoleBinding" is registered for version "rbac.authorization.k8s.io/v1beta1"
```

stdout
```
Start Kubernetes DNS                                                            [OK]
Configure Heapster Cluster Monitoring                                           [ERROR]
- Task: create heapster rolebinding`
  vagrant:                                                                      [ERROR]
---- STDERR ----
error: unable to decode "/etc/kubernetes/specs/heapster-rbac.yaml": no kind "ClusterRoleBinding" is registered for version "rbac.authorization.k8s.io/v1beta1"
---------------
error installing: error running playbook: error running ansible: exit status 2
```

ansible run logs

failed yaml - `kismatic/ansible/playbooks/roles/heapster/tasks/main.yaml:20`
failed command - `kubectl apply -f /etc/kubernetes/specs/heapster-rbac.yaml`

do i need to supply any additional details for this error?

**Comment by dkoshkin** [comment]
Hi @mvasilenko is this a new install or an upgrade?
What OS are cluster and the install machines?
Where are these machines? Cloud, vagrant baremetal? 

Have you tried rerunning the install or is this the only time you tried?

**Comment by mvasilenko** [comment]
sorted out by wiping destination machine and installing again
