### ISSUE TITLE
Glusterfs starts with NFS disabled / offline 

### ISSUE THREAD

**Issue by hornjason** [apprenda/kismatic#645]
**Setup**:
Kismatic:
  Version: 1.4.0
  Built: Wed Jul  5 23:02:36 UTC 2017
  Go Version: go1.8
Vagrant generated with the provision tool, 
 Vagrantfile: bento/ubuntu-16.04
 3 **MasterNodes**: ( includes etcd and storage  on each )
 2 **WorkerNodes**

After deploying the above configuration with no issues and adding a volume using kismatic Noticed NFS on each storage node shows offline and rpcbind stopped.  After enabling / restarting rpcbind everything started working.  

**Volume Add:**

`kismatic volume add 8 jenkins-data  -r 2 -d 1 -c=durable  --access-modes  ReadWriteOnce  
`

**PV / PVC Status:**
The PVC bound successfully to the new PV,

```
kubectl get pv jenkins-data
  jenkins-data   8Gi        RWO           Retain          Bound     default/loping-bear-jenkins   durable
```

**POD NFS Times out:**
The pod times out trying to NFS mount the volume

```
  kubectl describe po/podname
```
```
  Mounting command: mount
  Mounting arguments: 172.20.33.125:/jenkins-data1 /var/lib/kubelet/pods/af287470-67e7-11e7-
  aac1-080027192ca4/volumes/kubernetes.io~nfs/jenkins-data1 nfs []
  Output: mount.nfs: Connection timed out
```
 
**Storage Nodes:**
Noticed on each storage node glusterfs shows nfs disabled

```
Gluster process                             TCP Port  RDMA Port  Online  Pid
------------------------------------------------------------------------------
Brick master002:/data/jenkins-data          49152     0          Y       23140
Brick master001:/data/jenkins-data          49152     0          Y       24346
NFS Server on localhost                     2049      0          N       24367
Self-heal Daemon on localhost               N/A       N/A        Y       24374
Quota Daemon on localhost                   N/A       N/A        Y       24419
NFS Server on master002                     2049      0          N       23163
Self-heal Daemon on master002               N/A       N/A        Y       23162
Quota Daemon on master002                   N/A       N/A        Y       23209
```

But gluster volume info shows **NFS enabled**

```
gluster volume info
  Volume Name: jenkins-data
  ...
  nfs.disable: off

```

**Changing ansible/playbooks/roles/glusterfs/tasks/main.yaml** seems to have fixed the issue.

```
- name: reload systemd daemon
   command: systemctl daemon-reload
- name: start rpcbind service
   service:
     name: rpcbind.service
     state: started
     enabled: yes
 - name: start glusterfs-server service
```

**Comment by dkoshkin** [comment]
Thanks @hornjason tested manually and was able to reproduce. Your fix worked.
