### ISSUE TITLE
Using [SKIPPED] for un-supported component upgrades

### ISSUE THREAD

**Issue by swade1987** [apprenda/kismatic#670]
I feel we should be using `[SKIPPED]` instead of `[ERROR]` when KET is upgrading components we don't support, see below ...

```
ingress1 [ingress]                                                              [ERROR]
- Performing an online upgrade of ingress nodes is not supported.
storage1 [storage]                                                              [ERROR]
- Performing an online upgrade of storage nodes is not supported.
storage2 [storage]                                                              [ERROR]
- Performing an online upgrade of storage nodes is not supported. 
```

The user should only be seeing the word `[ERROR]` when something has gone wrong with the process being executed.

**Comment by willvrny** [comment]
I'd agree with @swade1987. Skipped seems more appropriate.

**Comment by dkoshkin** [comment]
I do agree that seeing `[ERROR]` is unexpected here but I think `[SKIPPED]` might be just as confusing, as it might indicated that that node will be skipped and not upgraded.

What do you think of `[WARNING]` printed in orange color?

**Comment by swade1987** [comment]
Agreed I feel that `[INFO]` would be better than `[WARNING]` but the orange colour makes sense.

**Comment by alexbrand** [comment]
The important thing here is to properly communicate to the user that KET cannot guarantee that ingress and storage will remain available during the upgrade.

**Comment by swade1987** [comment]
@alexbrand are we not just stating that Ingress and Storage nodes aren't going to be upgraded? If so, we just need to make the user aware of this.

**Comment by alexbrand** [comment]
No, that is not what is being communicated. Ingress and Storage nodes are still upgraded if you pass the `--ignore-safety-checks` flag.

**Comment by alexbrand** [comment]
I think the resolution here should also include improving the messages that are being printed. I can see where the confusion is coming from.

**Comment by swade1987** [comment]
@alexbrand you read my mind, it's not obvious when you read the message what is going on under the covers.
