### ISSUE TITLE
Add Contiv as a CNI provider

### ISSUE THREAD

**Issue by alexbrand** [apprenda/kismatic#671]
Introduce support for Contiv as a CNI provider.

- [x] Figure out if we can use etcd v3
- [x] Figure out if we can use secure etcd endpoints (how to pass certificates to wherever they are needed): 
Doesn't look like contiv currently supports an etcd cluster over HTTPS,
 as it uses the default HTTP transport in the etcd client,
 and there is not way to override it.
 (https://github.com/contiv/netplugin/blob/master/state/etcdstatedriver.go#L62).
- [x] Figure out if contiv supports multiple etcd nodes
Contiv currently doesn't support multiple etcd nodes in the backend. It only sets one URL when building the etcd client:
 (https://github.com/contiv/netplugin/blob/master/state/etcdstatedriver.go#L63).
- [ ] Translate installation script into an ansible play
- [x] Figure out what to do about taints - the taint is used for a replicaset that should only run on master nodes. We can probably rework this to use a daemonset.
- [x] "Own" the resources that get deployed
- [ ] How to ship the contiv binary (`netctl`) - probably use a container similar to what we'll do with CNI

**Comment by robotica72** [comment]
@alexbrand - This is something I was going to ask about - I had issues trying to get Contiv running and I did manage to get fairly close but ran out of time - you hit the key point on the taint - aside from that it would have worked for me....  But this would be an awesome choice for people during installation - nothing against Calico, working well for my lab, but I did want to kick Contiv around a bit....

**Comment by alexbrand** [comment]
@robotica72 We are planning to release an initial version of contiv support in v1.5.0. Would be great if you review the PRs once they are ready. Any input is welcome!

**Comment by robotica72** [comment]
@alexbrand Sounds great, would love to look at it and offer input - very interested since we are looking at Contiv as a deployment at work (Global deployment) and with some of the restrictions like the taint on the Master using Kismatic, or even other deployments, it hasnt been a smooth test - so would welcome an easier integration :)

**Comment by robotica72** [comment]
Oh nice Alex - Im going to look at that - I appreciate it

**Comment by alexbrand** [comment]
@robotica72 Excellent! Feel free to comment here or on the PR with any feedback.
