### ISSUE TITLE
Suggestion : Validate should check for Docker on Node

### ISSUE THREAD

**Issue by robotica72** [apprenda/kismatic#672]
Obviously this isn't a huge issue, but since there is a validate command to check the nodes for a smooth upgrade, you might want to add a check for the installation of Docker on the nodes.  I forgot I had docker on my one image and I cloned it out to 13 machines for a new lab at home, validate was clean - so I kicked off an apply and it bombed at the Docker check since it was installed on the nodes.  Easy enough to remove it with an ssh command, but still - an add on into validate might help newer people?

Just a thought... and great work as always....

**Comment by alexbrand** [comment]
@robotica72 Can you share a bit more about how it bombed with Docker? Thanks!

**Comment by robotica72** [comment]
Hey - sorry meant to add to my statement that day but got sidetracked - It bombs out installing docker due to docker conflicting with container-selinux-2.12-2.gite7096ce.el7.noarch - But the validate passed this section without any issues.  (I should have known better, I just forgot about my base template and what was in it).   So overall, just a suggestion for anyone who may be newer/etc ...  

But excellent installer overall - best I have seen for K8s.

**Comment by dkoshkin** [comment]
Closed in #875

**Comment by dkoshkin** [comment]
Commented out the checks until there is a mechanism to have docker preinstalled on the node by the user.

**Comment by dkoshkin** [comment]
Closed in #1051
