### ISSUE TITLE
Implement log rotation for all components that KET deploys

### ISSUE THREAD

**Issue by alexbrand** [apprenda/kismatic#674]
To prevent nodes from filling up their disks, KET should configure log rotation on all the components that are deployed.

We can most likely take advantage of systemd's built-in log rotation capabilities for systemd services. In the case of containerized components, we can use docker's built-in log rotation. This, however, would need more consideration as it would affect workload logs as well.

**Comment by willvrny** [comment]
@alexbrand Would be great to see this added to KET soon. I agree with leveraging the built in log rotation in Docker. We might need this for any Kubernetes components that are logging to the node.

@swade1987 @dkoshkin Do you have any further thoughts on this?
