### ISSUE TITLE
Have a way to define log-opts for docker daemon

### ISSUE THREAD

**Issue by prat0318** [apprenda/kismatic#685]
I want log rotation to be enabled for docker daemon so that i don't face disk full issues later. Hence, i want:
```
  "log-opts": {
    "max-size": "20m",
    "max-file": "10"
  }
```
in the `/etc/docker/daemon.json` in addition to the `direct-lvm` settings added by kismatic.

Either these settings should be taken in the `kismatic-cluster.yaml` or have a way to insert `log-opts` to the daemon settings.

**Comment by prat0318** [comment]
Might be related to #674

**Comment by alexbrand** [comment]
Thanks @prat0318. We will tackle this soon.

**Comment by mrgleeco** [comment]
+1 for customzied `daemon.json`.  In addition to altering log type, would like to implement overlay as storage driver.

**Comment by alexbrand** [comment]
As part of this issue, I think we should consider opening up the ability to configure any docker daemon option.

**Comment by willvrny** [comment]
I think the `daemon.json` option is better than passing a flag. The Docker docs state a really good reason for this:

> The daemon includes many configuration options, which you can pass as flags when starting Docker manually, or set in the daemon.json configuration file. The second method is recommended because those configuration changes persist when you restart Docker.

It would be good to provide the `daemon.json` option as default. We currently only do it when direct-lvm is used.

**Comment by alexbrand** [comment]
We won't be able to tackle this as part of the 1.6.0 release. We will look into it for the next one.
