### ISSUE TITLE
Calico Routed Network - BGP for Service IP's?

### ISSUE THREAD

**Issue by robotica72** [apprenda/kismatic#687]
My Calico BGP is working great for the PODs and routing with my Ubiquity switches - but of course the service IPs are not of the BGP Peering - Is there any way to get the service subnets to Peer with BGP??

**Comment by alexbrand** [comment]
That's an interesting question @robotica72. We have reached out to the calico team to ask about it. However, it might be better if you reach out to them directly as they might have some questions. You can reach them through an issue or their Slack channel. They are pretty responsive.

**Comment by robotica72** [comment]
Thanks Alex - I had a quick chat with some of your team - actually a few and today was around that idea.   Overall, it can be done in a way - but it gets a bit tough, I think, with the ASN assignment.   Load balancer was always one way, but Im thinking globally and we do not deploy F5's all over the place.  So I had few directions I could look, but as you may be able to - the question is more related to using K8s as an IaaS replacement where it makes sense....  I see a benefit in it, but Team Calico may think its crazy talk too :)   I am going to look into some Bird configs to see what might make sense.

**Comment by alexbrand** [comment]
Got it @robotica72. In that case, I am going to close this issue. Please reach out if you make some progress on this!
