### ISSUE TITLE
Problem with direct_lvm configuration in 1.4.1

### ISSUE THREAD

**Issue by robb-foster-ck** [apprenda/kismatic#693]
I believe that there is a small problem with the direct_lvm ansible.  The line in question is

`/home/kismaticuser/ansible/playbooks/roles/preflight/tasks/direct_lvm_preflight.yaml:    with_items: ansible_mounts`

I believe that should be, as it is elsewhere, `/home/kismaticuser/ansible/playbooks/roles/preflight/tasks/direct_lvm_preflight.yaml:    with_items: "{{ ansible_mounts }}"`

When I make that change, my install works.

**Comment by alexbrand** [comment]
Thanks @robb-foster-ck!

This was fixed (https://github.com/apprenda/kismatic/pull/684), and will be coming out in the next release this week.
