### ISSUE TITLE
Increase validate-pod timeout

### ISSUE THREAD

**Issue by swade1987** [apprenda/kismatic#694]
I feel a timeout of two minutes is a little short (see below).

[https://github.com/apprenda/kismatic/blob/master/ansible/roles/validate-pod/tasks/validate-pod.yaml#L7-L8](https://github.com/apprenda/kismatic/blob/master/ansible/roles/validate-pod/tasks/validate-pod.yaml#L7-L8)

I am wondering if we should increase this to no longer than five minutes to allow for network connectivity issues.

@alexbrand thoughts?

**Comment by alexbrand** [comment]
Based on your recent installation experiences, I think we should increase it. We'll tackle this soon.
