### ISSUE TITLE
Upgrade versions of Calico, Kubernetes and Dashboard

### ISSUE THREAD

**Issue by swade1987** [apprenda/kismatic#701]
- [Calico v1.4.0](https://github.com/projectcalico/calicoctl/releases/tag/v1.4.0)
- [Dashboard v1.6.3](https://github.com/kubernetes/dashboard/releases/tag/v1.6.3)
- Kubernetes v1.7.3(once released)

Note: Kubernetes v1.7.3 is specifically important as it will fix cAdvisor metrics being exposed correctly via the Kubelet therefore not breaking clients Grafana dashboards pre v1.7.0.

**Comment by alexbrand** [comment]
Calico v1.4.0 has breaking changes, which means it needs to go into KET v1.6.0

**Comment by swade1987** [comment]
Can we also upgrade to NGINX v0.9.0 it's got some necessary functionality? 

https://github.com/nginxinc/kubernetes-ingress/releases
