### ISSUE TITLE
Enhancement: Use proxy configuration to update each node's profile

### ISSUE THREAD

**Issue by emedina** [apprenda/kismatic#713]
Hi,

When I create a K8s cluster with Kismatic, as I'm in a corporative environment, I need to manually (or through automated provisioning) configure in /etc/profile.d/proxy.sh the proxy to use to connect to Internet, plus which local addresses should be ignored by the proxy. A typical example would be:

`export http_proxy="http://10.138.129.1"`
`export no_proxy="10.138.129.2,10.138.129.3,10.138.129.4,10.138.129.5`

As this configuration needs to be provided to the `kismatic-cluster.yaml` as well, and Kismatic can already handle the /etc/hosts in each server for us, wouldn't it be interesting to use it to configure the server's boot profile as well?

Regards.

**Comment by alexbrand** [comment]
Thanks @emedina. We actually don't want to get into configuring machines, as we consider that is the responsibility of the user/system provisioning the machines. Feel free to reopen if you disagree.
