### ISSUE TITLE
Force the installation of expected docker version

### ISSUE THREAD

**Issue by emedina** [apprenda/kismatic#717]
Currently, at least in CentOS 7, when the `ansible-yum` command requests to install the docker engine, if other `yum` repositories are configured in the machine where a newer version of `docker` is available, the latter is eventually installed.

In my case, I was expecting `docker 1.12.6` and I was getting all the time `docker 17.06`. Therefore, I had to install it manually with:

`yum install --disablerepo=* --enablerepo=kismatic docker-engine-1.12.6-1.el7.centos`

Maybe this should be also handled by the tool as well.

**Comment by dkoshkin** [comment]
We have moved to using upstream docker repos, this will no longer be needed.
