### ISSUE TITLE
dashboard spelt dashbard in plan file

### ISSUE THREAD

**Issue by robb-foster-ck** [apprenda/kismatic#722]
Kismatic 1.5.0/CentOS 7.2.1511

I don't know if this is by plan, but, after running *kismatic install plan*, the output contains the element *dashbard* as part of the intended configuration, I believe, for the *dashboard*.

**Comment by dkoshkin** [comment]
Thanks @robb-foster-ck this was already fixed in https://github.com/apprenda/kismatic/pull/720 and will be released shortly. 
To remain backwards compatible `dashbard` will still be respected
