### ISSUE TITLE
Use official distribution packages for Kubernetes and other cluster components

### ISSUE THREAD

**Issue by alexbrand** [apprenda/kismatic#724]
Given that the community has started building and maintaining official distribution packages for Kubernetes, we should transition over to using them instead of maintaining our own.

Overall, our packaging and distribution strategy should follow these principles for all components:
- Use upstream packages and bits unchanged
- Support natural way of distribution/packaging that is being created by the community
- If official distribution strategy is unavailable, prefer a container for simplification of disconnected install use case.

| Component | Distribution |
|-------------|-------------|
| Docker         | Official Docker packages for each distro |
| Etcd             | Tarball or Container image |
| Kubelet        | Official RPM/DEB (pending further investigation) |
| Control plane components | Official container images (unchanged) |
| CNI | Official distribution is not available. Using custom built container |
| CNI Add-on providers | Official container images (unchanged) |
| Other add-ons | Official container images (unchanged) |

**Upgrade Considerations**
Performing this transition will require the removal of our own packages and package repositories during the upgrade.

Open questions:
- [x] Why did kubeadm decide to use RPMs/DEBs instead of using containers for the Kubelet?

**Comment by swade1987** [comment]
@alexbrand I was talking to Kris Nova about Kubeadm and see said it's extremely hard to run inside a container due to the volumes.

**Comment by alexbrand** [comment]
Notes on why kubelet is not run inside container:
https://docs.google.com/document/d/1XLZR0OQckXVSB6xVcaqkSWUzufllOMRR9eeWEpGNjJY/edit

**Comment by alexbrand** [comment]
Closed via #768
