### ISSUE TITLE
Revamp the disconnected installation technique

### ISSUE THREAD

**Issue by alexbrand** [apprenda/kismatic#725]
As we move from custom built distribution packages to upstream packages, we will have to revamp our disconnected installation documentation / technique. The main trigger for this work is that we will most likely lose the "offline" package, which means KET will either a) stop being responsible for seeding the container registry, or b) change the seeding process.

**Container Images**
Components that are distributed as container images will need to be available in an internal container image registry. Potential solutions here, from simpler to more complex:

1. Maintain a list of container images that are required during an installation. The user is responsible for seeding their internal registry with all images.
2. Maintain a script that must be run by the user prior to the installation. This script will contain a list of the container images that are required for an installation, and will download, tag, and push each one to the internal registry.
3. Make KET compute the required container images according to the selected options, add-ons, etc. KET can then seed the registry from the installation machine. This assumes that the installation machine has internet access and a docker client that can be used to download, tag and push images.

**OS Packages**
If we are unable to shed the need for RPM/DEB packages, we can continue to accept a list of private package repositories. The user is responsible for seeding the private repository with the required packages. Some potential improvements to the current status quo:

1. Maintain a script for each supported linux distro that builds a package repository mirror.
2. Maintain a container image that has a pre-built repository mirror. This container can then be started by the user internally.

**Comment by swade1987** [comment]
@alexbrand would love to collab with you guys on the whole "disconnected install" story.

**Comment by jaycoon** [comment]
For **OS Packages** and using the `package_repository_urls` flag, KET could help quite a bit as part of the **Plan** step, similar to the proposal for Container Image management.

Currently it is not clear what packages are needed for an install or upgrade, so configuring a disconnected install is not trivial. Since Kismatic is aware of all the packages it needs to do an install, part of the **Plan** process can be providing a list of all packages needed, and optionally automate this further by:

1. Pulling all required packages down to a local node
2. Pushing binaries to a **private repo** (specified by the user, with credentials)
3. Setting the `package_repository_urls` flag with private repo URLs

**Comment by alexbrand** [comment]
@jaycoon This is an excellent idea, but I don't think there's a way to "push" OS packages to repositories. Are you familiar with any repositories that support this?

**Comment by jaycoon** [comment]
@alexbrand I mean automating the repo sync. 

If we assume the user is managing/syncing the repo as described in [packages.md](https://github.com/apprenda/kismatic/blob/master/docs/packages.md), we would be most concerned with setting `package_repository_urls` with the user-specified base URL automatically. 

Automation of downloading packages and updating the repo helps the user manage their repo, though we would need to manage scripts for both `yum` and `apt-get`, and are making assumptions on how the repo was set up (which is risky). I think there is more benefit in building the repo mirror (as described in the original enhancement).

I'm favoring the container image repo mirror proposal right now, as we can deploy it as needed (during install/upgrades).

**Comment by alexbrand** [comment]
Closed via #814
