### ISSUE TITLE
Including Rook as another storage option

### ISSUE THREAD

**Issue by swade1987** [apprenda/kismatic#726]
The more and more I read about [https://rook.io/](https://rook.io/ )the more I feel we need to provide this as an option to users of Kismatic.

**Comment by josephjacks** [comment]
Thanks @swade1987! Let me know how we can help out. Rook 0.5 is landing soon and would be a great time to test with KET. cc @bassamtabbara

**Comment by swade1987** [comment]
Happy for this to be removed in light of the other outstanding issues taking priority.

**Comment by dkoshkin** [comment]
Storage is a complex topic and is very much dependent on the organization and the use case, if Rook is required it can be installed by the operator after the cluster is running.
