### ISSUE TITLE
Docker 1.12 is getting EOL'd in November

### ISSUE THREAD

**Issue by aquasheep20** [apprenda/kismatic#739]
is it possible to use docker-ce instead of os distribution docker on ubuntu 16.04?

**Comment by alexbrand** [comment]
We currently don't support docker CE, as it hasn't been vetted yet by the Kubernetes community. Was there a feature that you were looking for that is only available in docker CE?

**Comment by aquasheep20** [comment]
I'm running portworx, which requires Docker 1.13 or higher to install as a v2 plugin

**Comment by aquasheep20** [comment]
Or can you tell me what the plan is for Docker in Kismatic?  Docker end of support/EOL for 1.12 is November 2017

**Comment by alexbrand** [comment]
Thanks @aquasheep20!

Unfortunately, there are known issues with Kubernetes and docker > 1.12, such as https://github.com/kubernetes/kubernetes/issues/40182, which is mainly why we haven't bumped up the version. Furthermore, the upstream e2e tests continue to test against 1.12.

The community is working towards validating newer versions of docker, and we will closely track that effort to move away from 1.12 as soon as we can.

**Comment by dkoshkin** [comment]
Closed in #868
