### ISSUE TITLE
Include dns-autoscaler as an option

### ISSUE THREAD

**Issue by dkassab** [apprenda/kismatic#741]
https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns-horizontal-autoscaler

**Comment by swade1987** [comment]
This would be extremely useful for a client issue we are dealing with presently.

**Comment by swade1987** [comment]
@dkassab do you see this as a necessity or happy to close the issue?

**Comment by dkoshkin** [comment]
This can be installed post installation and as off `v1.9.2` the DNS replicas can be specified in the plan file. https://github.com/apprenda/kismatic/pull/1172
