### ISSUE TITLE
Manage package dependencies in a private repo

### ISSUE THREAD

**Issue by jaycoon** [apprenda/kismatic#742]
This is an enhancement request, that would be used in conjunction with a **Disconnected Install** and the `package_repository_urls` flag. 

Currently it is not clear what packages are needed for an install or upgrade, so configuring a disconnected install is not trivial. Since Kismatic is aware of all the packages it needs to do an install, part of the **Plan** process can be providing a list of all packages needed, and optionally automate this further by:

1. Pulling all required packages down to a local node
2. Pushing binaries to a **private repo** (specified by the user, with credentials)
3. Setting the `package_repository_urls` flag with private repo URLs

**Comment by alexbrand** [comment]
This is awesome Jay! We are planning on revamping the disconnected installation and packaging for the next milestone release. Do you mind adding these thoughts to #725? That way we can have a single issue for this.

**Comment by jaycoon** [comment]
Sure thing! Didn't see [#725](https://github.com/apprenda/kismatic/issues/725) when I searched (quickly)

**Comment by alexbrand** [comment]
Thanks! I'm going to close this then.
