### ISSUE TITLE
HTTP proxy, preflight

### ISSUE THREAD

**Issue by dkoshkin** [apprenda/kismatic#745]
KET does not set the `no_proxy` setting when running preflights. In scenarios where the install nodes are also behind a proxy, that proxy is being used to connect to the other nodes in the cluster where in most cases it should not be.

This requires some though how to solve this.
1) Use the same configuration as the rest of the cluster
2) Use different configuration fields for the `preflight` 
3) Run the preflight client from within the cluster. This would also fix https://github.com/apprenda/kismatic/issues/187

**Comment by alexbrand** [comment]
Would another option be setting always setting NO_PROXY to include all the nodes in the cluster?

**Comment by dkoshkin** [comment]
Would that be KETs responsibility or the users?

**Comment by robb-foster-ck** [comment]
For something like *add-worker*, it would help a lot if KET added the new worker to the no_proxy, otherwise that needs to be scripted outside of KET, which adds more complexity.
