### ISSUE TITLE
HTTP proxy, add worker

### ISSUE THREAD

**Issue by dkoshkin** [apprenda/kismatic#746]
When using the proxy settings, it is most likely required to set the `no_proxy` flag equal to a list of all IPs and Hostnames of the nodes.

However, when using the `add-worker` command, this will break unless the user modified the plan file prior to running the install.

KET should verify that the new node is in the `no_proxy` list and append to it, or at least fail the validation.

**Comment by alexbrand** [comment]
> When using the proxy settings, it is most likely required to set the no_proxy flag equal to a list of all IPs and Hostnames of the nodes.
Can we make this not true? I think I'd rather we figure out a way to not burden the user with this requirement, but it's not very clear if/how we can do that.
