### ISSUE TITLE
kubernetes-dashboard doesn't work at first, can't find api server

### ISSUE THREAD

**Issue by seeekr** [apprenda/kismatic#75]
`Kismatic version: 8bd4462%` (Current release / 1.0.0)

Working my way through setting up a cluster using KET. One issue I've come across is that after the initial cluster deployment the dashboard doesn't work:

```
$ kubectl -n kube-system logs kubernetes-dashboard-1872324879-qh85b
Using HTTP port: 9090
Creating API server client for https://172.17.0.1:443
Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: the server has asked for the client to provide credentials
Refer to the troubleshooting guide for more information: https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md
```

So I went about digging for what might be the problem. Long story short -- I finally just reapplied the KET-generated `/tmp/kubernetes-dashboard.yaml` on my master node and the dashboard pod came up healthy.
So I'm assuming this might be a subtle timing or order of operations issue between bringing up the dashboard and something like bringing up the kube proxy or writing the kubeconfig file on that node. But you'll likely have a better idea of what might be going on here.

Thanks for the work on this tool, much appreciated!

**Comment by alexbrand** [comment]
I suspect this is due to #95

**Comment by seeekr** [comment]
This was definitely on a setup with multiple masters configured, if that is what you're asking. I'm assuming that at the point kismatic installs kube-dashboard all kube master processes should be up and running properly, but that's not something I had checked for.
HTH

**Comment by alexbrand** [comment]
Thanks @seeekr 

I am confident that this was caused by #95.

**Comment by seeekr** [comment]
@alexbrand Cool. But then this means that the cluster that I have right now (which is just a test cluster, haven't done a whole lot with it yet) is not in a properly functional state, iiu #95 correctly?

**Comment by alexbrand** [comment]
@seeekr unfortunately yes. Given that it's a test cluster you could recreate it. Feel free to reach out on our Slack channel if you need more help.

**Comment by seeekr** [comment]
@alexbrand Thanks, just wanted to confirm!
Re Slack channel: https://kismatic.slack.com/signup still says that only people with those specific email address domains are allowed to join, seems like the channel is still in a sort of "limited/invite-only preview" kind of mode!
