### ISSUE TITLE
Override kube-api server port

### ISSUE THREAD

**Issue by dkoshkin** [apprenda/kismatic#750]
Currently the user is forced to use port `6443` even when using a LB. We should expose a way to use the standard `443` port or any other port.

As part of this we should also rework
```
  load_balanced_fqdn: 
  load_balanced_short_name:
```

**Comment by msm93v2** [comment]
I just came here to raise this exact issue. In my use-case I run keepalived on the master nodes with nginx performing loadbalancing  to the api servers, this obviously requires nginx to listen on something other than 6443. I can still work around the issue by overriding --secure-port on the kube-apiserver, but think this would be an excellent feature to have regardless.

**Comment by dkoshkin** [comment]
Need to modify `all.yaml`, `kubeconfig.go`, `kubernetes-dns.yaml` and `kube-proxy.yaml`
