### ISSUE TITLE
how to run single (ansible) task?

### ISSUE THREAD

**Issue by seeekr** [apprenda/kismatic#76]
While working to bring up a cluster using KET I got stuck a few times when I'd have liked to run just a single thing from the long list of things that KET goes through, like for example "(re-)deploy kubernetes-dashboard addon".

I've tried it like this:

```
$ ./bin/ansible-playbook -i inventory.ini playbooks/_addon-kubernetes-dashboard.yaml
```

but that gave me an error like this:

```
TASK [addon-kubernetes-dashboard : copy kubernetes-dashboard.yaml to remote] ***
fatal: [s0]: FAILED! => {"changed": true, "failed": true, "module_stderr": "Shared connection to 172.21.12.10 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_Wx9I4L/ansible_module_copy.py\", line 364, in <module>\r\n    main()\r\n  File \"/tmp/ansible_Wx9I4L/ansible_module_copy.py\", line 343, in main\r\n    module.atomic_move(b_mysrc, dest, unsafe_writes=module.params['unsafe_writes'])\r\n  File \"/tmp/ansible_Wx9I4L/ansible_modlib.zip/ansible/module_utils/basic.py\", line 2001, in atomic_move\r\nNameError: global name 'exception' is not defined\r\n", "msg": "MODULE FAILURE"}
```

which I'm assuming is a result of variables not being defined or similar. (Not an expert in Ansible, so this is more of a guess.)

I'm sure you guys are running single tasks etc while developing the tool. Is there a way for me to do the same?
Also, related, do you guys have plans for a way for a regular end-user -- who might not know or understand anything about ansible -- to run any single of the defined tasks through the kismatic CLI? I'm imagining some capability for that will be necessary for cluster operations anyway, but it could also be a huge boon during complex cluster bring-up, e.g. when something fails for a silly and easily fixable reason like the user misconfiguring something slightly.
Reprovisioning every time and going through the whole cluster bring-up process every time is not desirable, not very enjoyable.

Thanks!

**Comment by seeekr** [comment]
Another use case:

Let's say I have at first brought up the cluster using `policy_enabled: false` but would now liked to enable policy enforcement. Changing the cluster yaml and then running `./kismatic install apply` again would go through the full process again, wouldn't it? And is that operation idempotent, i.e. can I just call it any number of times and it is guaranteed not to change anything that is already in the desired state?

**Comment by alexbrand** [comment]
Thanks @seeekr 

We are considering adding the ability to run single tasks, mainly as a debugging feature. However, we don't expect this to address the "enable policy later" use case, as this is a complex operation.

**Comment by alexbrand** [comment]
Addressed via https://github.com/apprenda/kismatic/pull/77

**Comment by hecko** [comment]
Im running into the same error message - Im really not sure what this Python exception represents and debugging Ansible is really not my strong side - can anyone explain the possible root cause of the following exception?

`An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_QRVC87/ansible_module_copy.py", line 364, in <module>
    main()
  File "/tmp/ansible_QRVC87/ansible_module_copy.py", line 343, in main
    module.atomic_move(b_mysrc, dest, unsafe_writes=module.params['unsafe_writes'])
  File "/tmp/ansible_QRVC87/ansible_modlib.zip/ansible/module_utils/basic.py", line 2001, in atomic_move
NameError: global name 'exception' is not defined
`
