### ISSUE TITLE
Have kube-state-metrics installed as an addon

### ISSUE THREAD

**Issue by prat0318** [apprenda/kismatic#761]
Currently, `kube-state-metrics` nor `heapster` give all the metrics like PersistentVolume Usage. Having [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics) by default will be a nice feature.

**Comment by alexbrand** [comment]
Thanks @prat0318. Definitely something that would add value, but not something we are looking to prioritize in the short term.

Is there anything that prevents you from deploying it manually after installing the cluster? I just want to make sure that we are not blocking you from doing it.

**Comment by swade1987** [comment]
@prat0318 just out of interest, if you would like kube-state-metrics would you also like Prometheus and Grafana as a default?

**Comment by prat0318** [comment]
@alexbrand nothing blocking.

@swade1987 that would be great. we currently install them via helm charts.

**Comment by alexbrand** [comment]
Got it. Thanks @prat0318

**Comment by swade1987** [comment]
@alexbrand as we have agreed that KET isn't going to be responsible for adding workloads to the cluster this issue can be closed.

**Comment by swade1987** [comment]
@prat0318 due to the statements above are you happy for this issue to be closed?

**Comment by alexbrand** [comment]
Agreed @swade1987. Closing  this out.
