### ISSUE TITLE
Certificate Change - Just for API/Dash internal CA Signed

### ISSUE THREAD

**Issue by robotica72** [apprenda/kismatic#765]
Ive been looking into this, but I have to admit Im a bit confused on getting to my end goal on this one.

All documentation around k8s (regardless of vendor) deals with self signed certificates for all components - or they document adding your own private root CA's for signing.   Neither of these will accomplish what I need for my corporate installations outside of my lab.

What I need to achieve is, at the very least, an internally signed certificate for anything externally facing (Non internal cluster communication) - So the API/Dashboard URL needs to be signed by my internal CA, which I need to request through a standard certificate request, which will return my public/private key.

I know where to change the certificate in the mater node for the API - but what confuses me is - All examples I find, which make sense, are based on a SANS certificate that has the desired Signed URL (ie: kube.xxxxx.xxxx - but they also include the standard kubernetes.cluster and other names for internal communication) - My PKI team will never sign a cert with that information in it - they will allow me to add the IPs and the official "internal" name - but they will not allow names that are not "owned" internally by the CA.

Do I have any options here?   If I run with a cert that doesnt have the internal kube domain name, but I do have the IP's, I assume I will have issues with internal functions?  (Sanity check here).

The only work around I have come up with is to use an internal cert on the load balanced URL on the F5 - Im not sure how security will look at it, thats why I am trying to verify options before I get to that point...   

Thanks for any suggestions.

**Comment by alexbrand** [comment]
> Do I have any options here? If I run with a cert that doesnt have the internal kube domain name, but I do have the IP's, I assume I will have issues with internal functions? (Sanity check here).

You will run into issues as pods that require access to the API server usually connect using the `kubernetes` service. If your cert doesn't have that SAN, the client will complain.

**Comment by robotica72** [comment]
Thanks Alex - I was thinking similar - so the confirmation helps, something I'll need to address before our prod install

**Comment by alexbrand** [comment]
Closing as this isn't actionable as is. Feel free to reopen if you disagree.
