### ISSUE TITLE
Service names - Dynamic DNS registration to Windows DNS Server?  Any value?

### ISSUE THREAD

**Issue by robotica72** [apprenda/kismatic#766]
So, Ive been writing a python script that I will convert to go (at least I will when I get time) that watches the API server and any adds/deletes will trigger a script that updates a Windows 2016 DNS Server entry for the service.   I have debating adding other backends, but I'm not there yet.

Two questions for people - am I the only person who sees value to this?   and next question - Am I re-inventing the wheel?   Does something exist today already?  (Non Cloud - so we cant use the nice easy loadbalanced option)

What I am accomplishing in my hacked together script now - Whats the API (I use Calico in Routed mode) and the name of the service is added to the DNS zone identified in the script.  Right now it all goes to the root domain name for my AD - I may add other options as I run into a requirement, but Im not going to go the route that internal Kube names are created for kube-dns.   I may decide to take a label for the DNS entry since I have already run into way too may names I would rather have for DNS name over the service name already :)

In the end, I would foresee a simple docker container with the script that watches the API with some passed parameters to the Windows DNS Server. (Or other backend, if expanded)

**Comment by dkoshkin** [comment]
Hi @robotica72, take a look at https://github.com/kubernetes-incubator/external-dns, it doesn't have support for Windows DNS Server, but I'm sure the community would find your work valuable, at the very least you can get some inspiration on how this project is watching the k8s resources.

**Comment by robotica72** [comment]
Hey Dimitri - good idea, I knew of that project but saw it didn't support Windows DNS so I went off to do it myself - but never considered contributing to the project or even mentioning it to the team...  Might be about time to contribute :)

**Comment by alexbrand** [comment]
Closing this. Feel free to reopen if you disagree.
