### ISSUE TITLE
Support the overlay2 docker storage driver

### ISSUE THREAD

**Issue by aquasheep20** [apprenda/kismatic#770]
any plans for kismatic support of overlay2 for Redhat? rhel 7.4 docker 1.12.6 docker can now use overlay2

**Comment by alexbrand** [comment]
Hey @aquasheep20,

We don't plan to in the short term, but we might bump it up in priority given that overlay2 is preferred over devicemapper. 

One thing that needs more thought is how to handle this during an upgrade. I haven't looked into it, but I imagine there is some migration that needs to happen from devicemapper to overlay2.

**Comment by swade1987** [comment]
Also, you need to disable SELinux to use overlay and overlay2 on RHEL or CentOS.

**Comment by aquasheep20** [comment]
i've got kismatic running on RH 7.4 with overlay2 on a new cluster.  remove docker-engine, install RH docker, disable selinux, disable container-storage-setup (echo STORAGE_DRIVER="" >> /etc/sysconfig/docker-storage-setup), add "storage-driver": "overlay2" to /etc/docker/daemon.json, add --cgroup-driver=systemd to /etc/systemd/system/kubelet.service.  make sure you push all your own images before you swap docker, & pull them back post swap.  All the k8s  images will be re pulled on their own.  This will also leave your cluster in a precarious situation for a kismatic upgrade.

**Comment by mrgleeco** [comment]
+1 to overlay2 options- as a general thing.   Would like to use on xenial.  Separate Issue?

**Comment by alexbrand** [comment]
Thanks @mrgleeco. I think we can keep both RHEL and Ubuntu in this issue.

**Comment by swade1987** [comment]
@aquasheep20 what version of Docker are you using with overlay2 also how do you find the performance?

**Comment by aquasheep20** [comment]
I'm using Ubuntu 16.04 with whatever docker kismatic is installing.  You can set overlay2 by creating  /etc/docker/daemon.json before installing kismatic.   

Mine for reference:  
{
  "storage-driver": "overlay2",
  "icc": false,
  "disable-legacy-registry": true,
  "live-restore": true,
  "userland-proxy": false
  }

**Comment by swade1987** [comment]
@aquasheep20 you mentioned RHEL 7.4 up above, is this not the case?

Regardless, pretty cool it was that straightforward to configure.

**Comment by aquasheep20** [comment]
The kismatic install on redhat 7.4 builds lvm-thinpool (unless its been updated) I've been busy with my day job lately.  I was only able to get overlay2 to work by removing docker-engine post kismatic install and reinstalling redhat docker with the overlay2 options set.  I wanted to see if it could be done and document any issues I came across.   If you go this route , a kismatic upgrade will wipe out the redhat docker install .   Really just laying groundwork for @alexbrand and company.

**Comment by swade1987** [comment]
https://raymii.org/s/tutorials/Ansible_-_Only_if_on_specific_distribution_or_distribution_version.html

Adding this here for future reference.

**Comment by dkoshkin** [comment]
Closed in #1067
