### ISSUE TITLE
Get inspiration from yeoman for capturing input for plan file.

### ISSUE THREAD

**Issue by codymccain** [apprenda/kismatic#78]
Yeoman provides a slick CLI workflow for capturing input used for scaffolding initial assets for a project.  We should adopt a similar UX experience for `kismatic install plan`.

http://yeoman.io/

Try out either the angular or jhipster generators as good examples.

**Comment by alexbrand** [comment]
We won't focus on this for now. From the way things have been progressing, it seems like most plan files will be generated by an external process.
