### ISSUE TITLE
Pass flags to the Kubelet

### ISSUE THREAD

**Issue by willvrny** [apprenda/kismatic#790]
FEATURE REQUEST

**Description**:

The Kubelet can be customised via flags. It would be great if we could define custom flags for Kismatic to apply to the Kubelet. The particular flags that I am interested in are:

- --max-open-files
- --max-pods
- --kube-reserved
- --system-reserved

I think it would be better for Kismatic to be flexible so that when new flags are added to the Kubelet a new release of Kismatic is not required.

**Comment by willvrny** [comment]
Looking into this further, setting the same values for all nodes would be assuming that all nodes are the same sizing. This also assumes that all nodes are running the same workloads. 

An example of this is smaller ingress nodes compared to worker nodes as they are just dedicated to running ingress.

It would be better to be able to either set the `kube-reserved` and `system-reserved` on a per node basis or on a component basis e.g. ingress versus worker.

See [here](http://node-perf-dash.k8s.io/#/builds) for a way of comparing kubelet performance under different workloads.

**Comment by alexbrand** [comment]
It would be nice to have a concept of "node pools", where you could group nodes together into pools and apply configuration at the pool level. Unfortunately we don't have that currently, and I don't think we should rush something that fundamental for 1.6.

From the user's POV, I think it would be painful to have to go node-by-node adding the flags, so if we want to implement node-level granularity, we would most likely also have to implement role-level granularity (worker vs ingress).

**Comment by swade1987** [comment]
I think this needs to be on a node-by-node basis.  As the settings will be dependent upon the workloads running on that given node. 

Also the flag values shouldn't be mandatory for every node, they should be allowed to be kept blank.

**Comment by alexbrand** [comment]
@swade1987 @willvrny Do you guys think it's a deal breaker if we only allow them to be set at a global level for the first iteration? We are thinking that once we learn more from our users use cases, we can improve it.

**Comment by willvrny** [comment]
@alexbrand The smallest node would dictate the value e.g. if you're running a smaller ingress node then you wouldn't want to take up all the resources as it wouldn't be schedulable but those values wouldn't be useful on the bigger nodes. I'd say it is a deal breaker.
