### ISSUE TITLE
Issues with `gluster-healthz` pods not launching correctly.

### ISSUE THREAD

**Issue by swade1987** [apprenda/kismatic#791]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug Request

**What happened**: The `Gluster-Healthz` pods don't spin up and running successfully.

**What you expected to happen**: The `Gluster-Healthz` pods to running successfully.

**How to reproduce it (as minimally and precisely as possible)**: 

- 2 Master nodes (load-balanced using TCP :6443 as its health check).
- 2 Ingress nodes (load-balanced using :80/healthz as its health check).
- 1 Etcd node
- 3 Worker nodes
- A GlusterFS storage cluster (spread across 2 dedicated nodes)
Note: Calico is used as the Overlay network for the Kubernetes cluster

**Anything else we need to know?**: This has happened multiple times before.

**Environment**:

- Kismatic version (use `kismatic version`): v1.5.3

- Plan file Gist (remove sensitive information if any): https://gist.github.com/swade1987/46f25475fd1c27f07740b332db05a1d0

- Cloud provider or hardware configuration: Digital Ocean

- OS (e.g. from /etc/os-release): 
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`): Linux bootstrap 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dkoshkin** [comment]
@swade is there anything in the logs or in the pod status that would indicate why it's not starting up?

**Comment by TimWoolford** [comment]
@swade have you added a volume yet? We found that an empty cluster would show in a similar state.

**Comment by jarkomes** [comment]
I also bumped in this issue when we still used Gluster, solution was to restart the rpcbind service on your gluster machines.

**Comment by swade1987** [comment]
@TimWoolford yes I had no volumes created. 
@jarkomes interesting solution.

**Comment by alexbrand** [comment]
Hard to tell what exactly happened here. Feel free to reopen if you have additional information/logs. With that said, it is expected for the pods to be down until at least one volume has been created.
