### ISSUE TITLE
Ability to apply Kismatic to a single node

### ISSUE THREAD

**Issue by swade1987** [apprenda/kismatic#803]
**FEATURE REQUEST**:

I would like to be able to apply Kismatic to a given node.

For example `kismatic install apply -f kismatic-cluster.yaml -n <node>`

**Comment by jaycoon** [comment]
Make that "given nodes" (default being "all nodes")

**Comment by swade1987** [comment]
That'd be `-n <node-a> -n <node-b>`

**Comment by swade1987** [comment]
This comes from a client request who wanted to make changes to the two ingress nodes and not wait for the whole cluster to be re-provisioned again.

**Comment by emmetthitz** [comment]
I can look into this. It should be reasonably easy, I think. It's on the back burner for now though while we work on the KET daemon.

**Comment by dkoshkin** [comment]
Removing from the `v1.8.0` milestone as it needs more discussion.
