### ISSUE TITLE
Add tolerations to components required on every node

### ISSUE THREAD

**Issue by willvrny** [apprenda/kismatic#804]
FEATURE REQUEST

**Description**:

It would be great to add tolerations to the components, such as Calico, that Kismatic installs.

The scenario where this would be useful is if a taint was added to a node to only allow a certain workload on it. It would be great to be able to add another taint allowing core cluster components so that they are not evicted or can not be rescheduled onto the node in case of failure.

I am not sure of the granularity that of these taints and tolerations. I wouldn't expect the kubernetes-dashboard or the tiller pod to be included with components such as Calico. This is because certain components are a hard requirement on the node.

Until this is added it might make it either difficult or introduce risk when using taints in a cluster.

**Comment by alexbrand** [comment]
We use the upstream deployment descriptors which already include tolerations. For example, the calico deployment includes the following tolerations:
```
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: |
          [{"key": "dedicated", "value": "master", "effect": "NoSchedule" },
           {"key":"CriticalAddonsOnly", "operator":"Exists"}]
```

I believe this is what you are referring to?

**Comment by TimWoolford** [comment]
@alexbrand From my understanding those tolerations are only effective if the Rescheduler is running

https://github.com/apprenda/kismatic/issues/611

**Comment by alexbrand** [comment]
@TimWoolford Would love to learn more about what you are doing, and see if we can bring it into KET.
