### ISSUE TITLE
kube-proxy not running as a DaemonSet

### ISSUE THREAD

**Issue by swade1987** [apprenda/kismatic#806]
**BUG REPORT**:

**What happened**:

kube-proxy is deployed as a pod to each node. 

**What you expected to happen**:

As kube-proxy needs to run on each node to manage the iptables/ipvs rules on it, it should be deployed as a DeamonSet because if the proxy dies on one of the nodes it'll never be rescheduled.

**Comment by alexbrand** [comment]
Kube-proxy is currently deployed as a static pod, so it will indeed be restarted if it goes down.

**Comment by swade1987** [comment]
What is the reason for this over using a DaemonSet?

**Comment by jaycoon** [comment]
Should be an upstream change; a lot of discussion on this already 
https://github.com/kubernetes/kubernetes/issues/23225

**Comment by willvrny** [comment]
@swade1987 @jaycoon @alexbrand it appears that it is being run as a daemonset in the official Kubernetes repository: 

https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/kube-proxy/kube-proxy-ds.yaml

**Comment by swade1987** [comment]
This is a duplicate of #951 this issue can be closed as #951 covers both.
