### ISSUE TITLE
Extend preflight checks to verify the registry has been seeded properly in a disconnected installation

### ISSUE THREAD

**Issue by alexbrand** [apprenda/kismatic#810]
After the work in #725, KET is no longer responsible for seeding a container image registry. Instead, the user is responsible for seeding a local registry before performing a disconnected installation.

In order to better the user experience, we should enhance our preflight checks to verify that all the images we need are available in the registry that has been configured in the plan file.

**Comment by dkoshkin** [comment]
Not really possible as the nodes are not yet configured with docker.
