### ISSUE TITLE
Upgrading to go v1.9 causes execution to hang at gathering facts

### ISSUE THREAD

**Issue by emmetthitz** [apprenda/kismatic#824]
**Is this a BUG REPORT or FEATURE REQUEST?**:
A bit of both?

**What happened**:
Glide v0.11.1 fails on macOS 10.13.0.
Upgrading Glide to v0.12.3 requires go v1.9 to handle dependencies properly.
Go 1.9 causes the execution of `./kismatic install apply` to hang during Gathering facts (possibly related to #635).

**What you expected to happen**:
I just want to spin up a cluster man. 

**How to reproduce it (as minimally and precisely as possible)**:
`go get github.com/apprenda/kismatic`
edit the Makefile to use go v1.9, and glide v0.12.3
`./provision vagrant create`
`./kismatic install apply`

**Anything else we need to know?**:
~switching to go v1.8.3 instead causes issues with CNI~
I'm an idiot

**Environment**:
- Kismatic version (use `kismatic version`):
1.5.3
- Plan file Gist (remove sensitive information if any): 

- Cloud provider or hardware configuration:?
Vagrant
- OS (e.g. from /etc/os-release):
macOS 10.13.0 High Sierra
- Kernel (e.g. `uname -a`):
Darwin 17.0.0

**Comment by emmetthitz** [comment]
This only seems to happen on vagrant.

**Comment by swade1987** [comment]
@emmetthitz i ran this from Master and didn't seem to get an issue.

**Comment by emmetthitz** [comment]
Yeah, I'm going to close this.

**Comment by swade1987** [comment]
I was going to do a PR to upgrade to using Golang 1.9.2, happy for me to do this?

**Comment by emmetthitz** [comment]
👍
