### ISSUE TITLE
Use seed-registry with a Proxy?

### ISSUE THREAD

**Issue by robotica72** [apprenda/kismatic#859]
First, this is a great add on - Congrats to Apprenda for beating the competition to an easier offline install.

Quick question - does the seed-registry command work with a Proxy?   I plan to try this tomorrow, but thought I would ask before banging my head for hours if it ignores any proxy variables.  I have a build machine that has proxy access but nothing with "pure" internet access.

Thanks!

**Comment by robotica72** [comment]
Answered my own question - its pulling containers using Docker pull, so the proxy settings in the Docker system.d section are used ... Excellent!  :)

**Comment by alexbrand** [comment]
Indeed! I am glad it’s working out for you. 

Let us know if you run into any issues.
