### ISSUE TITLE
kubelet and kube-controller-manager not reflecting cloud-provider value

### ISSUE THREAD

**Issue by snyamars** [apprenda/kismatic#867]
**BUG REPORT**:

**What happened**:
I am trying to setup kubernetes on AWS RHEL instance using kismatic. 
Added cloud_provider value as aws in kismatic-cluster.yaml. Ran the script. K8s successfully setup.
However, the value "--cloud-provider=aws" is not reflecting in the kubelet and kube-controller configuration at runtime.

**What you expected to happen**:
cloud provider value should reflect in the runtime configuration of kubelet and kube-controller-manager configuration.

**How to reproduce it (as minimally and precisely as possible)**:
Add cloud_provider, provider:aws to the kismatic_cluster.yaml and run the kismatic install apply command.
**Anything else we need to know?**:

**Environment**: Target OS: RHEL 7.4, Host OS: Ubuntu 14.04
- Kismatic version (use `kismatic version`): 1.5.3
- Plan file Gist (remove sensitive information if any): 
- Cloud provider or hardware configuration: AWS 
- OS (e.g. from /etc/os-release): RHEL 7.4
- Kernel (e.g. `uname -a`): 3.13.0-77-generic #121-Ubuntu x86_64 x86_64 x86_64 GNU/Linux

**Comment by dkoshkin** [comment]
@snyamars this feature was added in KET [v1.6.0](https://github.com/apprenda/kismatic/releases/tag/v1.6.0). 

Please upgrade and try again.

**Comment by snyamars** [comment]
@dkoshkin - I tried with KET v1.6.0. 
The scripts are failing with the following ansible error:
Validate Kubernetes Control Plane is Running  [ERROR]
- Task: get docker container ID for pod 'kube-controller-manager'
  ip-xxxxx.ec2.internal: the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'item' is undefined
The error appears to have been in '/ansible/playbooks/roles/validate-pod/tasks/validate-pod.yaml': line 32, column 5, but may be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:
  - name: get docker container ID for pod '{{ name }}'
    ^ here
Any suggestion on the above error?

**Comment by dkoshkin** [comment]
That looks like the api-server docker container is not running, check the container logs.

**Comment by snyamars** [comment]
api-server pod is running fine. 
kube-controller-manager pod is crashing with CrashLoopBackOff error. 
kube-controller-manager:
    Container ID:  docker://476459e499fc314e779656c05bc507d271ec16df763319098af922699f963b8d
    Image:         gcr.io/google-containers/kube-controller-manager-amd64:v1.8.0
    Image ID:      docker-pullable://gcr.io/google-containers/kube-controller-manager-amd64@sha256:9b1ae1007d3d0f4272e7ad5e8a6d34a1f49c2e3a33339773864aed525a667d26
    Port:          <none>
    Command:
      kube-controller-manager
      --allocate-node-cidrs=true
      --cloud-provider=aws
      --cluster-cidr=172.16.0.0/16
      --cluster-name=kubernetes
      --kubeconfig=/etc/kubernetes/controller-manager.conf
      --leader-elect=true
      --root-ca-file=/etc/kubernetes/pki/ca.pem
      --service-account-private-key-file=/etc/kubernetes/pki/service-account-key.pem
      --service-cluster-ip-range=172.20.0.0/16
      --use-service-account-credentials=true
      --v=2
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Tue, 17 Oct 2017 18:11:37 +0000
      Finished:     Tue, 17 Oct 2017 18:11:37 +0000
    Ready:          False

**Comment by snyamars** [comment]
Looks like the error is due to missing clusterID.
I1017 18:22:16.790466       1 aws.go:847] Building AWS cloudprovider
I1017 18:22:16.790553       1 aws.go:810] Zone not specified in configuration file; querying AWS metadata service
E1017 18:22:17.071314       1 tags.go:94] Tag "KubernetesCluster" nor "kubernetes.io/cluster/..." not found; Kubernetes may behave unexpectedly.
W1017 18:22:17.071339       1 tags.go:78] AWS cloud - no clusterID filtering applied for shared resources; do not run multiple clusters in this AZ.
F1017 18:22:17.071382       1 controllermanager.go:151] error building controller context: no ClusterID Found.  A ClusterID is required for the cloud provider to function properly.  This check can be bypassed by setting the allow-untagged-cloud option
