### ISSUE TITLE
New Command to start KET in HTTP server mode

### ISSUE THREAD

**Issue by dkoshkin** [apprenda/kismatic#878]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What you expected to happen**:
KET should expose a new method to interact with the clusters it manages. In addition to the existing CLI interface, a new HTTP interface will be added. 

The HTTP(s) server will be responsible for exposing a RESTful API to create, mutate, delete and view clusters.

Criteria:
- [x] new command - `kismatic server` starts an HTTP(s) server
- [x] handle JSON payloads
- [x] support TLS

**Comment by alexbrand** [comment]
Completed in #883.
