### ISSUE TITLE
HTTP Server Endpoints

### ISSUE THREAD

**Issue by dkoshkin** [apprenda/kismatic#879]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What you expected to happen**:
KET needs to expose a set of API endpoints to support cluster management over HTTP. 
The endpoints to Create,Update and Delete the cluster resource will all be asynchronous.  
The cluster name will be used as a key and will need to be unique for all clusters managed by that instance of KET.

**Cluster Resource**
- name: string
- state: string
- desiredState: string
- plan: KETPlan

**Endpoints**
- [x] GET /clusters
  Req body: empty
  Response: List of clusters

- [x] POST /clusters
  Req body: cluster resource
  Resp code: 201 (resource created)

- [x] PATCH /clusters/${name} (Kicking off a retry, adding/deleting workers)
  Resp: 202 Accepted
  Req body: cluster resource

- [x] GET /clusters/${name}
  Resp: Cluster details, including state (created, provisioning, installing, running, modifying, deleting)

- [x] DELETE /clusters/${name}
  Resp: 202 Accepted
  The client is responsible for checking if deletion was successful

- [x] GET /clusters/${name}/statuslogs
  Resp: If an operation is in progress, the logs of the current operation are returned. In any other 
  case, the logs of the previous operation are returned.

- [x] GET /clusters/${name}/kubeconfig
  Resp: Kubeconfig file for the cluster

- [x] GET /clusters/${name}/assets
  Resp: Returns a tarball or zip file containing all the generated assets of the cluster (kubeconfig, certificates, etc).

**Comment by alexbrand** [comment]
Closing, as this is done.
