### ISSUE TITLE
Create scaffolding workflow for spinning up a cluster based on plan output.

### ISSUE THREAD

**Issue by codymccain** [apprenda/kismatic#88]
# Problem
We would like to spin up clusters quickly for testing various configurations.  While the Kismatic tool drastically simplifies cluster creation, manual intervention is required during the bring up process to finalize the plan file with various parameters such as IP address, CIDR ranges, and several other policy and configuration options.

# Vagrant Scenario
Often, I spin up a small vagrant test cluster by running

```kismatic install plan```

After answering the node count and other questions, I create a matching Vagrant configuration of nodes.  The node IPs, and names (fqdn and short name for example, you could use the vagrant-dns plugin) need to be synchronized with the plan file.  Once additional options are set in the plan file (see enhancement #78 for a better way to capture this input) and the vagrant virtual machines have been brought up with `vagrant up` run 

```kismatic install validate```

and then

``` kismatic install apply```

to deploy kubernetes.

# Proposal

I propose we add an additional subcommand named `scaffold`.  This subcommand could accept a parameter identifying the target platform on which to scaffold (e.g. `vagrant`, `aws`, `packet`, etc.) the nodes necessary to implement the plan.  This target platform should be pluggable and adhere to a common API for specifying the node VM configurations for the cluster.  

`kismatic install scaffold` should bring up the target platform.  This subcommand should honor the global parameter for specifying a plan file since it needs to both read and write it.  Since it would bring up the platform, would should provide the appropriate `up`, `halt`, and `destroy` subcommands to `scaffold`.  

For example, if the target is
- `vagrant`, a Vagrantfile should be produced (we will need to capture the desired CIDR for generating the nodes and optionally could consume a go template as a parameter for controlling certain aspects of the Vagrantfile)
- `aws`, a CloudFormation script to bring up the nodes (the CLI should prompt the user for appropriate authentication credentials as well as region, availability zone, VPC, etc.).

Additionally, if scaffold specific parameters need to be saved (for halting, destroying, or bringing the cluster back up), those could be stored in the plan file as:

```
scaffold:
  vagrant:
    cidr: 192.168.50.0/24
```

A proposed order of operations is:

```kismatic install plan```

yielding the plan file.

```kismatic scaffold up --target vagrant```

This will bring up the Vagrant cluster.

```kismatic install apply```

will install the kismatic distribution on the new cluster.

**Comment by dasmb** [comment]
I've actually been working on something like this, though in reverse.

What I have is a separate `provision` command, which operates against AWS (and soon Vagrant/Virtualbox and Rackspace) to create new machines using the same technique as our integration tests.

After creation, the provision command generates a plan and fills in the details of the newly created resources.

e.g.

`provision aws --etcd=3 --master=2 --workers=4 --generatePlan`

will spin up 7 machines using AWS credentials in the user's environment and output a basic plan file that may be edited after `provision` completes.

**Comment by codymccain** [comment]
The order I specified allows for mapping a test cluster directly to a provided plan file and allows the planning step to work the same in all scenarios (instead of needing to provide switches).

This allows the scaffolding operation to be an optional step that can replace plan file prep that might be used during standard deployment.

The goal here would be to maintain well-understood workflow with pluggable steps.

**Comment by dasmb** [comment]
https://github.com/apprenda/kismatic-provision 

Please review. As it stands, this tool is intended to GENERATE a plan file, but it could also take input from a plan if this is desirable.

**Comment by codymccain** [comment]
I recommend closing this issue and moving further enhancement requests for provisioning functions over to the new http://github.com/apprenda/kismatic repo.
