### ISSUE TITLE
Store to support HTTP API

### ISSUE THREAD

**Issue by dkoshkin** [apprenda/kismatic#882]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What you expected to happen**:
To support the newly proposed HTTP API, KET will need to keep state. The HTTP server should be responsible for only responding to requests and updating the store, it will not manipulate the clusters directly. A separate process will watch for changes in the store and act accordingly. 

This issue will track the work required to implement the store.

Criteria:
- [x] Data must be persisted to disk to recover from failures and restarts
- [x] Must support transactions as multiple processes will be interacting with it concurrently. 
- [x] Preferably support watching for changes

**Comment by alexbrand** [comment]
Closing as this is done.
