### ISSUE TITLE
New provision command to generate terraform config 

### ISSUE THREAD

**Issue by emmetthitz** [apprenda/kismatic#885]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature request

Similar to how the current provisioner generates a plan file, the new provision command should generate terraform variables from the relevant proposed plan file changes.

- [x] Add the static templates for provider-specific defaults and information that is unlikely to change.
- [ ] Add command to generate the dynamic data needed for cluster provisioning (node numbers and their respective IPs, SSH keys, etc). This generated data should be variables that fit into the static data.
- [ ]  Modify plan file and plan file generation to incorporate this new data.

**Comment by emmetthitz** [comment]
- [ ] Add the static templates for provider-specific defaults and information that is unlikely to change.
- [ ] Add command to generate the dynamic data needed for cluster provisioning (node numbers and their respective IPs, SSH keys, etc). This generated data should be variables that fit into the static data.
- [ ]  Modify plan file and plan file generation to incorporate this new data.

**Comment by alexbrand** [comment]
Closing as this is complete.
