### ISSUE TITLE
Labels appear in the plan file for etcd nodes

### ISSUE THREAD

**Issue by emmetthitz** [apprenda/kismatic#887]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug report

Exactly what the title says. Etcd nodes should not have node labels since they are not running a kubelet. This occurs through either plan file generation via a kismatic plan, or via the provisioner.

**Comment by swade1987** [comment]
Can we get this added to the 1.7.0 release, this seems like a tidying up exercise.

**Comment by emmetthitz** [comment]
You would think. It's actually a bit of a foundational problem, so the fix isn't as easy as we'd first hoped. There might be some hack/workaround to fix this that I haven't thought of, but I couldn't think of an easy or clean one - so it got shelved for a little while we got re-prioritized to the KET daemon.

**Comment by swade1987** [comment]
I feel though that if we are adding features which are "incomplete" which in this case I would say that this falls into this category they should really be fixed in the subsequent release. Otherwise, we are just giving ourselves more technical debt.

**Comment by dkoshkin** [comment]
Fixed in https://github.com/apprenda/kismatic/pull/1042
