### ISSUE TITLE
1.6.1 Release Missing Release Archives

### ISSUE THREAD

**Issue by WillPlatnick** [apprenda/kismatic#888]
Hello,
I saw 1.6.1 was released on GitHub, but it doesn't have the release zip and tar, only the source. Is 1.6.1 supposed to be officially out?

**Comment by dkoshkin** [comment]
@WillPlatnick 1.6.1 has not been released yet as we are still waiting on the official kubernetes `v1.8.1` DEB packages.
Github automatically creates the zip files for a tag.

I will close this issue once 1.6.1 is released.

**Comment by WillPlatnick** [comment]
Thank you @dkoshkin  - Are there any show stopper bugs that that would discourage me from moving to 1.6.0? I'm currently working on some calico networking issues when masters become unavailable, and I wanted to get on a later version to continue troubleshooting.

**Comment by dkoshkin** [comment]
@WillPlatnick feel free to use 1.6.0, only minor enhancements were added.

Notable Changes
---
* Validate admin passwords to be safe for URL encoding (https://github.com/apprenda/kismatic/issues/560)
* Use proper kube-proxy health port 10256 that was changed in kuberntes 1.7 (https://github.com/apprenda/kismatic/issues/809)
* Deploy critical pod rescheduler addon (https://github.com/apprenda/kismatic/pull/873)
* New field `docker_registry.server` replaces `docker_registry.address` and `docker_registry.port`. These fields are now deprecated but will still function until they are completely removed in a later release (https://github.com/apprenda/kismatic/pull/869)
* Enable prometheus metrics endpoint in kube-dns (https://github.com/apprenda/kismatic/issues/880)
* Update Go and Glide in the build process (https://github.com/apprenda/kismatic/pull/861)

**Comment by alexbrand** [comment]
Closing as 1.6.1 is up.
