### ISSUE TITLE
Create one-time password for automatically updating ~/kube/config

### ISSUE THREAD

**Issue by McCodeman** [apprenda/kismatic#89]
# Problem
As new operators join a team, they have to acquire the private keys necessary to interact with the Kubernetes API endpoint.  Copying keys via Slack, email or other communication channel can be insecure and cumbersome.

# Proposal
I propose we create a kismatic subcommand for generating a one-time password that can be used by the kismatic tool to fetch the necessary private keys and automatically configure a user's `~/kube/config` for connecting to the cluster.  A proposed scenario would be as follows.

Existing user with authentication credentials issues

```kismatic authn token```

Existing user receives an opaque one-time use text token that expires after a set period of time.  This token can then be handed off to the user needing access via a standard communication channel.

The new user can then issue the command

```kismatic authn fetch {token}```

(please suggest subcommand name alternatives, not sure what this should be).

This would (optionally generate a new private key), fetch the private key and update `~/kube/config` with necessary information to authenticate to the k8s API.  Also, it would fetch the private node ssh key for running the kismatic tool (maybe these should be separate commands and later authorized with RBAC).  Once the API key is in place, `kubectl config --set-context` could be run with the appropriate cluster name to default authentication for `kubectl`.

**Comment by dasmb** [comment]
Good idea Cody. Given that our authentication model is currently weak, I would suggest we create only full admin users using this technique but would eventually expand it to include a more robust auth Z model.

**Comment by alexbrand** [comment]
This is an interesting idea, but I am not sure it belongs in KET. Feel free to reopen.
