### ISSUE TITLE
Upgrade Helm

### ISSUE THREAD

**Issue by willvrny** [apprenda/kismatic#891]
Helm currently has a newer patch release (2.6.2) than what we are using (2.6.1), which includes bug fixes. 

They've also released 2.7.0 version that is compiled against Kubernetes 1.8. It might be worthwhile to make the jump?

At a minimum we should upgrade to 2.6.2.

**Comment by jaycoon** [comment]
Besides supporting K8s 1.7, Helm 2.7.0 focuses on production stability and reliability; definitely a worthwhile jump from 2.6.1.
