### ISSUE TITLE
Rollback support.

### ISSUE THREAD

**Issue by st4nson** [apprenda/kismatic#896]
Hi, does _kismatic_ support rollback ? If not is this somehow on a roadmap ?

**Comment by alexbrand** [comment]
Hey @st4nson - we currently don't support rollback or uninstall. We don't have anything planned on this respect in the short term roadmap.

**Comment by st4nson** [comment]
Thanks for reply Alex. If I would change version in `/etc/kismatic-version` could that work ? ;)

**Comment by alexbrand** [comment]
@st4nson What are you trying to achieve?

**Comment by st4nson** [comment]
Find a possibility to rollback to earlier version of `kismatic`/`kubernetes`.

**Comment by st4nson** [comment]
Just for info, I've manged to `rollback` from kismatic version `1.6.1` to `1.6.0`. Of course this is unofficial way and one should know what he's/she's doing.
