### ISSUE TITLE
Executing chaos on the cluster

### ISSUE THREAD

**Issue by swade1987** [apprenda/kismatic#90]
It would be useful to have a "kismatic chaos" command like primitive to test the simulation of failures of instances within the default cluster. Perhaps it could be a separate repository called "khaos" ?

**Comment by alexbrand** [comment]
This sounds like a separate tool (outside of `kismatic`) that is part of the KET. Can you elaborate on what "default cluster" means?

**Comment by swade1987** [comment]
The default cluster would be the cluster after the execution of the plan file. 
So after executing the plan you could execute "chaos" 
This would provide an output to see how well the cluster can handle the failure.

**Comment by dasmb** [comment]
There are some interesting ideas here and some neat tools available.
