### ISSUE TITLE
Failed to stop kube-apiserver during upgrade

### ISSUE THREAD

**Issue by bacher09** [apprenda/kismatic#912]
Kismatic version: 1.6.1
Environment: bare metal
OS: Ubuntu 16.04.3
Kernel: 4.4.0-87-generic

I was upgrading cluster from kismatic 1.6.0 to 1.6.1 and faced with this issue:

    Stop Kubernetes Control Plane                                                   [ERROR]                                                                      
    - Task: wait until kube-apiserver is stopped                                                                                                    
      kube-master-01.example: Timeout when waiting for 127.0.0.1:8080 to stop.      [ERROR]                                                                         
    Failed to upgrade nodes: error upgrading node "kube-master-01.example": error running playbook: error running ansible: exit status 2

*Note*: I replaced server name

When I manually killed `kube-apiserver` and repeated operation upgrade succeeded.

It seems this happened because during upgrade kismatic stopped `kubelet` on master node and [removing manifest](https://github.com/apprenda/kismatic/blob/master/ansible/_kube-control-plane-stop.yaml#L20) was not enough to stop `kube-apiserver`.

**Comment by swade1987** [comment]
@bacher09 i am wondering if replacing the server name during the upgrade process caused an issue?

**Comment by swade1987** [comment]
@bacher09

I think when replacing the server its best to perform an `apply` with the old version and then an `upgrade`.

The reason for this is an `upgrade` expects all nodes to already be running the previous version of kismatic.

Therefore, you are happy for us to close this issue?

**Comment by JRaver** [comment]
Hi, we have already successfully upgraded Kismatic from 1.6.1 to 1.7.1. Without any issue. We used this command ./kismatic upgrade online. That's why you can close this bug.

**Comment by bacher09** [comment]
Sorry, but currently I have no access to such environment. But we have tested upgrade process few times and it had same issue again. Issue happened only when upgrading `1.6.0` to `1.6.1`. Other versions had no such issue.

You probably can close this issue, cause this version already old enough.
