### ISSUE TITLE
File basicauth.csv is overwritten during upgrade

### ISSUE THREAD

**Issue by bacher09** [apprenda/kismatic#914]
Kismatic version: 1.6.1
Environment: bare metal
OS: Ubuntu 16.04.3
Kernel: 4.4.0-87-generic

During process of cluster upgrade file `/etc/kubernetes/auth/basicauth.csv` is overwritten. Because of this, users that was manually created and added to `basicauth.csv` will disappear. 

Probably it's good to add some warning for this behaviour, or maybe stop overwriting this file if it contains more then one line.

**Comment by alexbrand** [comment]
Thanks @bacher09 

We'll take a look shortly.
