### ISSUE TITLE
Preflight checks fail when adding a worker if preflight was originally skipped

### ISSUE THREAD

**Issue by alexbrand** [apprenda/kismatic#918]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**What happened**: Attempted to add a new worker using the `add-worker` command, but the preflight checks failed when attempting to run them from the master node. The log messages indicate that the inspector binary is not on the master node.

**What you expected to happen**: Preflight check should be able to run from the master node

**How to reproduce it (as minimally and precisely as possible)**:
```
./kismatic install apply --skip-preflight
./kismatic install add-worker
```

**Comment by dkoshkin** [comment]
During a merging the fix for this was unintentionally reverted.
Because the inspector will was modified in `KET v1.8.0` this will also fail when adding workers after upgrading from a cluster installed with a previous version.

A workaround for now is to run prior to adding a new worker:
```
kismatic install step copy-inspector.yaml
```
