### ISSUE TITLE
Setup Calicoctl on all nodes 

### ISSUE THREAD

**Issue by swade1987** [apprenda/kismatic#932]
The issue title says it all.

**Comment by swade1987** [comment]
This is based off the need to have this during a support call.

**Comment by dkoshkin** [comment]
There is no easy way to distribute the binary, it will have to be up to the operator to install it if required.

**Comment by swade1987** [comment]
@dkoshkin have to disagree with closing this, calicoctl is the main debugging tool for calico.

Not having this available on all nodes in the cluster really reduces the ability to diagnose overlay network related issues.
