### ISSUE TITLE
Provisioner: AWS provider should create a load balancer when standing up multiple API servers

### ISSUE THREAD

**Issue by alexbrand** [apprenda/kismatic#934]
Currently, the AWS provisioner is able to create multiple master nodes. However, this is still not an HA setup given that all cluster components are being setup to talk to the first master node. 

In order to achieve a truly HA setup, we must create a load balancer when multiple master nodes are in play to load balance access to the API server endpoint. The load balancer configuration should include health checking to detect when a downstream instance is down.

**Comment by emmetthitz** [comment]
My only concern here is extending this then to the provider-agnostic cases. Is there no way to do this with kube-proxy?

**Comment by emmetthitz** [comment]
Should there be separate buckets for load balancer logs for each cluster?
