### ISSUE TITLE
Provisioner: Improve tagging of the resources provisioned by KET

### ISSUE THREAD

**Issue by alexbrand** [apprenda/kismatic#935]
In order to quickly and easily find infrastructure that was created by KET, all resources should be tagged with a consistent scheme.

We must devise our own tagging style and be consistent through out. I have seen different styles in AWS for the tag keys: `aws:cloudformation:logical-id`, `kubernetes.io/cluster/testcluster7405`, `OpsFunction`, etc.

At a minimum, all resources created for a specific cluster should be tagged with `kismatic/clusterName` = `${clusterName}` (or something of the sort).

Nodes should be tagged with their roles: `kismatic/nodeRole` = `${join(nodeRoles, ",")}`.

**Comment by dkoshkin** [comment]
In addition to that labeling we will also need to tag machines as described in https://github.com/apprenda/kismatic/issues/767, we do similar tagging in our integration tests.
