### ISSUE TITLE
Improve disconnected installation process when the user is unable to run `seed-registry`

### ISSUE THREAD

**Issue by alexbrand** [apprenda/kismatic#944]
**Scenario**
The user is running a registry that is disconnected from the internet, and the user has no access to that registry from a machine that has internet access.

**Current Approach**
The user can download KET on a machine that has internet access, and use the seed-registry command with the --list-only flag to display the images needed for the installation. Once downloaded, the user can save these to a tarball and somehow move them over to the machine running the registry. I am not sure if there's anything that we can do to improve this, other than having a pre-built tarball with all the images.

The bigger issue is that the user now has to go over to the registry machine, import the images, and manually retag them with their registry url. It's very easy to get this wrong. It is also time consuming.

**Potential Solutions**
- Documentation: We could document a script that will retag all the images in a given tarball. This might have the downside of having to maintain the list of images in this doc. Easy to get out of sync.

- Generate script/documentation in `seed-registry` command: Maybe we can generate the script(s)/documentation and print it to the screen if a specific flag is used. This is useful because the script/docs would be generated based on the list of images that are needed. We might even want to generate multiple scripts: 1. For downloading and creating a tarball of all images, 2. Extracting the tarball, tagging and seeding the registry.

- Add new modality to the seed-registry command: This new mode would have two "sub-commands" or flags. The first one will produce a version-tagged tarball and it will be run on a machine that has internet access. The second one will use the tarball as input to seed the registry, and will be run on the machine that has the registry running.

**Comment by dkoshkin** [comment]
Disconnected Installs are an advanced feature, the tool already provides a mechanism to seed the registry or get a list of images, it would be up to the operator to seed the registry if the provided method does not work.
