### ISSUE TITLE
Add labels to kube-dns to enable prometheus scraping

### ISSUE THREAD

**Issue by alexbrand** [apprenda/kismatic#945]
The following labels have to be added to the kubedns service so that prometheus can get metrics:
```
prometheus.io/port: “10054”
prometheus.io/scrape: “true”
```

cc: @swade1987

**Comment by swade1987** [comment]
@alexbrand would be very useful as currently, we don't have the `dns-horizontal-autoscaler` installed. I think @dkassab was asking for this a few months back.
