### ISSUE TITLE
Deprecate/Remove NFS storage volume support from plan file

### ISSUE THREAD

**Issue by alexbrand** [apprenda/kismatic#946]
The original purpose for adding NFS storage was to support stateful workloads that KET would deploy after installation, such as prometheus, EFK, etc. 

Given that we have already decided that KET is not responsible for deploying these workloads, there is no real need for the NFS volume mounting feature. 

If the user intends to use NFS with their cluster, they can create and configure persistent volumes using `kubectl`. This is the native way of adding persistent storage to Kubernetes clusters, and it also exposes a variety of options not exposed via KET.

**Comment by swade1987** [comment]
We should also maybe remove https://github.com/apprenda/kismatic-charts/

**Comment by swade1987** [comment]
I feel that removing the below from the plan file makes sense.

```nfs:
  nfs_volume: []```

However, having a GlusterFS cluster be provisioned is pretty useful in my opinion.
