### ISSUE TITLE
Install fails when using a proxy and separate load balancer

### ISSUE THREAD

**Issue by TDeprez** [apprenda/kismatic#954]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug

**What happened**:
Using a proxy and separate load balancer (ie not a master node), the install fails here:

TASK [run helm init]
Error: error installing: Post https://hlb.kube.bmguk:6443/apis/extensions/v1beta1/namespaces/kube-system/deployments: Forbidden

This request is being sent to the proxy server

**What you expected to happen**:
The 'no_proxy' section of the config has this note
"All nodes' 'host' and 'IPs' are always set."
I'd expect this to also include 'load_balanced_fqdn'

**How to reproduce it (as minimally and precisely as possible)**:
Run an install using a proxy server and load balancer (we used HA Proxy).

**Anything else we need to know?**:

**Environment**:
- Kismatic version (use `kismatic version`): 1.6.3
- Plan file Gist (remove sensitive information if any): https://gist.github.com/TDeprez/0375854f96445e93f8d11d1ca213b60e
- Cloud provider or hardware configuration: Bare metal
- OS (e.g. from /etc/os-release): Centos 7
- Kernel (e.g. `uname -a`): Linux *** 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dkoshkin** [comment]
Hi @TDeprez unfortunately the LB setup will be highly specific to each user and KET cannot assume it is not behind a proxy.

I would recommend setting the `load_balanced_fqdn` in the `no_proxy` for this scenario.
