### ISSUE TITLE
Storage and Ingress node labels aren't applied so services are unavailable

### ISSUE THREAD

**Issue by jlmeeker** [apprenda/kismatic#958]
**BUG REPORT**:

**What happened**:
Applying clean plan with storage and ingress enabled, nodes aren't labeled with kismatic/storage=true and kismatic/ingress=true.  Without these labels ingress and storage daemonsets have no endpoints as no nodes match the selector.

**What you expected to happen**:
When nodes are assigned to the plan document in storage and ingress sections... they should get the necessary labels so the specified services work.

**How to reproduce it (as minimally and precisely as possible)**:
Create a default plan and add nodes to ingress and/or storage.  Look at daemonsets and notice that there are no running pods (DESIRED, CURRENT, READY, UP-TO-DATE,AVAILABLE columns are all zero) for gluster-healthz, ingress, default-http-backend services.

**Anything else we need to know?**: 
If node labeling is meant to be manual, please udpdate documentation to reflect so.  Manually labeling the nodes immediately fixed the problem as pods were created and the services worked as intended.

**Environment**:
- Kismatic version (use `kismatic version`): 1.6.1 & 1.6.3
- Plan file Gist (remove sensitive information if any): n/a
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from /etc/os-release): CentOS7
- Kernel (e.g. `uname -a`): 3.10

**Comment by jaycoon** [comment]
This currently happens in an upgrade scenario, if you want to add storage nodes _**after**_ installing the initial platform.

When setting up the cluster with storage nodes initially, labels are added as expected.

This is **feature request**, to make it possible to add storage and ingress nodes to an existing cluster; it would be an enhancement to `add-worker` to specify the type of worker.

**Comment by jlmeeker** [comment]
I guess all that is needed then is an updated https://github.com/apprenda/kismatic/blob/master/docs/storage.md document that also says to manually label the nodes when running "kismatic install step _storage.yaml".  

This is the document I followed when adding storage to my cluster after the initial setup.

**Comment by jaycoon** [comment]
We will keep this flagged as a bug and try to identify the problem when upgrading. The labels should be set in the kubelet systemd unit file and applied.

For reference, the node labels are defined in `group_vars/all.yaml` under `kubelet_defaults.node-labels`.
