### ISSUE TITLE
Provisioner: Add support for Azure

### ISSUE THREAD

**Issue by emmetthitz** [apprenda/kismatic#963]
Currently only supports AWS, we need to add support for Azure in order to iron out any kinks that might be left with the kismatic codebase.

**Comment by emmetthitz** [comment]
Specific issues moving forward:
- Azure login information is handled weirdly by Terraform. Terraform seems to expect a login token from the Azure CLI as its first priority. If this isn't set, Terraform will complain (even if the environment variables reported in the docs _are_ set correctly). This means we either need to persist that information to disk (including the secret) to supercede this priority, or just authenticate through the azure CLI each time we want to use Terraform, which is not feasible in daemon mode.

- The Azure API has numerous race conditions that cause non-deterministic behavior during creation, modification, and deletion of cluster resources. The most easily reproducible one involves issuing a delete on NICs and a subnet simultaneously (I.E. destroying a cluster). The API will attempt to delete both, but will complain about how you can't delete the subnet since a NIC is still attached. The NICs will delete just fine. Re-issuing the request will cause expected behavior, since there's no longer NICs prevent subnet destruction.

**Comment by emmetthitz** [comment]
I'm not sure which/what exactly is on Terraform vs what's on the API. I believe the latter is on the Azure API since this behavior can be re-created via the web UI. 

The former issue is, I think, a bug with Terraform. The workaround of persisting that information to disk is, I think, the only way to get it to work. I'm not sure which solution I hate less.

**Comment by alexbrand** [comment]
Hey @emmetthitz - I was able to use terraform with Azure without the Azure CLI by setting the appropriate environment variables as documented here: 
https://www.terraform.io/docs/providers/azurerm/

**Comment by emmetthitz** [comment]
Huh. Alright. I'll take another look. Thanks @alexbrand.

**Comment by alexbrand** [comment]
Make sure to remove the config in the provider in `main.tf` so that they are picked up from the env.

**Comment by emmetthitz** [comment]
That's probably the reason why. I think aws doesn't care if that exists or not, so I assumed this would also be the case.
