### ISSUE TITLE
Upgrade: Calico does not shutdown in time

### ISSUE THREAD

**Issue by dkoshkin** [apprenda/kismatic#964]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
When performing an upgrade Calico node did not shutdown in time 120 seconds. Failed in:
```
name: wait until the calico pod running on this node is deleted
```
When we waited for another minute or 2 it shut down properly. 

Their cluster has been running for a few months now and it looks Calico is doing some cleanup that takes some time that we do not see during short term integration tests.

**What you expected to happen**:
Calico to shutdown in time.

**How to reproduce it (as minimally and precisely as possible)**:
Upgrade a cluster that has been running for a few months.

**Anything else we need to know?**:

**Environment**:
- Kismatic version (use `kismatic version`):
Upgrading from `v1.5.2` to `v1.6.3`
- OS (e.g. from /etc/os-release):
RHEL

**Comment by alexbrand** [comment]
Fixed by #943
