### ISSUE TITLE
Incorporate Weave Scope out the box

### ISSUE THREAD

**Issue by swade1987** [apprenda/kismatic#97]
The toolkit should spin up [Weave Scope](https://www.weave.works/guides/monitor-docker-containers/) by default to provide the user with an easy to understand holistic overview of what was built and running.

We simply need to execute 

```kubectl apply -f 'https://cloud.weave.works/launch/k8s/weavescope.yaml?k8s-service-type=NodePort'```

**Comment by willvrny** [comment]
Would it be better to copy the yaml file into the project? I could imagine some environments being locked down and not allow access to the weaveworks website.

**Comment by swade1987** [comment]
@willvrny that is a great point and definitely something we should do.

**Comment by willvrny** [comment]
@swade1987 Scope also runs in privileged mode. Should we make it opt in because of this?

**Comment by WillPlatnick** [comment]
I've also seen Scope be very resource intensive (but while being used) - I'd rather this be opt in

**Comment by alexbrand** [comment]
Closing this for now as installing weave scope should be simple enough with kubectl. Feel free to reopen.
