### ISSUE TITLE
Is there an easy way to decommission the kubernetes cluster?

### ISSUE THREAD

**Issue by fredzqm** [apprenda/kismatic#970]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What happened**:
We created a cluster of two to first figure out how it works, and then wants to shut it down and starts a new cluster with more nodes. However, we did not find a good way of shutting down the first test cluster.

**What you expected to happen**:
I would like to run something like `kismatic shutdown`, so that I use the same nodes to build another cluster. Right now, I can't find an easy way to do this cleanly.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:
- Kismatic version (use `kismatic version`): 1.6.3
- Plan file Gist (remove sensitive information if any): 
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): ubuntu
- Kernel (e.g. `uname -a`): Linux chef 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by emmetthitz** [comment]
Kismatic is not currently responsible for the underlying infrastructure. If you want to decommission a cluster, you either have to do it through your cloud provider manually, or over whatever bare metal setup you're running.

**Comment by fredzqm** [comment]
Got it. Thanks!
