### ISSUE TITLE
Support for authentication & authorization webhooks

### ISSUE THREAD

**Issue by bacher09** [apprenda/kismatic#979]
It's nice to have ability to configure [authentication](https://kubernetes.io/docs/admin/authentication/#webhook-token-authentication) and [authorization]() webhooks during setup. It can't be simply achieved by adding options to apiserver since it also requires extra configuration file that should be available in apiserver POD.

It also possible related with [this](https://github.com/kubernetes/kubernetes/issues/52511).

**Comment by alexbrand** [comment]
Thanks @bacher09. Do you think you'd be able to create a proposal or PR for this?

**Comment by bacher09** [comment]
Actually I would like to discuss implementation first before making any PR.

I think that easiest way to do this, is create directory with custom data that will be copied to '/etc/kubernetes' on master nodes. So [webhook config](https://kubernetes.io/docs/admin/authorization/webhook/#configuration-file-format) can be placed in such directory and it will be copied there before kubernetes services are started. Also, this design is generic enough to be useful for other use cases, since many options of 'kube-apiserver' requires file. For example, if someone is using authorization via oidc they can provide '--oidc-ca-file' in same way. To make this design really reusable for some other cases, it will probably require more than one directory. Maybe something like 6 of them. Since, in some cases it also useful to provide custom manifests, for example authentication webhook service can be self-hosted and provided by custom manifest. Also, users need to specify where this files would be placed, on master node, on slave or on both of them.

So, what do you think about such design. Is it ok ?

**Comment by vasilievip** [comment]
@alexbrand pls take a look https://github.com/apprenda/kismatic/pull/1118
