### ISSUE TITLE
Provisioner: Storing the terraform plan might leave cloud provider credentials on disk

### ISSUE THREAD

**Issue by alexbrand** [apprenda/kismatic#981]
We currently run `terraform plan` and store the output on disk to then feed to the `terraform apply` command. According to the [documentation](https://www.terraform.io/docs/commands/plan.html#security-warning), this might leave variables on disk, including the cloud provider credentials or any other secret.

**Comment by swade1987** [comment]
You should set up an S3 bucket for "remote-state"

**Comment by emmetthitz** [comment]
We considered this in the beginning, but ultimately running KET as a server also solves this problem. Depending on provider-specific tech also means we're less flexible when it comes to the bare-metal cases.

**Comment by emmetthitz** [comment]
After some testing, this doesn't seem to be the case for AWS or Azure, but does not guarantee that other providers won't do the same. That said, this still has to occur in server mode, so secrets will be left on disk in that case. Closing this.
